### ISSUE TITLE
Compiler crash for erroneous `Task` type

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#1071]
Changing the `Closure.roc` benchmark to this:

```elm
main : Task.Task (Result (Num *) [ ListWasEmpty ]*) []
main =
    Task.succeed (List.first [ 12, 9, 6, 3 ])
```

...resulted in this compiler crash:

```
Mismatch in compiler/unify/src/unify.rs Line 1072 Column 29
Trying to unify two flat types that are incompatible: TagUnion({Private(`fx.Effect.Effect`): [85]}, 83) ~ Erroneous(BadTypeArguments { symbol: `base.Task.Task`, region: |L 5-5, C 7-57|, type_got: 3, alias_needs: 2 })

Mismatch in compiler/unify/src/unify.rs Line 1072 Column 29
Trying to unify two flat types that are incompatible: Erroneous(BadTypeArguments { symbol: `base.Task.Task`, region: |L 5-5, C 7-57|, type_got: 3, alias_needs: 2 }) ~ Erroneous(BadTypeArguments { symbol: `base.Task.Task`, region: |L 5-5, C 7-57|, type_got: 3, alias_needs: 2 })

Mismatch in compiler/unify/src/unify.rs Line 1072 Column 29
Trying to unify two flat types that are incompatible: Erroneous(BadTypeArguments { symbol: `base.Task.Task`, region: |L 5-5, C 7-57|, type_got: 3, alias_needs: 2 }) ~ TagUnion({Private(`fx.Effect.Effect`): [69]}, 2)

thread '<unnamed>' panicked at 'TODO handle invalid function Erroneous', compiler/mono/src/ir.rs:2140:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

I tried removing the extra `[]` at the end of the type and got:

```
Trying to unify two flat types that are incompatible: TagUnion({Global('Ok'): [163], Global('Err'): [165]}, 126) ~ Record({}, 1)

Mismatch in compiler/unify/src/unify.rs Line 870 Column 9
Problem with Tag Union
There should be 1 matching tags, but I only got 
{}

Mismatch in compiler/unify/src/unify.rs Line 1072 Column 29
Trying to unify two flat types that are incompatible: TagUnion({Global('Ok'): [306], Global('Err'): [307]}, 2) ~ Record({}, 1)

Mismatch in compiler/unify/src/unify.rs Line 870 Column 9
Problem with Tag Union
There should be 1 matching tags, but I only got 
{}

thread '<unnamed>' panicked at 'unificaton failure for `#UserApp.main`', compiler/mono/src/ir.rs:1798:5
```

**Comment by JanCVanB** [comment]
FWIW, I get this today:
```
[jan@framey roc]$ cat examples/benchmarks/Closure.roc 
app "closure"
    packages { pf: "platform/main.roc" }
    imports [pf.Task]
    provides [main] to pf

# see https://github.com/roc-lang/roc/issues/985
main : Task.Task (Result (Num *) [ ListWasEmpty ]*) []
main = 
    Task.succeed (List.first [ 12, 9, 6, 3 ])
[jan@framey roc]$ 
[jan@framey roc]$ roc examples/benchmarks/Closure.roc

── TYPE MISMATCH ─────────────────────── examples/benchmarks/platform/main.roc ─

Something is off with the type annotation of the main required symbol:

2│      requires {} { main : Task {} [] }
                             ^^^^^^^^^^

This #UserApp.main value is a:

    Task (Result (Num *) [ListWasEmpty]*) [] ?

But the type annotation on main says it should be:

    Task {} [] ?


── TYPE MISMATCH ─────────────────────── examples/benchmarks/platform/main.roc ─

Something is off with the body of the mainForHost definition:

8│  mainForHost : Task {} [] as Fx
9│  mainForHost = main
                  ^^^^

This #UserApp.main value is a:

    Effect.Effect (Result (Result (Num *) [ListWasEmpty]*) []) ?

But the type annotation on mainForHost says it should be:

    Fx ?

Tip: Type comparisons between an opaque type are only ever equal if
both types are the same opaque type. Did you mean to create an opaque
type by wrapping it? If I have an opaque type Age := U32 I can create
an instance of this opaque type by doing @Age 23.

────────────────────────────────────────────────────────────────────────────────

2 errors and 0 warnings found in 26 ms.

You can run the program anyway with roc run examples/benchmarks/Closure.roc
[jan@framey roc]$ 
[jan@framey roc]$ roc run examples/benchmarks/Closure.roc 
thread 'main' panicked at 'internal error: entered unreachable code: symbol/layout `18.IdentId(17)` ProcLayout {
    arguments: [
        Struct {
            field_order_hash: FieldOrderHash(
                0,
            ),
            field_layouts: [],
        },
        LambdaSet(
            LambdaSet {
                set: [
                    ( 18.17, [Union(NonRecursive([[Union(NonRecursive([]))], [Union(NonRecursive([[Struct { field_order_hash: FieldOrderHash(0), field_layouts: [] }], [Builtin(Int(I64))]]))]]))]),
                ],
                representation: Interned(
                    0,
                    PhantomData,
                ),
            },
        ),
    ],
    result: Union(
        NonRecursive(
            [
                [
                    Union(
                        NonRecursive(
                            [],
                        ),
                    ),
                ],
                [
                    Struct {
                        field_order_hash: FieldOrderHash(
                            0,
                        ),
                        field_layouts: [],
                    },
                ],
            ],
        ),
    ),
    captures_niche: CapturesNiche(
        [
            Union(
                NonRecursive(
                    [
                        [
                            Union(
                                NonRecursive(
                                    [],
                                ),
                            ),
                        ],
                        [
                            Union(
                                NonRecursive(
                                    [
                                        [
                                            Struct {
                                                field_order_hash: FieldOrderHash(
                                                    0,
                                                ),
                                                field_layouts: [],
                                            },
                                        ],
                                        [
                                            Builtin(
                                                Int(
                                                    I64,
                                                ),
                                            ),
                                        ],
                                    ],
                                ),
                            ),
                        ],
                    ],
                ),
            ),
        ],
    ),
} combo must be in DeclarationToIndex', crates/compiler/mono/src/borrow.rs:165:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
^C
[jan@framey roc]$ 
```

**Comment by ayazhafiz** [comment]
We now generate an appropriate type error message here!

```
── TYPE MISMATCH ──── crates/cli_testing_examples/benchmarks/platform/main.roc ─

Something is off with the type annotation of the main required symbol:

2│      requires {} { main : Task {} [] }
                             ^^^^^^^^^^

This #UserApp.main value is a:

    Task (Result (Num *) [ListWasEmpty]*) []

But the type annotation on main says it should be:

    Task {} []


── TYPE MISMATCH ──── crates/cli_testing_examples/benchmarks/platform/main.roc ─

Something is off with the body of the mainForHost definition:

8│  mainForHost : Task {} [] as Fx
9│  mainForHost = main
                  ^^^^

This #UserApp.main value is a:

    Effect.Effect [Err [], Ok (Result (Num *) [ListWasEmpty]*)]

But the type annotation on mainForHost says it should be:

    Fx

Tip: Type comparisons between an opaque type are only ever equal if
both types are the same opaque type. Did you mean to create an opaque
type by wrapping it? If I have an opaque type Age := U32 I can create
an instance of this opaque type by doing @Age 23.

────────────────────────────────────────────────────────────────────────────────
```
