### ISSUE TITLE
Compiler panic from attempt at cyclic definition

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#1166]
This code causes a compiler panic in canonicalization:

```elm
app "sscce"
    packages { base: "platform" }
    imports [ base.Task ]
    provides [ main ] to base

main : Task.Task {} *
main =
    loop

loop : Task.Task {} *
loop =
    Task.await loop
```

The backtrace is:

```
thread '<unnamed>' panicked at 'no entry found for key', compiler/can/src/def.rs:593:39
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1292:5
   3: core::option::Option<T>::expect
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:349:21
   4: <std::collections::hash::map::HashMap<K,V,S> as core::ops::index::Index<&Q>>::index
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/collections/hash/map.rs:1116:9
   5: roc_can::def::sort_can_defs::{{closure}}
             at ./compiler/can/src/def.rs:593:39
   6: ven_graph::topological_sort_into_groups
             at ./vendor/pathfinding/src/lib.rs:197:40
   7: roc_can::def::sort_can_defs
             at ./compiler/can/src/def.rs:603:19
   8: roc_can::module::canonicalize_module_defs
             at ./compiler/can/src/module.rs:187:11
   9: roc_load::file::canonicalize_and_constrain
             at ./compiler/load/src/file.rs:3559:25
  10: roc_load::file::run_task
             at ./compiler/load/src/file.rs:4036:14
  11: roc_load::file::load::{{closure}}::{{closure}}
             at ./compiler/load/src/file.rs:1376:54
```

**Comment by rtfeldman** [comment]
Fixed now! The error is:

```
── TOO FEW ARGS ────────────────────────────────────── examples/helloWorld.roc ─

The await function expects 2 arguments, but it got only 1:

12│      Task.await loop 
         ^^^^^^^^^^

Roc does not allow functions to be partially applied. Use a closure to
make partial application explicit.


── TYPE MISMATCH ───────────────────────────────────── examples/helloWorld.roc ─

Something is off with the body of the main definition:

6│  main : Task.Task {} *
7│  main =
8│      loop
        ^^^^

The type annotation on main says this loop value should have the type:

    Task {} *

However, the type of this loop value is connected to another type in a
way that isn't reflected in this annotation.

Tip: Any connection between types must use a named type variable, not
a *! Maybe the annotation  on main should have a named type variable
in place of the *?

────────────────────────────────────────────────────────────────────────────────
```
