### ISSUE TITLE
Race condition with Effect module generation

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#1182]
It rarely happens, but it did on [this build](https://github.com/rtfeldman/roc/pull/1180/checks?check_run_id=2317697146):

```
---- cli_run::base64 stdout ----
thread 'cli_run::base64' panicked at 'Unrecognized non-builtin function: "Effect_always_1"

Symbol: `12.IdentId(5)`
Layout: FunctionPointer([Union(NonRecursive([[Builtin(Int64), Union(NonRecursive([]))], [Builtin(Int64), Struct([])]]))], Closure([Struct([])], ClosureLayout { captured: [(Closure(`12.IdentId(16)`), [Builtin(Int64), Closure([Struct([])], ClosureLayout { captured: [], layout: Struct([Builtin(Str)]) }, Struct([])), FunctionPointer([Struct([])], Union(NonRecursive([[Builtin(Int64), Union(NonRecursive([]))], [Builtin(Int64), Struct([])]])))]), (Closure(`12.IdentId(18)`), [Builtin(Int64), Union(NonRecursive([[Builtin(Int64), Union(NonRecursive([]))], [Builtin(Int64), Struct([])]]))])], layout: Union(NonRecursive([[Builtin(Int64), Closure([Struct([])], ClosureLayout { captured: [], layout: Struct([Builtin(Str)]) }, Struct([])), FunctionPointer([Struct([])], Union(NonRecursive([[Builtin(Int64), Union(NonRecursive([]))], [Builtin(Int64), Struct([])]])))], [Builtin(Int64), Union(NonRecursive([[Builtin(Int64), Union(NonRecursive([]))], [Builtin(Int64), Struct([])]]))]])) }, Union(NonRecursive([[Builtin(Int64), Union(NonRecursive([]))], [Builtin(Int64), Struct([])]]))))

Is the function defined? If so, maybe there is a problem with the layout
thread 'main' panicked at 'Unrecognized non-builtin function: "Effect_always_1" (symbol: `12.IdentId(5)`)', compiler/gen/src/llvm/build.rs:3508:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:435:5
   2: roc_gen::llvm::build::function_value_by_name::{{closure}}
   3: roc_gen::llvm::build::function_value_by_name
   4: roc_gen::llvm::build::build_exp_call
   5: roc_gen::llvm::build::build_exp_expr
   6: roc_gen::llvm::build::build_exp_stmt
   7: roc_gen::llvm::build::build_proc
   8: roc_build::program::gen_from_mono_module
   9: roc_cli::build::build_file
  10: roc_cli::build
  11: roc::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
', cli/tests/cli_run.rs:57:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:435:5
   2: cli_run::cli_run::check_output_with_stdin
   3: core::ops::function::FnOnce::call_once
   4: serial_test::serial_core
   5: core::ops::function::FnOnce::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    cli_run::base64

test result: FAILED. 16 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 20.38s

error: test failed, to rerun pass '-p roc_cli --test cli_run'
```

**Comment by ayazhafiz** [comment]
Closing as this hasn't been observed in a while and most loading bugs due to specialization have been winked away over the last year
