### ISSUE TITLE
editor: render_format GPU issue on PopOS / AMD mobile system

### ISSUE THREAD

**Issue by jthegedus** [roc-lang/roc#2015]
I got this error when building the editor on PopOS 21.04 system:

```
➜ uname -a
Linux art 5.13.0-7620-generic #20~1634827117~21.04~874b071-Ubuntu SMP Fri Oct 29 15:06:55 UTC  x86_64 x86_64 x86_64 GNU/Linux

➜ npx envinfo --system

  System:
    OS: Linux 5.13 Pop!_OS 21.04
    CPU: (8) x64 AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx
    Memory: 2.78 GB / 15.26 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh

➜ RUST_BACKTRACE=1 cargo run edit
    Blocking waiting for file lock on build directory
   Compiling roc_editor v0.1.0 (/home/jthegedus/projects/roc/editor)
   Compiling roc_cli v0.1.0 (/home/jthegedus/projects/roc/cli)
    Finished dev [unoptimized + debuginfo] target(s) in 43.34s
     Running `target/debug/roc edit`
thread 'main' panicked at 'Error in Surface::configure: requested format Bgra8Unorm is not in list of supported formats: [Rgba8UnormSrgb, Bgra8UnormSrgb]', /home/jthegedus/.asdf/installs/rust/1.56.1/registry/src/github.com-1ecc6299db9ec823/wgpu-0.11.0/src/backend/direct.rs:204:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: std::panicking::begin_panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:460:5
   2: wgpu::backend::direct::Context::handle_error_fatal
             at /home/jthegedus/.asdf/installs/rust/1.56.1/registry/src/github.com-1ecc6299db9ec823/wgpu-0.11.0/src/backend/direct.rs:204:9
   3: <wgpu::backend::direct::Context as wgpu::Context>::surface_configure
             at /home/jthegedus/.asdf/installs/rust/1.56.1/registry/src/github.com-1ecc6299db9ec823/wgpu-0.11.0/src/backend/direct.rs:910:13
   4: wgpu::Surface::configure
             at /home/jthegedus/.asdf/installs/rust/1.56.1/registry/src/github.com-1ecc6299db9ec823/wgpu-0.11.0/src/lib.rs:3184:9
   5: roc_editor::editor::main::run_event_loop
             at ./editor/src/editor/main.rs:117:5
   6: roc_editor::editor::main::launch
             at ./editor/src/editor/main.rs:53:5
   7: roc_editor::launch
             at ./editor/src/lib.rs:19:5
   8: roc::launch_editor
             at ./cli/src/main.rs:179:5
   9: roc::main
             at ./cli/src/main.rs:86:21
  10: core::ops::function::FnOnce::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Replacing with one of the values in the "supported formats" list got it working for me:

```diff
    // Prepare swap chain
-    let render_format = wgpu::TextureFormat::Bgra8Unorm;
+    let render_format = wgpu::TextureFormat::Rgba8UnormSrgb;
    let mut size = window.inner_size();
```

https://github.com/rtfeldman/roc/blob/5b19337089a8f6f9dbcb51a282802f89496528d8/editor/src/editor/main.rs#L106

Unfortunately I do now know Rust or GPU libs well enough to contribute the correct cross-platform fix for this.

**Comment by skyqrose** [comment]
Editor is no longer being worked on, and has been removed from the repo. Closing.
