### ISSUE TITLE
Confusing panics when accessing nonexistent record fields

### ISSUE THREAD

**Issue by JanCVanB** [roc-lang/roc#2204]
Strangely, it's a different panic depending on whether the record was created within a `when` block or not.

Module A:
```coffeescript
#!/usr/bin/env roc

app "example"
    packages { base: "roc/examples/cli/platform" }
    imports [ base.Stdout, base.Task.{ await } ]
    provides [ main ] to base

main = 
    # This extra Stdout.line call is required. See GH issue #2151.
    _ <- await (Stdout.line "")
    x = { dogSays: "bark" }
    Stdout.line x.catSays
```

Output A:
```
[nix-shell:~/code/advent-of-code-2021]$ ./roc/target/release/roc example.roc 
thread '<unnamed>' panicked at 'internal error: entered unreachable code: something weird ended up in a record type: Error', compiler/types/src/types.rs:1736:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
^C

[nix-shell:~/code/advent-of-code-2021]$ 
```

Module B:
```coffeescript
#!/usr/bin/env roc

app "example"
    packages { base: "roc/examples/cli/platform" }
    imports [ base.Stdout, base.Task.{ await } ]
    provides [ main ] to base

main = 
    # This extra Stdout.line call is required. See GH issue #2151.
    _ <- await (Stdout.line "")
    x = 
        when 2 + 2 is
            4 -> { dogSays: "bark" }
            _ -> { dogSays: "growl" }
    Stdout.line x.catSays
```

Output B:
```
[nix-shell:~/code/advent-of-code-2021]$ ./roc/target/release/roc example.roc 
thread '<unnamed>' panicked at 'TODO turn fn_var into a RuntimeError Erroneous', compiler/mono/src/ir.rs:3580:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
^C

[nix-shell:~/code/advent-of-code-2021]$ 
```

To the compiler's credit, `roc check` works well on these, with identical+helpful output:
```
[nix-shell:~/code/advent-of-code-2021]$ ./roc/target/release/roc check example.roc 

── TYPE MISMATCH ───────────────────────────────────────────────────────────────

This expression is used in an unexpected way:

12│      Stdout.line x.catSays
                     ^^^^^^^^^

This x value is a:

    { dogSays : Str }

But you are trying to use it as:

    { catSays : a }b

Tip: Seems like a record field typo. Maybe catSays should be dogSays?

Tip: Can more type annotations be added? Type annotations always help
me give more specific messages, and I think they could help a lot in
this case

────────────────────────────────────────────────────────────────────────────────


[nix-shell:~/code/advent-of-code-2021]$ 
```

**Comment by ayazhafiz** [comment]
The first case seems to do much better these days. Only "Module B" is still a problem.

**Comment by JanCVanB** [comment]
TODO: Simplify examples to remove #2151-related bloat.
TODO: Test examples against `trunk`

**Comment by JanCVanB** [comment]
Nevermind about those TODOs, `roc repl` shows that the core logic in both of the above example apps seems to work just fine now. Hooray for automatic type checking!
