### ISSUE TITLE
Cannot declare `Dict` literal

### ISSUE THREAD

**Issue by JanCVanB** [roc-lang/roc#2318]
I'm trying to declare [this literal from the Elm tutorial](https://github.com/rtfeldman/roc/blob/trunk/roc-for-elm-programmers.md?plain=1#L826), but I get a "not yet implemented" panic:
```
[nix-shell:~/code/Strify]$ ./roc/target/release/roc repl

  The rockin’ roc repl
────────────────────────

Enter an expression, or :help, or :exit/:q.

» {::}
thread 'main' panicked at 'not yet implemented: unhandled parse error: Record(End(3:5), 3:4)', reporting/src/error/parse.rs:521:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

[nix-shell:~/code/Strify]$ 
```

This happens with non-empty `Dict` literals as well, as per [this nonempty example](https://github.com/rtfeldman/roc/blob/226237d1cdea5cdae6c8e0e869f16bfbddb5dcfe/roc-for-elm-programmers.md?plain=1#L804):
```
[nix-shell:~/code/Strify]$ ./roc/target/release/roc repl

  The rockin’ roc repl
────────────────────────

Enter an expression, or :help, or :exit/:q.

» {: "Sam" => True, "Ali" => False, firstName => False :}
thread 'main' panicked at 'not yet implemented: unhandled parse error: Record(End(3:5), 3:4)', reporting/src/error/parse.rs:521:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

[nix-shell:~/code/Strify]$ 
```

**Comment by JanCVanB** [comment]
This syntax seems to be obsolete: https://github.com/roc-lang/roc/commit/737acd2acea1843970f972f984520700929f73db
