### ISSUE TITLE
REPL crashes on newline after `=`

### ISSUE THREAD

**Issue by JanCVanB** [roc-lang/roc#3595]
This is very inconvenient, as it prevents testing snippets like this:
```
x = 
    y = 2
    y + 3
```

```
[jan@framey roc]$ export RUST_BACKTRACE=full
[jan@framey roc]$ cargo run repl
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running `target/debug/roc repl`

  The rockin’ roc repl
────────────────────────

Enter an expression, or :help, or :exit/:q.

» x =
thread 'main' panicked at 'not yet implemented: unhandled parse error: IndentEnd(@69)', crates/reporting/src/error/parse.rs:532:14
stack backtrace:
   0:     0x562f19908c2d - std::backtrace_rs::backtrace::libunwind::trace::h22893a5306c091b4
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x562f19908c2d - std::backtrace_rs::backtrace::trace_unsynchronized::h29c3bc6f9e91819d
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x562f19908c2d - std::sys_common::backtrace::_print_fmt::he497d8a0ec903793
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x562f19908c2d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9c2a9d2774d81873
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x562f19930dcc - core::fmt::write::hba4337c43d992f49
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/fmt/mod.rs:1194:17
   5:     0x562f199038d1 - std::io::Write::write_fmt::heb73de6e02cfabed
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/io/mod.rs:1655:15
   6:     0x562f1990a8d5 - std::sys_common::backtrace::_print::h63c8b24acdd8e8ce
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x562f1990a8d5 - std::sys_common::backtrace::print::h426700d6240cdcc2
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x562f1990a8d5 - std::panicking::default_hook::{{closure}}::hc9a76eed0b18f82b
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:295:22
   9:     0x562f1990a589 - std::panicking::default_hook::h2e88d02087fae196
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:314:9
  10:     0x562f1990ae22 - std::panicking::rust_panic_with_hook::habfdcc2e90f9fd4c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:698:17
  11:     0x562f1990ad07 - std::panicking::begin_panic_handler::{{closure}}::he054b2a83a51d2cd
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:588:13
  12:     0x562f199090e4 - std::sys_common::backtrace::__rust_end_short_backtrace::ha48b94ab49b30915
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x562f1990aa39 - rust_begin_unwind
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
  14:     0x562f14ff6fe3 - core::panicking::panic_fmt::h366d3a309ae17c94
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
  15:     0x562f16acc562 - roc_reporting::error::parse::to_expr_report::h3b89d5caeb58de74
                               at /home/jan/_code/_roc/roc-random/roc/crates/reporting/src/error/parse.rs:532:14
  16:     0x562f16acafc6 - roc_reporting::error::parse::to_syntax_report::hf3337d5665add9fe
                               at /home/jan/_code/_roc/roc-random/roc/crates/reporting/src/error/parse.rs:135:30
  17:     0x562f16aca312 - roc_reporting::error::parse::parse_problem::h896f67f165a915ec
                               at /home/jan/_code/_roc/roc-random/roc/crates/reporting/src/error/parse.rs:15:5
  18:     0x562f16a0cfe5 - roc_load_internal::file::to_parse_problem_report::h94d44572a5ce8d6d
                               at /home/jan/_code/_roc/roc-random/roc/crates/compiler/load_internal/src/file.rs:5376:18
  19:     0x562f169dfb79 - roc_load_internal::file::state_thread_step::he97cb8affc863d0c
                               at /home/jan/_code/_roc/roc-random/roc/crates/compiler/load_internal/src/file.rs:1561:31
  20:     0x562f169de51d - roc_load_internal::file::load_single_threaded::hcaa84a32ab66795c
                               at /home/jan/_code/_roc/roc-random/roc/crates/compiler/load_internal/src/file.rs:1470:15
  21:     0x562f169dd6d1 - roc_load_internal::file::load::h41e51df6597444ba
                               at /home/jan/_code/_roc/roc-random/roc/crates/compiler/load_internal/src/file.rs:1396:28
  22:     0x562f16911c6b - roc_load::load::h5cfcc0850f362f90
                               at /home/jan/_code/_roc/roc-random/roc/crates/compiler/load/src/lib.rs:29:5
  23:     0x562f16911f38 - roc_load::load_and_monomorphize_from_str::h913da67455150bc1
                               at /home/jan/_code/_roc/roc-random/roc/crates/compiler/load/src/lib.rs:78:11
  24:     0x562f1650938c - roc_repl_eval::gen::compile_to_mono::h87255dfa96f4ea63
                               at /home/jan/_code/_roc/roc-random/roc/crates/repl_eval/src/gen.rs:57:18
  25:     0x562f164cd66c - roc_repl_cli::gen_and_eval_llvm::h384666bbaab1c63b
                               at /home/jan/_code/_roc/roc-random/roc/crates/repl_cli/src/lib.rs:368:28
  26:     0x562f164ce04e - roc_repl_cli::eval_and_format::hec4edd28b4a0045c
                               at /home/jan/_code/_roc/roc-random/roc/crates/repl_cli/src/lib.rs:430:5
  27:     0x562f164ceb26 - roc_repl_cli::main::hb5a1b3d68bdd72dd
                               at /home/jan/_code/_roc/roc-random/roc/crates/repl_cli/src/lib.rs:499:29
  28:     0x562f150c3abb - roc::main::h423c1fb84af910cd
                               at /home/jan/_code/_roc/roc-random/roc/crates/cli/src/main.rs:147:17
  29:     0x562f150c25cb - core::ops::function::FnOnce::call_once::h7c77ac6a58d31fd4
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
  30:     0x562f150c1ace - std::sys_common::backtrace::__rust_begin_short_backtrace::h996f56a0f696e8be
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:122:18
  31:     0x562f150c1c21 - std::rt::lang_start::{{closure}}::h60650cadf439ea7a
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:145:18
  32:     0x562f198fba8e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::had4f69b3aefb47a8
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:259:13
  33:     0x562f198fba8e - std::panicking::try::do_call::hf2ad5355fcafe775
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  34:     0x562f198fba8e - std::panicking::try::h0a63ac363423e61e
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  35:     0x562f198fba8e - std::panic::catch_unwind::h18088edcecb8693a
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  36:     0x562f198fba8e - std::rt::lang_start_internal::{{closure}}::ha7dad166dc711761
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:48
  37:     0x562f198fba8e - std::panicking::try::do_call::hda0c61bf3a57d6e6
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  38:     0x562f198fba8e - std::panicking::try::hbc940e68560040a9
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  39:     0x562f198fba8e - std::panic::catch_unwind::haed0df2aeb3fa368
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  40:     0x562f198fba8e - std::rt::lang_start_internal::h9c06694362b5b80c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:20
  41:     0x562f150c1bf0 - std::rt::lang_start::hc2eba1e5550ccad0
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:144:17
  42:     0x562f150c630c - main
  43:     0x7f4fcc31e237 - __libc_start_call_main
  44:     0x7f4fcc31e2f5 - __libc_start_main_impl
  45:     0x562f150bfcf1 - _start
                               at /build/glibc-2.34/csu/../sysdeps/x86_64/start.S:116
  46:                0x0 - <unknown>
[jan@framey roc]$ 
```

**Comment by Ivo-Balbaert** [comment]
Allthough there are still many usability issues with the repl, it seems this is solved. When entering something like x = , the continuation ... appears:

» x =
…

So this issue seems solved. @Anton-4?

**Comment by lukewilliamboswell** [comment]
Concur this is resolved. You can also copy-paste the snippet in and it works as expected. 

```
» x = 
…     y = 2
…     y + 3

5 : Num *                    # x
```
