### ISSUE TITLE
Improve messaging for missing platform dependencies

### ISSUE THREAD

**Issue by JanCVanB** [roc-lang/roc#3631]
I don't have clang or Rust or Zig installed in my operating system, so I got the following panic when running an app outside of `nix develop`:
```sh-session
[jan@framey roc]$ nix develop
[jan@framey roc]$ 
[jan@framey roc]$ ./target/release/roc ../project-euler-in-roc/2.roc
🔨 Rebuilding host...
4613732
[jan@framey roc]$
[jan@framey roc]$ exit
exit
[jan@framey roc]$
[jan@framey roc]$ cd ../project-euler-in-roc/
[jan@framey project-euler-in-roc]$
[jan@framey project-euler-in-roc]$ ../roc/target/release/roc 2.roc
🔨 Rebuilding host...
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', crates/compiler/build/src/link.rs:360:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', crates/cli/src/build.rs:283:46
[jan@framey project-euler-in-roc]$
[jan@framey project-euler-in-roc]$ ../roc/target/release/roc 2.roc --precompiled-host=true
4613732
[jan@framey project-euler-in-roc]$
```

**Comment by Anton-4** [comment]
Similarly, the error thrown [here](https://github.com/roc-lang/roc/blob/52f0dfbaf424584019599c981bd09bbcb53136ac/crates/compiler/build/src/link.rs#L626) should say something like: "Do you have cargo installed? Go to https://rustup.rs/ to install cargo."
