### ISSUE TITLE
Roc examples crash with: "thread 'main' panicked at 'wasm-stack-size-kb'"

### ISSUE THREAD

**Issue by imclerran** [roc-lang/roc#3852]
When trying to run any of the Roc Lang examples on ubuntu 21.10, the example code crashes with the following error message:

```
ian@UBU:~/Documents/repos/roc$ cargo run ./examples/hello-world/main.roc
    Finished dev [unoptimized + debuginfo] target(s) in 0.44s
     Running `target/debug/roc ./examples/hello-world/main.roc`
thread 'main' panicked at '`wasm-stack-size-kb` is not an id of an argument or a group.
Make sure you're using the name of the argument itself and not the name of short or long flags.', crates/cli/src/lib.rs:528:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: clap::parser::matches::arg_matches::ArgMatches::get_arg
             at /home/ian/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.2.11/src/parser/matches/arg_matches.rs:1273:17
   3: clap::parser::matches::arg_matches::ArgMatches::value_of
             at /home/ian/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.2.11/src/parser/matches/arg_matches.rs:352:19
   4: roc_cli::build
             at ./crates/cli/src/lib.rs:527:45
   5: roc::main
             at ./crates/cli/src/main.rs:32:17
   6: core::ops::function::FnOnce::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by imclerran** [comment]
Issue already resolved in latest versions -- oops!
