### ISSUE TITLE
Record `&` syntax fails to compile

### ISSUE THREAD

**Issue by imclerran** [roc-lang/roc#3908]
I am walking through the Roc tutorial, and at the point of [building records from other records](https://github.com/roc-lang/roc/blob/104ec255d766314f367b4e79a9b8c98c4a9e4b22/TUTORIAL.md?plain=1#L404-L407) using the `&` operator.

My full code is as follows:
```coffee
app "hello"
    packages { pf: "examples/interactive/cli-platform/main.roc" }
    imports [pf.Stdout]
    provides [main] to pf

main = Stdout.line "There are \(total) animals."

total = addAndStringify fromOriginal

addAndStringify = \{ birds, iguanas: lizards } ->
    Num.toStr (birds + lizards)

original = { birds: 5, iguanas: 7, zebras: 2, goats: 1 }

fromOriginal = { original & birds: 4, iguanas: 3 }
```

The error message produced is as follows:
```
ian@UBU ~/Documents/repos/roc (main) $ roc run Hello.roc 
    Finished dev [unoptimized + debuginfo] target(s) in 0.30s
     Running `target/debug/roc Hello.roc`
Symbol `#UserApp.original` #UserApp.3 has no info in self.vars
Symbol `#UserApp.original` #UserApp.3 has no info in self.vars
Symbol `#UserApp.original` #UserApp.3 has no info in self.vars
Symbol `#UserApp.original` #UserApp.3 has no info in self.vars
🔨 Rebuilding host...
thread 'main' panicked at 'no entry found for key', crates/compiler/alias_analysis/src/lib.rs:1306:28
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_display
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/option.rs:1874:5
   5: core::option::Option<T>::expect
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/option.rs:718:21
   6: <std::collections::hash::map::HashMap<K,V,S> as core::ops::index::Index<&Q>>::index
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/collections/hash/map.rs:1175:9
   7: roc_alias_analysis::expr_spec
             at ./crates/compiler/alias_analysis/src/lib.rs:1306:28
   8: roc_alias_analysis::stmt_spec
             at ./crates/compiler/alias_analysis/src/lib.rs:422:28
   9: roc_alias_analysis::proc_spec
             at ./crates/compiler/alias_analysis/src/lib.rs:389:20
  10: roc_alias_analysis::spec_program
             at ./crates/compiler/alias_analysis/src/lib.rs:217:38
  11: roc_gen_llvm::llvm::build::build_procedures_help
             at ./crates/compiler/gen_llvm/src/llvm/build.rs:4398:27
  12: roc_gen_llvm::llvm::build::build_procedures
             at ./crates/compiler/gen_llvm/src/llvm/build.rs:4274:5
  13: roc_build::program::gen_from_mono_module_llvm
             at ./crates/compiler/build/src/program.rs:281:5
  14: roc_build::program::gen_from_mono_module
             at ./crates/compiler/build/src/program.rs:172:67
  15: roc_cli::build::build_file
             at ./crates/cli/src/build.rs:275:27
  16: roc_cli::build
             at ./crates/cli/src/lib.rs:532:27
  17: roc::main
             at ./crates/cli/src/main.rs:35:17
  18: core::ops::function::FnOnce::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Commenting out the def for fromOriginal, and changing addAndStringify to take original as an argument instead compiles and runs normally:

```coffee
app "hello"
    packages { pf: "examples/interactive/cli-platform/main.roc" }
    imports [pf.Stdout]
    provides [main] to pf

main = Stdout.line "There are \(total) animals."

total = addAndStringify original

addAndStringify = \{ birds, iguanas: lizards } ->
    Num.toStr (birds + lizards)

original = { birds: 5, iguanas: 7, zebras: 2, goats: 1 }

# fromOriginal = { original & birds: 4, iguanas: 3 }
```

NOTE: I am on commit 104ec25 - latest from main at time of writing

**Comment by ayazhafiz** [comment]
Nice find. We have some kind of problem with thunks. For example, this happily compiles:

```
app "hello"
    packages { pf: "examples/interactive/cli-platform/main.roc" }
    imports [pf.Stdout]
    provides [main] to pf

main =
    total = addAndStringify fromOriginal

    addAndStringify = \{ birds, iguanas: lizards } ->
        Num.toStr (birds + lizards)

    original = { birds: 5, iguanas: 7, zebras: 2, goats: 1 }

    fromOriginal = { original & birds: 4, iguanas: 3 }

    Stdout.line "There are \(total) animals."
```
