### ISSUE TITLE
REPL broken on Fedora Linux

### ISSUE THREAD

**Issue by JanCVanB** [roc-lang/roc#4011]
This is about a week old, as it happens with either the Sept 5th nightly build & the September 10th nightly build.
```
[jan@framey ~]$ ls .local/bin
crates         lib      roc_nightly-linux_x86_64-2022-09-10-90923c5.tar.gz
examples       LICENSE  zig-linux-x86_64-0.9.1
LEGAL_DETAILS  roc      zig-linux-x86_64-0.9.1.tar.xz
[jan@framey ~]$ which roc
~/.local/bin/roc
[jan@framey ~]$ roc _code/_roc/roc/examples/hello-world/main.roc
roc: /lib64/libtinfo.so.6: no version information available (required by roc)
🔨 Rebuilding host...
Hello, World!
[jan@framey ~]$ roc repl
roc: /lib64/libtinfo.so.6: no version information available (required by roc)

  The rockin’ roc repl
────────────────────────

Enter an expression, or :help, or :q to quit.

» 123
ld: /usr/lib/libgcc_s.so.1: error adding symbols: file in wrong format
thread 'main' panicked at 'we produce a valid Dylib: DlOpen { desc: "/tmp/.tmpH4oBgE/app.so.1.0: cannot open shared object file: No such file or directory" }', crates/repl_cli/src/lib.rs:353:65
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[jan@framey ~]$ 
```

**Comment by brian-carroll** [comment]
I was about to look into fixing this but... it sounds like it's already fixed?
What is the goal of this issue?

**Comment by JanCVanB** [comment]
Sorry if my firstcomment was unclear, but when I created this issue it was still happening, from Sept 5 to present.

**Comment by brian-carroll** [comment]
Ah OK I'll try on Linux when I have a chance. Not seeing it on Mac.

**Comment by Anton-4** [comment]
This error did not reproduce on Ubuntu 20.04, I'll check fedora next.

**Comment by Anton-4** [comment]
On fedora I see the `roc: /lib64/libtinfo.so.6: no version information available (required by roc)`, but no errors when using the repl.

**Comment by JanCVanB** [comment]
Hmmm, I still have this issue:
```sh
[jan@framey ~]$ neofetch
             .',;::::;,'.                jan@framey 
         .';:cccccccccccc:;,.            ---------- 
      .;cccccccccccccccccccccc;.         OS: Fedora Linux 36 (Workstation Edition) x86_ 
    .:cccccccccccccccccccccccccc:.       Host: Laptop AA 
  .;ccccccccccccc;.:dddl:.;ccccccc;.     Kernel: 5.19.8-200.fc36.x86_64 
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    Uptime: 18 mins 
.:ccccccccccccc;KMMc;cc;xMMc:ccccccc:.   Packages: 2150 (rpm), 42 (nix-default), 21 (fl 
,cccccccccccccc;MMM.;cc;;WW::cccccccc,   Shell: bash 5.1.16 
:cccccccccccccc;MMM.;cccccccccccccccc:   Resolution: 2256x1504 
:ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:   DE: GNOME 42.4 
cccccc:0MMKxdd:;MMMkddc.;cccccccccccc;   WM: Mutter 
ccccc:XM0';cccc;MMM.;cccccccccccccccc'   WM Theme: Adwaita 
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    Theme: Adwaita [GTK2/3] 
ccccc;0MNc.ccc.xMMd:ccccccccccccccc;     Icons: Adwaita [GTK2/3] 
cccccc;dNMWXXXWM0::cccccccccccccc:,      Terminal: kitty 
cccccccc;.:odl:.;cccccccccccccc:,.       CPU: 11th Gen Intel i5-1135G7 (8) @ 4.200GHz 
:cccccccccccccccccccccccccccc:'.         GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics] 
.:cccccccccccccccccccccc:;,..            Memory: 2797MiB / 15781MiB 
  '::cccccccccccccc::;,.
                                                                 
                                                                 


[jan@framey ~]$ roc version
roc: /lib64/libtinfo.so.6: no version information available (required by roc)
roc nightly pre-release, built from commit 6613e9d on Mi 14 Sep 2022 09:12:53 UTC
[jan@framey ~]$ roc repl
roc: /lib64/libtinfo.so.6: no version information available (required by roc)

  The rockin’ roc repl
────────────────────────

Enter an expression, or :help, or :q to quit.

» 123
ld: /usr/lib/libgcc_s.so.1: error adding symbols: file in wrong format
thread 'main' panicked at 'we produce a valid Dylib: DlOpen { desc: "/tmp/.tmpEDby5D/app.so.1.0: cannot open shared object file: No such file or directory" }', crates/repl_cli/src/lib.rs:353:65
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[jan@framey ~]$ 
```

**Comment by JanCVanB** [comment]
Wait... omg I'm so sorry, this is silly. On this machine I use Nix, but I wasn't running `roc repl` inside a `nix develop` shell.

**Comment by JanCVanB** [comment]
Do we see any transparency/reporting action items coming out of this?

**Comment by Anton-4** [comment]
The repl from nightly should always work without using nix :thinking:

**Comment by Anton-4** [comment]
The virtual machine with fedora I tried it on is close to a clean install, I would guess you installed something that changed the default gcc setup.

**Comment by JanCVanB** [comment]
Dang. I don't konw what that might be... should we close this, then?

**Comment by Anton-4** [comment]
Perhaps we should try to fix `/lib64/libtinfo.so.6: no version information available`, there's a chance that could fix your error.

**Comment by Anton-4** [comment]
What does `gcc --version` return for you @JanCVanB?

**Comment by JanCVanB** [comment]
@Anton-4 
```
[jan@framey ~]$ gcc --version
gcc (GCC) 12.2.1 20220819 (Red Hat 12.2.1-1)
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[jan@framey ~]$ 
```

**Comment by Anton-4** [comment]
I have the same version, I'll try to think of next steps.

**Comment by JanCVanB** [comment]
@Anton-4 Update! This original problem seems to be resolved:

## Without Nix

```sh
[jan@framey _roc]$ neofetch
             .',;::::;,'.                jan@framey 
         .';:cccccccccccc:;,.            ---------- 
      .;cccccccccccccccccccccc;.         OS: Fedora release 40 (Forty) x86_64 
    .:cccccccccccccccccccccccccc:.       Host: Laptop AA 
  .;ccccccccccccc;.:dddl:.;ccccccc;.     Kernel: 6.8.8-300.fc40.x86_64 
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    Uptime: 1 hour, 4 mins 
.:ccccccccccccc;KMMc;cc;xMMc:ccccccc:.   Packages: 2769 (rpm), 50 (nix-default), 39 (flatpak) 
,cccccccccccccc;MMM.;cc;;WW::cccccccc,   Shell: bash 5.2.26 
:cccccccccccccc;MMM.;cccccccccccccccc:   Resolution: 2256x1504 
:ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:   DE: GNOME 46.1 
cccccc:0MMKxdd:;MMMkddc.;cccccccccccc;   WM: Mutter 
ccccc:XM0';cccc;MMM.;cccccccccccccccc'   WM Theme: Adwaita 
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    Theme: Adwaita [GTK2/3] 
ccccc;0MNc.ccc.xMMd:ccccccccccccccc;     Icons: Adwaita [GTK2/3] 
cccccc;dNMWXXXWM0::cccccccccccccc:,      Terminal: kitty 
cccccccc;.:odl:.;cccccccccccccc:,.       CPU: 11th Gen Intel i5-1135G7 (8) @ 4.200GHz 
:cccccccccccccccccccccccccccc:'.         GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics] 
.:cccccccccccccccccccccc:;,..            Memory: 4968MiB / 15771MiB 
  '::cccccccccccccc::;,.
                                                                 
                                                                 


[jan@framey _roc]$ gcc --version
gcc (GCC) 14.1.1 20240507 (Red Hat 14.1.1-1)
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[jan@framey _roc]$ which roc
~/_code/_roc/roc-installation/roc_nightly-linux_x86_64-latest/roc
[jan@framey _roc]$ roc repl
roc: /lib64/libtinfo.so.6: no version information available (required by roc)

  The rockin' roc repl
────────────────────────

Enter an expression, or :help, or :q to quit.

» 123

123 : Num *
» 
```

## With Nix

```sh
[jan@framey roc]$ nix develop
[jan@framey roc]$ which roc
~/_code/_roc/roc-installation/roc_nightly-linux_x86_64-latest/roc
[jan@framey roc]$ nix shell
bash: shopt: progcomp: invalid shell option name
bash: complete: command not found...
bash: complete: command not found...
bash: complete: command not found...
bash: complete: command not found...
bash: complete: command not found...
[jan@framey roc]$ which roc
/nix/store/3x0haav15ynswbf5q9ch5lp7v6rq9whk-roc_cli-0.0.1/bin/roc
[jan@framey roc]$ roc repl

  The rockin' roc repl
────────────────────────

Enter an expression, or :help, or :q to quit.

» 123

123 : Num *
» 
```

## Weirdness

I was going to ask if we can figure out why `roc: /lib64/libtinfo.so.6: no version information available (required by roc)` still appears as the first output of every `roc foo` command... but after running the above `nix` commands it no longers appears! Outside of Nix shell! What the heck?

**Comment by Anton-4** [comment]
strange indeed but nice to see the original issue resolved :)

**Comment by giganteous** [comment]
This still is a problem on fedora42:

```
 ❯ roc version
roc: /lib64/libtinfo.so.6: no version information available (required by roc)
roc nightly pre-release, built from commit c47a8e9 on Sa 22 Mär 2025 09:02:05 UTC
```

Ldd sees it:
```
…/git/thirdparty/hello ❯ ldd ../roc_nightly-linux_x86_64-2025-03-22-c47a8e9/roc
../roc_nightly-linux_x86_64-2025-03-22-c47a8e9/roc: /lib64/libtinfo.so.6: no version information available (required by ../roc_nightly-linux_x86_64-2025-03-22-c47a8e9/roc)
	linux-vdso.so.1 (0x00007f35cd360000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f35cd340000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f35cd33c000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f35cd338000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f35c8112000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f35cd315000)
	libzstd.so.1 => /lib64/libzstd.so.1 (0x00007f35c804e000)
	libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007f35cd2e6000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f35c7c00000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f35cd2ba000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f35c7a0e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f35cd362000)
```

(gcc is on 15.1.1 by Red Hat).

Other than the warning, the roc command seems to work fine, so the statement that it is required by roc is a bit misleading. Is it environment-related? The "Mär" in Swedish(?) is a bit weird, my locale is `en_US`. Can I help?

**Comment by Anton-4** [comment]
Hi @giganteous :)

> Can I help?

Thanks for the offer! We are hard at work on the new compiler (written in zig), and I expect that this problem will go away with the new compiler. So it's probably not worth the effort to chase this down in the current (old) repl. 

> The "Mär" in Swedish(?) is a bit weird

Yeah, I don't know what's up with the locale on my CI server, I don't live in Sweden :p I'll check it out.
I don't think we should adjust this to the user's locale, because it's nice that the same Roc versions have identical version strings.

**Comment by Anton-4** [comment]
>  I'll check it out.

Ok, releases from now on should have US dates.
