### ISSUE TITLE
`cli_run::args` test failure with surgical linker

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#4037]
Adding the args test in PR #3990 resulted in different kinds of errors that changed between runs (without changing relevant code):
```
thread 'cli_run::args' panicked at 'expected output to end with "hello world\n" but instead got "" - stderr was: "Inconsistency detected by ld.so: dl-version.c: 204: _dl_check_map_versions: Assertion `needed != NULL' failed!\n"', crates/cli/tests/cli_run.rs:216:17
```
```
thread 'cli_run::args' panicked at 'expected output to end with "hello world\n" but instead got "" - stderr was: "/home/big-ci-user/actions-runner/_work/roc/roc/examples/interactive/args: error while loading shared libraries: .25: cannot open shared object file: No such file or directory\n"', crates/cli/tests/cli_run.rs:216:17
```
Also a failure without errors:
```
thread 'cli_run::args' panicked at 'expected output to end with "hello world\n" but instead got "" - stderr was: ""', crates/cli/tests/cli_run.rs:216:17
```
In the attached archive there are two binaries, both were created on the same machine inside nix.
When going through github actions the created binary(args_error_loading_shared_libs_25) usually errors but the error often differs between runs.
When manually creating the binary(args_good_big_ci_manual) on the same machine it never errors.

The args_error one is missing the expected `Dynamic Section:` and `Version References:`, I checked this with `objdump -p`.
The `args_good` binary does have the expected sections.

`objdump -d` on `args_error` prints `objdump: warning: args_error_loading_shared_libs_25 has a corrupt string table index - ignoring` and does not print out any assembly.
`args_good` does not print this warning and we get the full disassembly as expected.

There may be a race condition in the surgical linker, using the legacy linker fixed the test.
Running with the surgical linker and single threaded(`-j 1`) `cargo test` did not fix the issue, this command may however not run the surgical linker single threaded.

[args_binaries.tar.gz](https://github.com/roc-lang/roc/files/9568217/args_binaries.tar.gz)

**Comment by Anton-4** [comment]
The args test also passed one time with the surgical linker but then the `cli_run::cli` test failed:
```
failures:

---- cli_run::cli stdout ----
thread 'cli_run::cli' panicked at '`roc` command had unexpected stderr: An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread '<unnamed>' panicked at 'Failed to parse executable file: Could not read file magic', crates/linker/src/lib.rs:479:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: roc_linker::preprocess
   3: roc_linker::build_and_preprocess_host
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', crates/cli/src/build.rs:322:46
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1785:5
   3: roc_cli::build::build_file
   4: roc_cli::build
   5: roc::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
', crates/cli/tests/cli_run.rs:117:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: cli_run::cli_run::run_roc_on
   3: core::ops::function::FnOnce::call_once
   4: core::ops::function::FnOnce::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    cli_run::cli

test result: FAILED. 39 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 446.50s

```

**Comment by Anton-4** [comment]
A promising potential cause: multiple tests that use the same platform are trying to read and write that file at the same time.
