### ISSUE TITLE
`Num.divTrunc` and `Num.divCeil` return 0 instead of panicking

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/roc#4363]
In the repl:
```
» Num.divCeil 7 0

0 : Int *
```

```
» 7 // 0

0 : Int *
```

This contracts there documentation and is surprising behaviour in general.
I think this should be a good first issue, but it may be a bit complex. Not fully sure.

**Comment by lukewilliamboswell** [comment]
@bhansconnect I got part way there with `Num.divCeil` it seems an easy fix. Copied fix below, though I am not sure if that is the right style, I've never touched Zig before.

Also, I noticed something that looked strange on *Line 395 in crates/compiler/builtins/bitcode/src/num.zig* it looks like we are comparing the numerator, not sure if this is right? 

For `7 // 0` I tried various things but still can't figure out why it isn't working. I feel like it may be something to do with 0 being interpreted as a float or something similar? I wish I could have gotten further here. 

```zig
pub fn exportDivCeil(comptime T: type, comptime name: []const u8) void {
    comptime var f = struct {
        fn func(a: T, b: T) callconv(.C) T {
            if (b == 0) {
                roc_panic("Runtime exception for dividing by 0!", 1);
                unreachable;
            } else {
                return math.divCeil(T, a, b) catch @panic("unreachable");
            }
        }
    }.func;
    @export(f, .{ .name = name ++ @typeName(T), .linkage = .Strong });
}
```

**Comment by basile-henry** [comment]
This example now seems to break the web REPL. After writing `Num.divCeil 7 0` we don't get an answer and we can't input anything else in the REPL. The browser console shows the following error:

```
Uncaught (in promise) RuntimeError: divide by zero
    at roc_builtins.num.div_ceil.i64 (000d1a72:0xb96)
    at replOutput (000d1a72:0x1bee)
    at 000d1a72:0x1c23
    at js_run_app (repl.js:224:26)
    at <roc_repl_wasm::repl::WasmReplApp as roc_repl_eval::ReplApp>::call_function::h5785dada8159d500 (roc_repl_wasm_bg.wasm:0x3c58c1)
    at roc_repl_wasm::repl::eval_wasm::{{closure}}::had0cb47aea0fdeb2 (roc_repl_wasm_bg.wasm:0x90e99)
    at wasm_bindgen_futures::future_to_promise::{{closure}}::{{closure}}::ha8d95284e390528f (roc_repl_wasm_bg.wasm:0x27fe56)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h53e50a293a7d9b98 (roc_repl_wasm_bg.wasm:0x36fe86)
    at wasm_bindgen::convert::closures::invoke1_mut::h7dcdcbc0922500bc (roc_repl_wasm_bg.wasm:0x3f3991)
    at __wbg_adapter_12 (roc_repl_wasm.js:205:10)
```

**Comment by JRI98** [comment]
No longer reproduces.

Current output:
```
This Roc code crashed with: "Integer division by 0!"

* : Int *
```
