### ISSUE TITLE
REPL crash on builtins call

### ISSUE THREAD

**Issue by ghigt** [roc-lang/roc#4461]
Using the REPL for documentation about a builtin function call is very useful and also the only way for some builtins to have the real definition (the website is sometimes missing parenthesis or function parameters)
But, on several, they crash if we call them on there definition call (using them normally seems to work fine).

```
» Decode.fromBytesPartial
thread 'main' panicked at 'unspecialized lambda sets left over during resolution: LambdaSet([] + (<1225>FlexAble(a, [`List.isEmpty`, `Decode.Decoding`]):`Decode.decoder`:1), ^<1230>), UlsOfVar(VecMap { keys: [1225], values: [VecSet { elements: [1227] }] })', crates/compiler/mono/src/layout.rs:1860:17

» Decode.fromBytes
thread 'main' panicked at 'unspecialized lambda sets left over during resolution: LambdaSet([] + (<1225>FlexAble(a, [`List.isEmpty`, `Decode.Decoding`]):`Decode.decoder`:1), ^<1230>), UlsOfVar(VecMap { keys: [1225], values: [VecSet { elements: [1227] }] })', crates/compiler/mono/src/layout.rs:1860:17

» Dict.get
thread 'main' panicked at 'assertion failed: unspecialized.is_empty()', crates/compiler/mono/src/ir.rs:5600:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

» Dict.insert
thread 'main' panicked at 'assertion failed: unspecialized.is_empty()', crates/compiler/mono/src/ir.rs:5600:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

» Dict.remove
thread 'main' panicked at 'assertion failed: unspecialized.is_empty()', crates/compiler/mono/src/ir.rs:5600:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

» Dict.update
thread 'main' panicked at 'assertion failed: unspecialized.is_empty()', crates/compiler/mono/src/ir.rs:5600:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

» Dict.contains
thread 'main' panicked at 'assertion failed: unspecialized.is_empty()', crates/compiler/mono/src/ir.rs:5600:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

» Dict.insertAll
thread 'main' panicked at 'assertion failed: unspecialized.is_empty()', crates/compiler/mono/src/ir.rs:5600:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

» Dict.keepShared
thread 'main' panicked at 'assertion failed: unspecialized.is_empty()', crates/compiler/mono/src/ir.rs:5600:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

» Dict.removeAll
thread 'main' panicked at 'assertion failed: unspecialized.is_empty()', crates/compiler/mono/src/ir.rs:5600:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

» Encode.append
thread 'main' panicked at 'unspecialized lambda sets left over during resolution: LambdaSet([] + (<937>FlexAble(a, [`Encode.Encoding`, `Bool.boolIsEq`]):`Encode.toEncoder`:2), ^<940>), UlsOfVar(VecMap { keys: [937, 981], values: [VecSet { elements: [936, 939] }, VecSet { elements: [980, 983] }] })', crates/compiler/mono/src/layout.rs:1860:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

» Encode.toBytes
thread 'main' panicked at 'unspecialized lambda sets left over during resolution: LambdaSet([] + (<981>FlexAble(a, [`Encode.Encoding`, `Bool.boolIsEq`]):`Encode.toEncoder`:2), ^<984>), UlsOfVar(VecMap { keys: [937, 981], values: [VecSet { elements: [936, 939] }, VecSet { elements: [980, 983] }] })', crates/compiler/mono/src/layout.rs:1860:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

» Hash.hashI8 # and all other .hashIX
thread 'main' panicked at 'assertion failed: unspecialized.is_empty()', crates/compiler/mono/src/ir.rs:5600:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

» List.contains
thread 'main' panicked at 'assertion failed: unspecialized.is_empty()', crates/compiler/mono/src/ir.rs:5600:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

» List.splitFirst
thread 'main' panicked at 'assertion failed: unspecialized.is_empty()', crates/compiler/mono/src/ir.rs:5600:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

» List.splitLast
thread 'main' panicked at 'assertion failed: unspecialized.is_empty()', crates/compiler/mono/src/ir.rs:5600:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

» Set.insert
thread 'main' panicked at 'assertion failed: unspecialized.is_empty()', crates/compiler/mono/src/ir.rs:5600:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

» Set.remove
thread 'main' panicked at 'assertion failed: unspecialized.is_empty()', crates/compiler/mono/src/ir.rs:5600:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

» Set.contains
thread 'main' panicked at 'assertion failed: is_sorted_dedup(right)', /Users/ghigt/code/github/roc/crates/compiler/unify/src/unify.rs:3113:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

» Set.fromList
thread 'main' panicked at 'assertion failed: unspecialized.is_empty()', crates/compiler/mono/src/ir.rs:5600:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

» Set.union
thread 'main' panicked at 'assertion failed: unspecialized.is_empty()', crates/compiler/mono/src/ir.rs:5600:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

» Set.intersection
thread 'main' panicked at 'assertion failed: unspecialized.is_empty()', crates/compiler/mono/src/ir.rs:5600:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

» Set.difference
thread 'main' panicked at 'assertion failed: unspecialized.is_empty()', crates/compiler/mono/src/ir.rs:5600:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by skyqrose** [comment]
This error still happens (though it's a slightly different error now).
```
» Set.union
panicked at crates/compiler/mono/src/ir.rs:6191:56:
called `Option::unwrap()` on a `None` value
```

**Comment by Anton-4** [comment]
> This error still happens

Just a clarification, `assertion failed: unspecialized.is_empty()` is a debug assert, you only get this error by building without `--release` (`cargo build --bin roc`) so the error has not changed.
