### ISSUE TITLE
`cli-platform` panics when reading a file that doesn't exist

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#4479]
The following code panics when trying to read a file that doesn't exist. 

```elixir
app "app-aoc-2021-day-4"
    packages { pf: "cli-platform/main.roc" }
    imports [
        pf.Program.{ Program },
        pf.Stdout,
        pf.Task.{ Task },
        pf.File,
        pf.Path.{ Path },
    ]
    provides [main] to pf

main : Program
main =
    Path.fromStr "i-dont-exist.txt"
    |> File.readUtf8
    |> Task.map Stdout.line
    |> Program.quick
```

```
luke@Lukes-MacBook-Air roc-things % roc run test.roc
🔨 Rebuilding platform...
thread '<unnamed>' panicked at 'not yet implemented: Report a file open error', src/lib.rs:410:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
zsh: abort      roc run test.roc
```

**Comment by lukewilliamboswell** [comment]
Checked this issue, and it is still present. Will raise on `roc/basic-cli` closing here. 

```elixir
app "example"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.1.2/3bKbbmgtIfOyC6FviJ9o8F8xqKutmXgjCJx3bMfVTSo.tar.br" }
    imports [
        pf.Stdout,
        pf.Task.{ Task },
        pf.File,
        pf.Path.{ Path },
    ]
    provides [ main ] to pf

main : Task {} []
main =
    task = 
        _ <- File.readUtf8 (Path.fromStr "i-dont-exist.txt") |> Task.await
        
        Stdout.line ""

    Task.onFail task \_ -> crash "ooops"
```

```sh
luke@192-168-1-108 aoc-2022 % roc dev test.roc
thread '<unnamed>' panicked at 'not yet implemented: Report a file open error', src/lib.rs:421:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```
