### ISSUE TITLE
Compiler bug when trying to compile the first hello world program of the tutorial

### ISSUE THREAD

**Issue by asielorz** [roc-lang/roc#4663]
I am following the roc tutorial with the intention of getting the basics and then doing advent of code in roc this year. However, in the "Building an application" step, I get a panic at the compiler when trying to build the example hello world program. The problem seems to be related to downloading or compiling the platform from the GitHub releases link.

This is the error message I am getting, with the stacktrace:

```
~/Desktop/advent-of-code-2022/day-1-1  roc dev day-1-1.roc

Downloading https://github.com/roc-lang/basic-cli/releases/download/0.1.1/zAoiC9xtQPHywYk350_b7ust04BmWLW00sjb9ZPtSQk.tar.br
    into /home/asier/.cache/roc/packages

thread 'main' panicked at 'not yet implemented: TODO gracefully handle package install error IoErr(Os { code: 18, kind: CrossesDevices, message: "Invalid cross-device link" })', crates/compiler/load_internal/src/file.rs:3859:37
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: roc_load_internal::file::parse_header
   3: roc_load_internal::file::load_filename
   4: roc_load_internal::file::LoadStart::from_path
   5: roc_load::load_and_monomorphize
   6: roc_cli::build::build_file
   7: roc_cli::build
   8: roc::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Just in case, the program I am trying to build is exactly this:

```
app "advent-of-code-1-1"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.1.1/zAoiC9xtQPHywYk350_b7ust04BmWLW00sjb9ZPtSQk.tar.br" }
    imports [pf.Stdout]
    provides [main] to pf

main =
    Stdout.line "I'm a Roc application"
```

I am using a Manjaro Linux with all rolling release dependencies updated today (Dec 2 2022 at around 19:00 CET). The roc version I am using is roc_nightly-linux_x86_64-2022-12-02-0d80e74.tar.gz, or roc --version "roc nightly pre-release, built from commit 0d80e74 on Fr 02 Dez 2022 09:08:27 UTC"

I also tried to download the archive file from GitHub Releases, decompress it and refer to it locally. When I did that, the program became:

```
app "advent-of-code-1-1"
    packages { pf: "../Platform/main.roc" }
    imports [pf.Stdout]
    provides [main] to pf

main =
    Stdout.line "I'm a Roc application"
```
where ~/Desktop/advent-of-code-2022/Platform is a directory that contains the contents of the .tar.br in the GitHub releases page and nothing else.

The error message then became:
```
~/Desktop/advent-of-code-2022/day-1-1  roc dev day-1-1.roc
🔨 Rebuilding platform...
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread '<unnamed>' panicked at 'failed to open file "../Platform/dynhost": No such file or directory (os error 2)', crates/linker/src/lib.rs:513:29
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: roc_linker::open_mmap
   3: roc_linker::elf::preprocess_elf
   4: roc_linker::build_and_preprocess_host
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'Failed to (re)build platform.: Any { .. }', crates/cli/src/build.rs:342:46
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1814:5
   3: roc_cli::build::build_file
   4: roc_cli::build
   5: roc::main
```

**Comment by Anton-4** [comment]
Thanks for the detailed error report @asielorz! I was able to reproduce this error on my manjaro VM.
Using today's nightly (12-03) fixed the issue for the first code snippet with the URL, I assume the error on the second snippet will also no longer occur.

I also recommend deleting the ~/.cache/roc directory before trying the latest nightly.

Please re-open this issue if the suggested fix did not work for you.

**Comment by asielorz** [comment]
I tried it yesterday and it worked perfectly. Thanks a lot.
