### ISSUE TITLE
Undefined Symbol in relocation (internal compiler expectation was broken)

### ISSUE THREAD

**Issue by keeslinp** [roc-lang/roc#4668]
I'm working on day3 of roc and ran into this compiler crash while compiling
```
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread 'main' panicked at 'Undefined Symbol in relocation, (+6152, Relocation { kind: PltRelative, encoding: Generic, size: +20, target: Symbol(SymbolIndex(+8d)), addend: +fffffffffffffffc, implicit_addend: false }): Ok(Symbol { name: "floor", address: +0, size: +0, kind: Unknown, section: Undefined, scope: Unknown, weak: false, flags: Elf { st_info: +10, st_other: +0 } })', crates/linker/src/elf.rs:1312:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: roc_linker::elf::surgery_elf_help
   3: roc_linker::link_preprocessed_host
   4: roc_cli::build::build_file
   5: roc_cli::build
   6: roc::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Here is the code I was compiling:
```
app "day3"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.1.1/zAoiC9xtQPHywYk350_b7ust04BmWLW00sjb9ZPtSQk.tar.br" }
    imports [pf.Stdout, pf.File, pf.Path, pf.Task]
    provides [main] to pf

Bag : { first: Set U32, second: Set U32 }

score : U32 -> U32
score = \scalar ->
    if scalar < 97 then
        scalar - 65 + 27
    else
        scalar - 97 + 1
expect score 97 == 1
expect score 65 == 27

accumulateRow : Str -> Bag
accumulateRow = \row ->
    scalars = row |> Str.toScalars
    { before, others } = List.split scalars ((List.len scalars |> Num.toFrac) / 2 |> Num.floor)
    {
        first: before |> List.map score |> Set.fromList,
        second: others |> List.map score |> Set.fromList,
    }

expect accumulateRow "abcd" == { first: Set.fromList [1, 2], second: Set.fromList [3, 4] }
expect accumulateRow "pLPv" == { first: Set.fromList [16, 38], second: Set.fromList [42, 22] }

scoreRow : Bag -> U32
scoreRow = \{ first, second } ->
    Set.intersection first second |> Set.toList |> List.sum

processRow : Str -> U32
processRow = \row ->
    row |> accumulateRow |> scoreRow

expect processRow "vJrwpWtwJgWrhcsFMMfFFhFp" == 16

part1 : Str -> U32
part1 = \file -> 
    file
    |> Str.split "\n"
    |> List.map processRow
    |> List.sum

exampleInput =
"""
vJrwpWtwJgWrhcsFMMfFFhFp
jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL
PmmdzqPrVvPwwTWBwg
wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn
ttgJtRGJQctTZtZT
CrZsJsPPZsGzwwsLwLmpwMDw
"""

expect part1 exampleInput == 157

main =
    result <- Task.attempt (File.readUtf8 (Path.fromStr "./day2.txt"))
    count = Result.map result \file -> { first: part1 file }
    when count is
        Ok { first } -> 
            first |> Num.toStr |> Stdout.line
        Err e -> when e is
            FileReadUtf8Err _path _ -> Stdout.line "Bad path"
            FileReadErr _path readError -> readError |> File.readErrToStr |> Stdout.line
```

Interestingly `roc test day3.roc` is totally fine and all tests pass (presumably because `main` is not actually being used).

I'm on the latest roc build `012810d7e840bc543b37522ff1e47ebb6706c72b`

**Comment by keeslinp** [comment]
Took a fresh look this morning and was able to trim it down to just this:
```
app "day3"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.1.1/zAoiC9xtQPHywYk350_b7ust04BmWLW00sjb9ZPtSQk.tar.br" }
    imports [pf.Stdout]
    provides [main] to pf

half : Nat -> U32
half = \num ->
    (num |> Num.toF32) / 2 |> Num.floor

expect half 10 == 5

main =
    10 |> half |> Num.toStr |> Stdout.line
```
In hindsight that is kinda obvious cause the error message mentions floor.

Tests still pass which is odd :thinking: . Luckily if I just do Num.divTrunc then it works fine

**Comment by folkertdev** [comment]
thanks for reporting. I suspect this is related to #3609. you can try passing `--linker=legacy` as an extra argument to roc. That will use the system linker which is slower, but should not have this issue.

**Comment by JRI98** [comment]
No longer reproduces
