### ISSUE TITLE
Ambient functions don't unify (internal compiler error)

### ISSUE THREAD

**Issue by keeslinp** [roc-lang/roc#4671]
I get this error when I run `roc check`, and it hangs.

```
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread '<unnamed>' panicked at 'ambient functions don't unify', /home/pearcekeesling/code/roc/crates/compiler/unify/src/unify.rs:247:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
   3: roc_solve::specialize::compact_lambda_sets_of_vars
   4: roc_solve::solve::compact_lambdas_and_check_obligations
   5: roc_solve::solve::solve
   6: roc_solve::solve::run
   7: roc_solve::module::run_solve
   8: roc_load_internal::file::run_solve_solve
   9: roc_load_internal::file::run_task
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Code snippet:
```
app "day3"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.1.1/zAoiC9xtQPHywYk350_b7ust04BmWLW00sjb9ZPtSQk.tar.br" }
    imports [pf.Stdout, pf.File, pf.Path, pf.Task]
    provides [main] to pf
commonSet : List (Set a) -> Set a | a has Eq
commonSet = \list ->
    result = list |> List.walk None \common, set ->
        when common is
            None -> Some set
            Some value -> Some (Set.intersection value set)
    when result is
        None -> Set.empty
        Some value -> value

expect ([[1, 2, 3], [2, 3, 4], [3, 4, 5]] |> List.map Set.fromList |> commonSet) == ([3] |> Set.fromList)
```

I'm probably doing something wrong here and I'll try to figure out what it is, but I thought I'd report it since the error message specifically calls out a compiler error.

**Comment by keeslinp** [comment]
Looks like if I swap out the `==` in the expect for a `Set.contains` then it passes. So I am guessing that Set equality is not supported but the error message just wasn't making that very clear?

**Comment by ayazhafiz** [comment]
Interesting, this seems enough to reproduce the crash:

```
interface R exposes [] imports []

expect (Set.fromList [1u8]) == (Set.fromList [1u8])
```

my guess is this is a problem in how the `==` for Set is derived

**Comment by ayazhafiz** [comment]
Set equality should be supported, but we may not have tested it very well..
