### ISSUE TITLE
vanilla install, cannot find `str.zig` when running rocLovesZig.roc

### ISSUE THREAD

**Issue by hjwp** [roc-lang/roc#4706]
am following the installation instructions, got this far:

```
👉  ./roc examples/platform-switching/rocLovesZig.roc                    
🔨 Rebuilding platform...
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread '<unnamed>' panicked at 'cannot find `str.zig`. Check the source code in find_zig_str_path() to show all the paths I tried.', crates/compiler/build/src/link.rs:242:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Failed to (re)build platform.: Any { .. }', crates/cli/src/build.rs:342:46
```

zig is installed:

```
👉  ll `which zig`                                     
lrwxrwxrwx 1 harry harry 38 Dec  7 05:22 /home/harry/.local/bin/zig -> /home/harry/zig-linux-x86_64-0.9.1/zig
```

**Comment by Anton-4** [comment]
Hi @hjwp, I'll look into this error and set up some tests to prevent from happening again in the future.

**Comment by Anton-4** [comment]
The fix will be in tomorrow's nightly @hjwp :)
