### ISSUE TITLE
Compiler Panic When Constructing Dict

### ISSUE THREAD

**Issue by peacememories** [roc-lang/roc#4743]
While solving day 8 of AoC I ran across a compiler crash when trying to create a dictionary with the type signature `Dict {x: I32, y: I32} Nat` from a `List (T {x: I32, y: I32} Nat)` using `Dict.fromList`

The code in question is [here](https://gitea.peacememori.es/peacememories/adventofcode2022/src/commit/2e8a2e26b7cf95e0de09966932bf571c4ea3d646/roc/day08.roc#L71-L82)

Replacing this piece of code with the helper function `woodFromInput` (as seen [here](https://gitea.peacememori.es/peacememories/adventofcode2022/src/commit/8298a6089fc3a40f5417ef782920ef88d969e113/roc/day08.roc)) solves the issue.

Using a `List.walk` instead of doing `Dict.fromList` directly does not make any difference.

The error message in question is:

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates/compiler/mono/src/ir.rs:5710:56
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:48:5
   3: roc_mono::ir::late_resolve_ability_specialization
   4: roc_mono::ir::with_hole
   5: roc_mono::ir::from_can
   6: roc_mono::ir::specialize_variable
   7: roc_mono::ir::specialize_external_help
   8: roc_mono::ir::specialize_all
   9: roc_load_internal::file::run_task
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The compiler also hangs instead of exiting.

**Comment by ayazhafiz** [comment]
I suspect this is because Hash is not yet implemented for Hash, although the type checker assumes that it is.

**Comment by ayazhafiz** [comment]
Nevermind, this reproduces on latest Roc. The symptom in debug mode is

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `3402`,
 right: `3306`', crates/compiler/mono/src/ir.rs:1178:33
```

resolving to failures here:

https://github.com/roc-lang/roc/blob/662eb5895eab36af4550a2c00d2bf089f0ef9340/crates/compiler/mono/src/ir.rs#L1169-L1182

**Comment by ayazhafiz** [comment]
Root cause is likely the same as https://github.com/roc-lang/roc/issues/4717
