### ISSUE TITLE
`dbg` caused: `entered unreachable code` [...] `nonrecursive Union layout`

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#4752]
This code works:
```
app "hello"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.>
    imports [pf.Stdout]
    provides [main] to pf
 
main =
    total = stringify 5
 
    Stdout.line "\(total)"
 
stringify = \num ->
    #dbg num
    Num.toStr (num)
```
Uncommenting the `dbg` yields:
```
thread 'main' panicked at 'internal error: entered unreachable code: Weird content for nonrecursive Union layout: FlexVar(None)', /home/big-ci-user/actions-runner/_work/roc/roc/crates/repl_eval/src/eval.rs:659:26
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: roc_repl_eval::eval::addr_to_ast
   3: roc_repl_expect::get_values
   4: roc_cli::roc_dev_native
   5: roc_cli::roc_run
   6: roc_cli::build
   7: roc::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
 
Very similar code generates a different error that could have the same cause.
```
app "hello"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.>
    imports [pf.Stdout]
    provides [main] to pf
 
main =
    total = stringify {birds: 5, iguanas: 7}
 
    Stdout.line "\(total)"
 
stringify = \rec ->
    dbg rec
    Num.toStr (rec.birds)
```
```
thread 'main' panicked at 'internal error: entered unreachable code: Weird content for nonrecursive Union layout: FlexVar(None)', /home/big-ci-user/actions-runner/_work/roc/roc/crates/repl_eval/src/eval.rs:659:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
est$ RUST_BACKTRACE=1 ../roc dev
thread 'main' panicked at 'Error in alias analysis: error in module ModName("UserApp"), function definition FuncName("\x01\x00\x00\x00\x10\x00\x00\x00+O\xcdE\xd4\x18\xe3\xab"), definition of value binding ValueId(4): expected type '((),)', found type '(((), ()),)'', crates/compiler/gen_llvm/src/llvm/build.rs:4306:19
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: roc_gen_llvm::llvm::build::build_procedures_help
   3: roc_build::program::gen_from_mono_module_llvm
   4: roc_build::program::gen_from_mono_module
   5: roc_cli::build::build_file
   6: roc_cli::build
   7: roc::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by ayazhafiz** [comment]
@folkertdev I think the problem here is that `dbg` stores only the generalized type currently, not the type per specialization

**Comment by folkertdev** [comment]
yes. Why is that though? should specialization not just take care of that?

**Comment by ayazhafiz** [comment]
I believe the issue is that there is only one type variable stored for a dbg symbol. So it's not specialized for every location it's used, and after specialization the type variable is rolled back to the generalized version.
