### ISSUE TITLE
Running Zig platforms crashes from the same directory

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#4992]
[Zulip discussion](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/zig.20platform/near/322033465)

Roc crashes when running the zig examples from the same directory.

@bhansconnect you asked me to log this issue.  

```
luke@192-168-1-105 roc % roc run examples/platform-switching/rocLovesZig.roc 
🔨 Rebuilding platform...
Roc <3 Zig!
runtime: 0.000ms
luke@192-168-1-105 roc % cd examples/platform-switching 
luke@192-168-1-105 platform-switching % roc run rocLovesZig.roc 
🔨 Rebuilding platform...
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread '<unnamed>' panicked at 'cannot find `str.zig`. Check the source code in find_zig_str_path() to show all the paths I tried.', crates/compiler/build/src/link.rs:217:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Failed to (re)build platform.: Any { .. }', crates/cli/src/build.rs:332:46
```

**Comment by lukewilliamboswell** [comment]
Note I think you can only compile zig platforms from the root of the repository due to this issue.
