### ISSUE TITLE
windows breakout hello gui flaky failure

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#5024]
```
---- cli_run::breakout_hello_gui stdout ----
error: test failed, to rerun pass `-p roc_cli --test cli_run`
thread 'cli_run::breakout_hello_gui' panicked at '
___________
The roc command:

  "D:\\a\\roc\\roc\\target\\release\\roc.exe build --optimize D:\\a\\roc\\roc\\examples\\gui\\breakout\\hello-gui.roc --"

had unexpected stderr:

  thread '<unnamed>' panicked at 'unable to copy \\?\D:\a\roc\roc\examples\gui\breakout\platform\target\release\host.exe => D:\a\roc\roc\examples\gui\breakout\platform\dynhost.exe: Os { code: 1224, kind: Uncategorized, message: "The requested operation cannot be performed on a file with a user-mapped section open." }

Is the file used by another invocation of roc?', crates\compiler\build\src\link.rs:796:17
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\panicking.rs:142
   2: roc_build::link::rebuild_host
   3: roc_linker::build_and_preprocess_host
   4: <roc_can::pattern::TupleDestruct as core::fmt::Debug>::fmt
   5: <&T as core::fmt::Display>::fmt
   6: alloc::boxed::impl$44::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\alloc\src\boxed.rs:1940
   7: alloc::boxed::impl$44::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\alloc\src\boxed.rs:1940
   8: std::sys::windows::thread::impl$0::new::thread_start
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys\windows\thread.rs:56
   9: BaseThreadInitThunk
  10: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'Failed to (re)build platform.: Any { .. }', crates\cli\src\build.rs:332:46
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\panicking.rs:142
   2: core::result::unwrap_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\result.rs:1785
   3: roc_cli::build::build_file
   4: roc_cli::build::build_file
   5: roc_cli::build
   6: core::ptr::drop_in_place<target_lexicon::triple::Triple>
   7: <ring::rsa::RsaParameters as core::fmt::Debug>::fmt
   8: <ring::rsa::RsaParameters as core::fmt::Debug>::fmt
   9: core::ops::function::impls::impl$2::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\ops\function.rs:283
  10: std::panicking::try::do_call
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:492
  11: std::panicking::try
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:456
  12: std::panic::catch_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panic.rs:137
  13: std::rt::lang_start_internal::closure$2
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\rt.rs:148
  14: std::panicking::try::do_call
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:492
  15: std::panicking::try
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:456
  16: std::panic::catch_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panic.rs:137
  17: std::rt::lang_start_internal
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\rt.rs:148
  18: main
  19: invoke_main
             at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  20: __scrt_common_main_seh
             at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  21: BaseThreadInitThunk
  22: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

___________
', crates\cli\tests\cli_run.rs:155:13
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\panicking.rs:142
   2: alloc::alloc::box_free
   3: alloc::string::impl$82::fmt
   4: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    cli_run::breakout_hello_gui

test result: FAILED. 15 passed; 1 failed; 34 ignored; 0 measured; 0 filtered out; finished in 577.79s
```

**Comment by skyqrose** [comment]
This example was removed in https://github.com/roc-lang/roc/pull/6917 , so this is no longer relevant.
