### ISSUE TITLE
Record update with `&` fails on imported record

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#5131]
This is similar to https://github.com/roc-lang/roc/issues/3908 which has been resolved, I think the issue may be caused by the fact that `defaultRequest` is imported.

```
app "temptest"
    packages { pf: "cli-platform/main.roc" }
    imports [pf.Stdout, pf.Http.{defaultRequest}]
    provides [main] to pf

main =
    request = { defaultRequest & url: "http://www.example.com" }

    Stdout.line request.url
```

The error:
```
❯ RUST_BACKTRACE=1 ./target/release/roc run examples/cli/temptest.roc 
🔨 Rebuilding platform...
thread 'main' panicked at 'no entry found for key', crates/compiler/alias_analysis/src/lib.rs:1404:28
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:1880:5
   5: roc_alias_analysis::expr_spec
   6: roc_alias_analysis::stmt_spec
   7: roc_alias_analysis::proc_spec
   8: roc_gen_llvm::llvm::build::build_procedures_help
   9: roc_gen_llvm::llvm::build::build_procedures
  10: roc_build::program::gen_from_mono_module_llvm
  11: roc_build::program::gen_from_mono_module
  12: roc_build::program::build_loaded_file
  13: roc_build::program::build_file
  14: roc_cli::build
  15: roc::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Using a non-imported record works:
```
app "temptest"
    packages { pf: "cli-platform/main.roc" }
    imports [pf.Stdout]
    provides [main] to pf

main =
    defaultRequest = {
        url: "",
    }

    request = { defaultRequest & url: "http://www.example.com" }

    Stdout.line request.url
```

**Comment by Anton-4** [comment]
This issue was originally reported [here](https://github.com/roc-lang/basic-cli/issues/23).
