### ISSUE TITLE
'panic: recursive value does not have Identifier pattern' when trying to destructure a lambda as a tuple

### ISSUE THREAD

**Issue by Innf107** [roc-lang/roc#5304]
## Minimal Example

Typing the following into the Roc REPL crashes the compiler
```
(_, x) = \x -> x
5
```

## Error Message
```
panicked at 'internal error: entered unreachable code: recursive value does not have Identifier pattern', crates/compiler/mono/src/ir.rs:6869:17

Stack:

getImports/imports.wbg.__wbg_new_abda76e883ba8a5f@https://www.roc-lang.org/repl/roc_repl_wasm.js:312:21
console_error_panic_hook::hook::hf3a47cf2e5d82233@https://www.roc-lang.org/repl/roc_repl_wasm_bg.wasm:wasm-function[1194]:0x333a4c
std::panicking::rust_panic_with_hook::h70a0e195f4db2a29@https://www.roc-lang.org/repl/roc_repl_wasm_bg.wasm:wasm-function[2701]:0x3a473d
std::panicking::begin_panic_handler::{{closure}}::hdcfc819ce836829e@https://www.roc-lang.org/repl/roc_repl_wasm_bg.wasm:wasm-function[2954]:0x3af443
std::sys_common::backtrace::__rust_end_short_backtrace::h53cabafab5b09ada@https://www.roc-lang.org/repl/roc_repl_wasm_bg.wasm:wasm-function[4392]:0x3d212b
rust_begin_unwind@https://www.roc-lang.org/repl/roc_repl_wasm_bg.wasm:wasm-function[4184]:0x3cf21a
core::panicking::panic_fmt::h751be80779d42b53@https://www.roc-lang.org/repl/roc_repl_wasm_bg.wasm:wasm-function[4239]:0x3cfffe
roc_mono::ir::from_can::hcb16c104d58ef703@https://www.roc-lang.org/repl/roc_repl_wasm_bg.wasm:wasm-function[162]:0x1ceec1
roc_mono::ir::specialize_variable::h8b55911880048cad@https://www.roc-lang.org/repl/roc_repl_wasm_bg.wasm:wasm-function[117]:0x18e12d
roc_mono::ir::specialize_external_help::hd1ae04683b963db5@https://www.roc-lang.org/repl/roc_repl_wasm_bg.wasm:wasm-function[81]:0x144961
roc_load_internal::file::run_task::h2af1a082e2d5876f@https://www.roc-lang.org/repl/roc_repl_wasm_bg.wasm:wasm-function[19]:0x23795
roc_load_internal::file::load::heb81ae50539fd93d@https://www.roc-lang.org/repl/roc_repl_wasm_bg.wasm:wasm-function[43]:0xc7230
roc_repl_wasm::repl::entrypoint_from_js::{{closure}}::hddbe6e30c99d9ee3@https://www.roc-lang.org/repl/roc_repl_wasm_bg.wasm:wasm-function[20]:0x2c485
 as core::future::future::Future>::poll::h8cdf8b7678bb2de4@https://www.roc-lang.org/repl/roc_repl_wasm_bg.wasm:wasm-function[988]:0x314068
wasm_bindgen_futures::queue::Queue::new::{{closure}}::h480e6bfb63753458@https://www.roc-lang.org/repl/roc_repl_wasm_bg.wasm:wasm-function[1471]:0x353a7d
+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h36c3365f47e7fdb6@https://www.roc-lang.org/repl/roc_repl_wasm_bg.wasm:wasm-function[4520]:0x3d3536
__wbg_adapter_12@https://www.roc-lang.org/repl/roc_repl_wasm.js:204:10
real@https://www.roc-lang.org/repl/roc_repl_wasm.js:189:20
```

**Comment by skyqrose** [comment]
This no longer reproduces in the repl, but it does reproduce with `roc build`

```
» (_, x) = \x -> x
panicked at crates/repl_ui/src/repl_state.rs:189:37:
not yet implemented: handle pattern other than identifier (which repl doesn't support).
```

```
app [main] { pf: platform "https://github.com/roc-lang/basic-cli/releases/download/0.16.0/O00IPk-Krg_diNS2dVWlI0ZQP794Vctxzv0ha96mK0E.tar.br" }

main =
    (_, x) = \x -> x
    Task.ok {}
```

```
$ roc build main.roc
thread '<unnamed>' panicked at crates/compiler/mono/src/ir.rs:7145:17:
internal error: entered unreachable code: recursive value does not have Identifier pattern
```

(version roc_nightly-linux_x86_64-2024-11-21-86b1933)
