### ISSUE TITLE
roc dev ends with exit code 0 on panic

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#5428]
A test with `helloWorldNoURL.roc` where I altered `roc_fx_stdoutLine` in `examples/cli/cli-platform/src/lib.rs` to panic:
```
❯ cargo run --release run examples/helloWorldNoURL.roc
    Finished release [optimized] target(s) in 0.24s
     Running `target/release/roc run examples/helloWorldNoURL.roc`
🔨 Rebuilding platform...
thread 'main' panicked at 'explicit panic', src/lib.rs:310:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)

roc on  main [!] is 📦 v0.0.1 via 🦀 v1.66.1 via ❄️  impure (nix-shell) took 18s 
❯ echo $?
134

roc on  main [!] is 📦 v0.0.1 via 🦀 v1.66.1 via ❄️  impure (nix-shell) 
❯ cargo run --release dev examples/helloWorldNoURL.roc
    Finished release [optimized] target(s) in 0.18s
     Running `target/release/roc dev examples/helloWorldNoURL.roc`
🔨 Rebuilding platform...
thread 'main' panicked at 'explicit panic', src/lib.rs:310:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5

roc on  main [!] is 📦 v0.0.1 via 🦀 v1.66.1 via ❄️  impure (nix-shell) 
❯ echo $?
0
```
It may be relevant that [roc_dev_native](https://github.com/roc-lang/roc/blob/28e56937ccab4da5792fa9779bb3779063a2f9f5/crates/cli/src/lib.rs#L1009) uses `execve` after `libc::fork` vs the "direct" `execve` call in `roc_run_native_fast`.

This incorrect exit code hides certain failures of `cli_run` tests.

Do you know how we could fix this @folkertdev?

**Comment by Anton-4** [comment]
friendly ping @folkertdev
