### ISSUE TITLE
dbg `entered unreachable code`

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#5470]
```
❯ cat examples/helloWorld.roc 
app "helloWorld"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.3.2/tE4xS_zLdmmxmHwHih9kHWQ7fsXtJr7W7h3425-eZFk.tar.br" }
    imports [pf.Stdout]
    provides [main] to pf

main =
    x = 
        dbg "yo"
        "hey"
    Stdout.line x
```

```
❯ ./target/release/roc run examples/helloWorld.roc 
thread '<unnamed>' panicked at 'internal error: entered unreachable code: I think this is unreachable', crates/compiler/mono/src/ir.rs:4423:23
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
   2: roc_mono::ir::with_hole
   3: roc_mono::ir::from_can_let
   4: roc_mono::ir::from_can
   5: roc_mono::ir::specialize_variable
   6: roc_mono::ir::specialize_external_help
   7: roc_mono::ir::specialize_all
   8: roc_load_internal::file::run_task
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

roc version: built from source ebd5cbb00

**Comment by Ivo-Balbaert** [comment]
This code now works!

$ roc test25.roc
[test25.roc 10:13] "yo"
hey

I think this issue can be closed, @Anton-4 ?
