### ISSUE TITLE
undefined symbol in relocation

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#5472]
```
❯ ./target/release/roc  run examples/helloWorld.roc 
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread 'main' panicked at 'Undefined Symbol in relocation, (+3794, Relocation { kind: PltRelative, encoding: Generic, size: +20, target: Symbol(SymbolIndex(+24)), addend: +fffffffffffffffc, implicit_addend: false }): Ok(Symbol { name: "__modti3", address: +0, size: +0, kind: Label, section: Undefined, scope: Unknown, weak: false, flags: Elf { st_info: +10, st_other: +0 } })', crates/linker/src/elf.rs:1482:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
   2: roc_linker::elf::surgery_elf_help
   3: roc_linker::surgery
   4: roc_linker::link_preprocessed_host
   5: roc_build::program::build_loaded_file
   6: roc_build::program::build_file
   7: roc_cli::build
   8: roc::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
```
roc on  main [!] is 📦 v0.0.1 via 🦀 v1.66.1 via ❄️  impure (nix-shell) 
❯ cat examples/helloWorld.roc 
app "helloWorld"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.3.2/tE4xS_zLdmmxmHwHih9kHWQ7fsXtJr7W7h3425-eZFk.tar.br" }
    imports [pf.Stdout]
    provides [main] to pf

main =
    Stdout.line (Num.toStr (Result.withDefault (Str.toDec "50") 1dec))
```

roc version: built from source on [ebd5cbb](https://github.com/roc-lang/roc/commit/ebd5cbb00de3cc977c69caca9918524703cd5683)

**Comment by Anton-4** [comment]
Possibly related to #5471

**Comment by bhansconnect** [comment]
Yeah, same issue as #5471, but manifesting in a different way. Closing as duplicate
