### ISSUE TITLE
DBG anonymous tag in expect block

### ISSUE THREAD

**Issue by KilianVounckx** [roc-lang/roc#5480]
When running `roc test Tmp.roc`, where Tmp.roc contains the following:
```
interface Tmp
    exposes []
    imports []

expect
    want = Fail
    dbg want
    Bool.true
```

It prints the following error:
```
thread '<unnamed>' panicked at 'internal error: entered unreachable code: I think this is unreachable', crates/compiler/mono/src/ir.rs:4423:23
stack backtrace:
   0:     0x563e4bd5a0b0 - std::backtrace_rs::backtrace::libunwind::trace::h1d00f3fcf4cb5ac4
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x563e4bd5a0b0 - std::backtrace_rs::backtrace::trace_unsynchronized::h920a6ff332484ee2
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x563e4bd5a0b0 - std::sys_common::backtrace::_print_fmt::hd7323920c925af6d
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x563e4bd5a0b0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3155a8c966b4beb5
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x563e4bd83a2e - core::fmt::write::h062c617411b691df
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/fmt/mod.rs:1209:17
   5:     0x563e4bd532c5 - std::io::Write::write_fmt::hb61fdf1275c61e1c
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/io/mod.rs:1682:15
   6:     0x563e4bd59e75 - std::sys_common::backtrace::_print::hd1b4d9664ab500e0
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x563e4bd59e75 - std::sys_common::backtrace::print::hca896ae22beb06cb
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x563e4bd5b86f - std::panicking::default_hook::{{closure}}::h0b5eeed5cf36ab5f
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:267:22
   9:     0x563e4bd5b5aa - std::panicking::default_hook::h8932b573145a321b
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:286:9
  10:     0x563e4bd5bf68 - std::panicking::rust_panic_with_hook::h4b1447a24e3e94f8
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:688:13
  11:     0x563e4bd5bd07 - std::panicking::begin_panic_handler::{{closure}}::h8701da9995a3820c
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:579:13
  12:     0x563e4bd5a55c - std::sys_common::backtrace::__rust_end_short_backtrace::hb696c5ed02a01598
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x563e4bd5ba22 - rust_begin_unwind
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
  14:     0x563e493a6c63 - core::panicking::panic_fmt::h8aa706a976963c88
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
  15:     0x563e4b9d892f - roc_mono::ir::with_hole::h51ce519e1d71fe05
  16:     0x563e4b9e9cdc - roc_mono::ir::from_can::h27ece1c4ab3aff21
  17:     0x563e4b9bcf26 - roc_mono::ir::from_can_let::h9dfd15947a3a6fac
  18:     0x563e4b9e82fd - roc_mono::ir::from_can::h27ece1c4ab3aff21
  19:     0x563e4b9c9ed3 - roc_mono::ir::specialize_variable::h3067c6a52f141202
  20:     0x563e4b9c1a26 - roc_mono::ir::specialize_external_help::hc65c3a42a15116b9
  21:     0x563e4b9c147e - roc_mono::ir::specialize_all::heae33a56cf0647f7
  22:     0x563e4b5ac3e8 - roc_load_internal::file::run_task::h57f3167bc7dd457a
  23:     0x563e4b535a0f - core::ops::function::FnOnce::call_once{{vtable.shim}}::h6631330de002bc59
  24:     0x563e4b53161e - std::sys_common::backtrace::__rust_begin_short_backtrace::hbbb2862b86a92cf5
  25:     0x563e4b536b2f - core::ops::function::FnOnce::call_once{{vtable.shim}}::h830e1b75dbd7347f
  26:     0x563e4bd61f23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6202d10b0224e7b0
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/alloc/src/boxed.rs:1987:9
  27:     0x563e4bd61f23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4dbea73c9cec160b
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/alloc/src/boxed.rs:1987:9
  28:     0x563e4bd61f23 - std::sys::unix::thread::Thread::new::thread_start::h0a2f4c32ba2f2278
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys/unix/thread.rs:108:17
  29:     0x7f0c49288e86 - start_thread
  30:     0x7f0c4930fd30 - clone3
  31:                0x0 - <unknown>
```

After this it doesn't terminate. It is just frozen. I have to press Ctrl-C manually.

**Comment by Anton-4** [comment]
Thanks for reporting @KilianVounckx, this is likely the same bug as #5470 but I'd like to keep both issues open to confirm that both scenarios are fixed when we find a solution.
