### ISSUE TITLE
Roc crashes with `thread 'main' panicked at 'out of memory'`

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#5512]
Running the below with latest main gives the below `thread 'main' panicked at 'out of memory'`, seems to be cause by the following test

```
# All tests pass when this is commented out
expect 
    actual = parseUtf8 (Str.toUtf8 "\"hello\",\n")
    actual == Ok { taken: String "hello", rest: [',', '\n'] }
```

```
% roc test package/String.roc
ld: warning: -undefined dynamic_lookup may not work with chained fixups
thread 'main' panicked at 'out of memory', /Users/luke/.cargo/registry/src/github.com-1ecc6299db9ec823/bumpalo-3.12.2/src/lib.rs:1853:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```coffee
interface String
    exposes []
    imports []

ParseResult : Result {taken: Json, rest: List U8} [Invalid]

Json : [
    Object (Dict Str Json), 
    Array (List Json),
    String Str,
    Number Dec,
    Boolean Bool, 
    Null
]

State : [
    Start,
    Chars Nat,
    Escaped Nat,
    UnicodeA Nat,
    UnicodeB Nat,
    UnicodeC Nat,
    UnicodeD Nat,
    Finish Nat,
    Invalid,
]

walkBytes : State, U8 -> [Continue State, Break State]
walkBytes = \state, byte ->
    when (state, byte) is
        (Start, b) if b == '"' -> Continue (Chars 1)
        (Chars n, b) if b == '"' -> Break (Finish (n + 1))
        (Chars n, b) if b == '\\' -> Continue (Escaped (n + 1))
        (Chars n, _) -> Continue (Chars (n + 1))
        (Escaped n, b) if isEscapedChar b -> Continue (Chars (n + 1))
        (Escaped n, b) if b == 'u' -> Continue (UnicodeA (n + 1))
        (UnicodeA n, b) if isHex b -> Continue (UnicodeB (n + 1))
        (UnicodeB n, b) if isHex b -> Continue (UnicodeC (n + 1))
        (UnicodeC n, b) if isHex b -> Continue (UnicodeD (n + 1))
        (UnicodeD n, b) if isHex b -> Continue (Chars (n + 1))
        _ -> Break (Invalid)

expect walkBytes Start '\n' == Break Invalid
expect walkBytes Start '"' == Continue (Chars 1)
expect walkBytes (Chars 3) '"' == Break (Finish 4)
expect walkBytes (Chars 3) '\\' == Continue (Escaped 4)
expect walkBytes (Chars 3) 'a' == Continue (Chars 4)

parseUtf8 : List U8 -> ParseResult
parseUtf8 = \bytes ->
    when List.walkUntil bytes Start walkBytes is
        Finish n ->
            when Str.fromUtf8 (List.sublist bytes { start: 0, len: n }) is
                Ok str ->
                    taken = String str
                    rest = List.drop bytes n

                    Ok { taken, rest }

                _ ->
                    Err Invalid

        _ ->
            Err Invalid

# All tests pass when this is commented out
expect 
    actual = parseUtf8 (Str.toUtf8 "\"hello\",\n")
    actual == Ok { taken: String "hello", rest: [',', '\n'] }

isEscapedChar : U8 -> Bool
isEscapedChar = \b ->
    when b is
        '"' | '\\' | '/' | 'b' | 'f' | 'n' | 'r' | 't' -> Bool.true
        _ -> Bool.false

isHex : U8 -> Bool
isHex = \b ->
    (b >= '0' && b <= '9')
    || (b >= 'a' && b <= 'f')
    || (b >= 'A' && b <= 'F')

expect isHex '0' && isHex 'f' && isHex 'F' && isHex 'A' && isHex '9'
expect !(isHex 'g' && isHex 'x' && isHex 'u' && isHex '\\' && isHex '-')

escapedCharFromJson : U8 -> U8
escapedCharFromJson = \b ->
    when b is
        '"' -> 0x22 # U+0022 Quotation mark
        '\\' -> 0x5c # U+005c Reverse solidus
        '/' -> 0x2f # U+002f Solidus
        'b' -> 0x08 # U+0008 Backspace
        'f' -> 0x0c # U+000c Form feed
        'n' -> 0x0a # U+000a Line feed
        'r' -> 0x0d # U+000d Carriage return
        't' -> 0x09 # U+0009 Tab
        _ -> b

expect escapedCharFromJson 'n' == '\n'
```

**Comment by jamesbirtles** [comment]
I think i am running into this, or something very similar also.

The following code:
```roc
    bytes = [56, 46, 49, 46, 48, 0, 236, 6, 0]
    valueA = [56, 46, 49, 46, 48]
    valueB = (List.splitFirst bytes 0) |> Result.map .before |> Result.withDefault []

    dbg
        valueA

    dbg
        Str.fromUtf8 valueA

    dbg
        valueB

    dbg
        Str.fromUtf8 valueB
```
gives the this output:
```
[main.roc 26:9] [56, 46, 49, 46, 48]
[main.roc 29:9] Ok "8.1.0"
[main.roc 32:9] [56, 46, 49, 46, 48]
thread 'main' panicked at 'out of memory', /Users/m1ci/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bumpalo-3.14.0/src/lib.rs:1854:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by bitsoflogic** [comment]
I'm seeing this as well with the 12/01 nightly and basic-cli 0.7.0.

```
  packages 
    { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.7.0/bkGby8jb0tmZYsy2hg1E_B2QrCgcSTxdUlHtETwm5m4.tar.br" 
    , parser: "https://github.com/lukewilliamboswell/roc-parser/releases/download/0.2.0/dJQSsSmorujhiPNIvJKlQoI92RFIG_JQwUfIxZsCSwE.tar.br",
    }
  imports 
    [ pf.Stdout
    , pf.Task
    , "./day3-input.txt" as input : Str
    , parser.Core.{ Parser, const, map, keep, skip, oneOf, sepBy }
    , parser.String.{ parseStr, string, digits, codeunit }
    ]
  provides [main] to pf

# ...

element : Parser (List U8) [Part Str, Separator, Symbol]
element = 
  oneOf [
    digits |> map \d -> Part (Num.toStr d),
    string  "." |> map \_ -> Separator,
    string "*" |> map \_ -> Symbol,
    string "+" |> map \_ -> Symbol,
    string "$" |> map \_ -> Symbol,
    string "#" |> map \_ -> Symbol,
  ] 

expect 
  actual = parseStr element "467..."

  actual == Ok (Part "467")
```

Changing the expect to this eliminates the crash, but eliminates the useful debugging info:
```
expect parseStr element "467..." == Ok (Part "467")
```

**Comment by Anton-4** [comment]
I think this was fixed by https://github.com/roc-lang/roc/issues/6158, can you give it another try with today's nightly @bitsoflogic?

**Comment by skyqrose** [comment]
I'm cleaning up old issues, so I'm closing this on the assumption that that PR did fix the problem. If it didn't, feel free to reopen the issue.
