### ISSUE TITLE
Roc crashes with `Expected symbol to be in the map` 

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#5513]
```
% roc run aoc-2022/08/broken.roc
thread 'main' panicked at 'Expected symbol to be in the map', crates/compiler/mono/src/inc_dec.rs:348:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
app "broken"
    packages { 
        pf: "https://github.com/roc-lang/basic-cli/releases/download/0.3.2/tE4xS_zLdmmxmHwHih9kHWQ7fsXtJr7W7h3425-eZFk.tar.br",
    }
    imports [
        pf.Stdout,
    ]
    provides [ main ] to pf

main =
    sampleState = processInput []

    Stdout.line "Done"

Trees : {
    rows : Nat, # zero indexed 
    cols : Nat, # zero indexed
    count : Nat, # for  
}

initialArray : Trees
initialArray = {
    rows : 1,
    cols : 0,
    count : 0, 
}

processInput : List U8 {} -> Trees
processInput = \data ->
    state, elem <- List.walk data initialArray

    when elem is 
        '\n' -> 
            if state.cols == 0 then
                {state & rows : state.rows + 1, cols : state.count}
            else 
                {state & rows : state.rows + 1}
        _ -> crash "unexpected input"

```

**Comment by JRI98** [comment]
Smaller reproducer with error ```thread 'main' panicked at 'symbol `#UserApp.9` does not have an rc type', crates/compiler/mono/src/inc_dec.rs:373:21```:

```elm
app "main"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.8.1/x8URkvfyi9I0QhmVG98roKBUs_AZRkLFwFJVJ3942YA.tar.br" }
    imports [pf.Task]
    provides [main] to pf

main =
    _ = f { a: 0, b: 0 }
    Task.ok {}

f = \state ->
    { state & a: state.b }
```
