### ISSUE TITLE
thread '<unnamed>' panicked at 'not a lambda set', crates/compiler/types/src/subs.rs:2169:18

### ISSUE THREAD

**Issue by JTeeuwissen** [roc-lang/roc#5554]
After modifying the Deriv benchmark example to this:
```coffee
app "deriv"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.3.2/tE4xS_zLdmmxmHwHih9kHWQ7fsXtJr7W7h3425-eZFk.tar.br" }
    imports [pf.Stdout, pf.Task.{ Task }]
    provides [main] to pf

# based on: https://github.com/koka-lang/koka/blob/master/test/bench/haskell/deriv.hs
IO a : Task.Task a []

main : Task.Task {} []
main =
    x : Expr
    x = Var "x"

    f : Expr
    f = pow x x

    _ <- Task.await (nest deriv 10 f)

    Stdout.line "done"

nest : (I32, Expr -> IO Expr), I32, Expr -> IO Expr
nest = \f, n, e -> nestHelp n f n e


nestHelp : I32, (I32, Expr -> IO Expr), I32, Expr -> IO Expr
nestHelp = \s, f, m, x -> when m is
    0 -> Task.succeed x
    _ ->
        w <- Task.await (f (s - m) x)
        nestHelp s f (m - 1) w

Expr : [Val I32, Var Str, Add Expr Expr, Mul Expr Expr, Pow Expr Expr, Ln Expr]

divmod : I32, I32 -> Result { div : I32, mod : I32 } [DivByZero]
divmod = \l, r ->
    when Pair (Num.divTruncChecked l r) (Num.remChecked l r) is
        Pair (Ok div) (Ok mod) -> Ok { div, mod }
        _ -> Err DivByZero

pown : I32, I32 -> I32
pown = \a, n ->
    when n is
        0 -> 1
        1 -> a
        _ ->
            when divmod n 2 is
                Ok { div, mod } ->
                    b = pown a div

                    b * b * (if mod == 0 then 1 else a)

                Err DivByZero ->
                    -1

add : Expr, Expr -> Expr
add = \a, b ->
    when Pair a b is
        Pair (Val n) (Val m) ->
            Val (n + m)

        Pair (Val 0) f ->
            f

        Pair f (Val 0) ->
            f

        Pair f (Val n) ->
            add (Val n) f

        Pair (Val n) (Add (Val m) f) ->
            add (Val (n + m)) f

        Pair f (Add (Val n) g) ->
            add (Val n) (add f g)

        Pair (Add f g) h ->
            add f (add g h)

        Pair f g ->
            Add f g

mul : Expr, Expr -> Expr
mul = \a, b ->
    when Pair a b is
        Pair (Val n) (Val m) ->
            Val (n * m)

        Pair (Val 0) _ ->
            Val 0

        Pair _ (Val 0) ->
            Val 0

        Pair (Val 1) f ->
            f

        Pair f (Val 1) ->
            f

        Pair f (Val n) ->
            mul (Val n) f

        Pair (Val n) (Mul (Val m) f) ->
            mul (Val (n * m)) f

        Pair f (Mul (Val n) g) ->
            mul (Val n) (mul f g)

        Pair (Mul f g) h ->
            mul f (mul g h)

        Pair f g ->
            Mul f g

pow : Expr, Expr -> Expr
pow = \a, b ->
    when Pair a b is
        Pair (Val m) (Val n) -> Val (pown m n)
        Pair _ (Val 0) -> Val 1
        Pair f (Val 1) -> f
        Pair (Val 0) _ -> Val 0
        Pair f g -> Pow f g

ln : Expr -> Expr
ln = \f ->
    when f is
        Val 1 -> Val 0
        _ -> Ln f

d : Str, Expr -> Expr
d = \x, expr ->
    when expr is
        Val _ -> Val 0
        Var y -> if x == y then Val 1 else Val 0
        Add f g -> add (d x f) (d x g)
        Mul f g -> add (mul f (d x g)) (mul g (d x f))
        Pow f g ->
            mul (pow f g) (add (mul (mul g (d x f)) (pow f (Val (-1)))) (mul (ln f) (d x g)))

        Ln f ->
            mul (d x f) (pow f (Val (-1)))

count : Expr -> I32
count = \expr ->
    when expr is
        Val _ -> 1
        Var _ -> 1
        Add f g -> count f + count g
        Mul f g -> count f + count g
        Pow f g -> count f + count g
        Ln f -> count f

deriv : I32, Expr -> IO Expr
deriv = \i, f ->
    fprime = d "x" f
    line =
        Num.toStr (i + 1)
        |> Str.concat " count: "
        |> Str.concat (Num.toStr (count fprime))

    _ <- Task.await (Stdout.line line)
    Task.succeed fprime
```

The error started occurring after changing `nest`/`nestHelp` from this
```coffee

nest : (I64, Expr -> IO Expr), I64, Expr -> IO Expr
nest = \f, n, e -> Task.loop { s: n, f, m: n, x: e } nestHelp

State : { s : I64, f : I64, Expr -> IO Expr, m : I64, x : Expr }

nestHelp : State -> IO [Step State, Done Expr]
nestHelp = \{ s, f, m, x } ->
    when m is
        0 -> Task.succeed (Done x)
        _ ->
            w <- Task.after (f (s - m) x)

            Task.succeed (Step { s, f, m: (m - 1), x: w })
```

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
   2: roc_types::subs::Subs::get_lambda_set
             at ./crates/compiler/types/src/subs.rs:2169:18
   3: roc_mono::ir::find_lambda_sets
             at ./crates/compiler/mono/src/ir.rs:9693:26
   4: roc_mono::ir::specialize_external_help
             at ./crates/compiler/mono/src/ir.rs:3087:25
   5: roc_mono::ir::specialize_host_specializations
             at ./crates/compiler/mono/src/ir.rs:2980:9
   6: roc_mono::ir::specialize_all
             at ./crates/compiler/mono/src/ir.rs:2941:5
   7: roc_load_internal::file::make_specializations
             at ./crates/compiler/load_internal/src/file.rs:5813:13
   8: roc_load_internal::file::run_task
             at ./crates/compiler/load_internal/src/file.rs:6557:17
   9: roc_load_internal::file::worker_task
             at ./crates/compiler/load_internal/src/file.rs:2261:34
  10: roc_load_internal::file::load_multi_threaded::{{closure}}::{{closure}}
             at ./crates/compiler/load_internal/src/file.rs:2061:25
  11: crossbeam_utils::thread::ScopedThreadBuilder::spawn::{{closure}}
             at /home/_/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.8.15/src/thread.rs:440:31
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/ops/function.rs:251:5
  13: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/alloc/src/boxed.rs:1987:9
```

on commit `36abaec07db8b0104b59d0d796421de528eb656e`

**Comment by ayazhafiz** [comment]
We now find the lambda set, but the code-generator generates invalid code.


```
❯ ROC_CHECK_MONO_IR=1 target/debug/roc build A.roc
Full source: procedure `pf.Task.fail` (`pf.Task.err`):
    let `pf.Task.93` : [<r>C {{Str, {}}, [<r>C *self *self, C *self, C *self *self, C *self *self, C I32, C Str]} {I32, I32, {}}, C
 [<r>C *self *self, C *self, C *self *self, C *self *self, C I32, C Str]] = CallByName `pf.InternalTask.fail` `pf.Task.err`;
    ret `pf.Task.93`;
IR PROBLEMS FOUND:
── PROC SPECIALIZATION NOT DEFINED ─────────────────────────────────────────────

in fail : ([]) ->
[<r>C {{Str, {}}, [<r>C *self *self, C *self, C *self *self, C *self *self, C I32, C Str]} {I32, I32, {}}, C [<r>C *self *self, C *
self, C *self *self, C *self *self, C I32, C Str]] ((niche
{}))

0│  procedure `pf.Task.fail` (`pf.Task.err`):
1│>     let `pf.Task.93` : [<r>C {{Str, {}}, [<r>C *self *self, C *self, C *self *self, C *self *self, C I32, C Str]} {I32, I32, {}
}, C [<r>C *self *self, C *self, C *self *self, C *self *self, C I32, C Str]] = CallByName `pf.InternalTask.fail` `pf.Task.err`;
2│      ret `pf.Task.93`;

No specialization

fail : ([]) ->
[<r>C {{Str, {}}, [<r>C *self *self, C *self, C *self *self, C *self *self, C I32, C Str]} {I32, I32, {}}, C [<r>C *self *self, C *
self, C *self *self, C *self *self, C I32, C Str]] ((niche
{}))

was found

The following specializations of InternalTask.fail were built:

fail : ([]) ->
[<r>C {{Str, {}}, [<r>C *self *self, C *self, C *self *self, C *self *self, C I32, C Str]} {I32, I32, {}}, C [<r>C *self *self, C *
self, C *self *self, C *self *self, C I32, C Str]] ((niche
{}))

fail : ([]) ->
[<r>C *self *self, C *self, C *self *self, C *self *self, C I32, C Str] ((niche
{}))

fail : ([]) -> [C Str {}, C {}] ((niche {}))
```
