### ISSUE TITLE
Not a lambda set in basic-cli Tty module

### ISSUE THREAD

**Issue by KilianVounckx** [roc-lang/roc#5583]
When running the following program:
```roc
app "tty"
    packages {
        cli: "../cli/main.roc",
    }
    imports [
        cli.Stdin,
        cli.Stdout,
        cli.Task.{ Task },
        cli.Tty,
    ]
    provides [main] to cli

main : Task {} U32
main =
    {} <- Tty.enableRawMode |> Task.await

    world = initialWorld {}
    {} <- loop world |> Task.await

    {} <- Tty.disableRawMode |> Task.await
    Task.succeed {}

World : {}

initialWorld : {} -> World

update : World, List U8 -> [Continue World, Exit]

display : World -> Str

loop : World -> Task {} *
loop = \world ->
    {} <- display world |> Stdout.write |> Task.await
    event <- Stdin.bytes |> Task.await
    when update world event is
        Continue newWorld ->
            {} <- display newWorld |> Stdout.write |> Task.await
            loop newWorld
        Exit ->
            Task.succeed {}
```

This produces the following error (when run with RUST_BACTRACE=full):
```
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread '<unnamed>' panicked at 'not a lambda set', crates/compiler/types/src/subs.rs:2169:18
stack backtrace:
   0:     0x55a5c26a16d0 - std::backtrace_rs::backtrace::libunwind::trace::h1d00f3fcf4cb5ac4
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55a5c26a16d0 - std::backtrace_rs::backtrace::trace_unsynchronized::h920a6ff332484ee2
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55a5c26a16d0 - std::sys_common::backtrace::_print_fmt::hd7323920c925af6d
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55a5c26a16d0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3155a8c966b4beb5
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55a5c26cb04e - core::fmt::write::h062c617411b691df
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/fmt/mod.rs:1209:17
   5:     0x55a5c269a8e5 - std::io::Write::write_fmt::hb61fdf1275c61e1c
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/io/mod.rs:1682:15
   6:     0x55a5c26a1495 - std::sys_common::backtrace::_print::hd1b4d9664ab500e0
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55a5c26a1495 - std::sys_common::backtrace::print::hca896ae22beb06cb
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55a5c26a2e8f - std::panicking::default_hook::{{closure}}::h0b5eeed5cf36ab5f
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:267:22
   9:     0x55a5c26a2bca - std::panicking::default_hook::h8932b573145a321b
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:286:9
  10:     0x55a5c26a3588 - std::panicking::rust_panic_with_hook::h4b1447a24e3e94f8
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:688:13
  11:     0x55a5c26a32e1 - std::panicking::begin_panic_handler::{{closure}}::h8701da9995a3820c
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:577:13
  12:     0x55a5c26a1b7c - std::sys_common::backtrace::__rust_end_short_backtrace::hb696c5ed02a01598
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x55a5c26a3042 - rust_begin_unwind
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
  14:     0x55a5bfcbc773 - core::panicking::panic_fmt::h8aa706a976963c88
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
  15:     0x55a5c26214e6 - roc_types::subs::Subs::get_lambda_set::h1d1bfb477a07da27
  16:     0x55a5c2328bd7 - roc_mono::ir::specialize_external_help::hf43b2872f22a15b4
  17:     0x55a5c232355e - roc_mono::ir::specialize_all::hcb71a15e4965f24b
  18:     0x55a5c1ed56b9 - roc_load_internal::file::run_task::h64f08d8ae00ed6fd
  19:     0x55a5c1e5ec9f - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc8b2412825a5bfa9
  20:     0x55a5c1e5a67e - std::sys_common::backtrace::__rust_begin_short_backtrace::hb7fd42ea52db34c2
  21:     0x55a5c1e5e11f - core::ops::function::FnOnce::call_once{{vtable.shim}}::h867af9c7f97b8060
  22:     0x55a5c26a9543 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6202d10b0224e7b0
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/alloc/src/boxed.rs:1987:9
  23:     0x55a5c26a9543 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4dbea73c9cec160b
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/alloc/src/boxed.rs:1987:9
  24:     0x55a5c26a9543 - std::sys::unix::thread::Thread::new::thread_start::h0a2f4c32ba2f2278
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys/unix/thread.rs:108:17
  25:     0x7fab14688e86 - start_thread
  26:     0x7fab1470fd30 - clone3
  27:                0x0 - <unknown>
```

**Comment by KilianVounckx** [comment]
With [the new release](https://github.com/roc-lang/basic-cli/releases/download/0.4.0/aVzHiy6d7Xgl2qVh-0OuAx0CMQQZBfGfSAbgF63P_Sg.tar.gz) of the basic-cli package, the same error is given.

**Comment by ayazhafiz** [comment]
Needs updated repro

```
app "tty"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.3.2/tE4xS_zLdmmxmHwHih9kHWQ7fsXtJr7W7h3425-eZFk.tar.br" }
    imports [
        pf.Stdin,
        pf.Stdout,
        pf.Task.{ Task },
    ]
    provides [main] to pf

main : Task {} U32
main =
    world = initialWorld {}
    {} <- loop world |> Task.await

    Task.succeed {}

World : {}

initialWorld : {} -> World

update : World, List U8 -> [Continue World, Exit]

display : World -> Str

loop : World -> Task {} *
loop = \world ->
    {} <- display world |> Stdout.write |> Task.await
    event <- Stdin.bytes |> Task.await
    when update world event is
        Continue newWorld ->
            {} <- display newWorld |> Stdout.write |> Task.await
            loop newWorld

        Exit ->
            Task.succeed {}
```

**Comment by ayazhafiz** [comment]
@lukewilliamboswell any chance you know how to quickly change the above program to compile again?

**Comment by lukewilliamboswell** [comment]
> @lukewilliamboswell any chance you know how to quickly change the above program to compile again?

Yeah the Task.succeed needs to be Task.ok

**Comment by lukewilliamboswell** [comment]
@ayazhafiz  I updated to the following using latest basic-cli

```
app "tty"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.5.0/Cufzl36_SnJ4QbOoEmiJ5dIpUxBvdB3NEySvuH82Wio.tar.br" }
    imports [
        pf.Stdin,
        pf.Stdout,
        pf.Task.{ Task },
    ]
    provides [main] to pf

main : Task {} I32
main =
    world = initialWorld {}
    {} <- loop world |> Task.await

    Task.ok {}

World : {}

initialWorld : {} -> World

update : World, List U8 -> [Continue World, Exit]

display : World -> Str

loop : World -> Task {} *
loop = \world ->
    {} <- display world |> Stdout.write |> Task.await
    event <- Stdin.bytes |> Task.await
    when update world event is
        Continue newWorld ->
            {} <- display newWorld |> Stdout.write |> Task.await
            loop newWorld

        Exit ->
            Task.ok {}
```

It gives a different error message now:

```
% roc run Experiments/Test.roc
thread 'main' panicked at 'Error in alias analysis: error in module ModName("UserApp"), function definition FuncName("\x14\x00\x00\x00\x02\x00\x00\x009\x83\xff\xa4\x92\xe5\xbch"), definition of value binding ValueId(3): could not find func in module ModName("UserApp") with name FuncName("(\x00\x00\x00\x04\x00\x00\x009\x83\xff\xa4\x92\xe5\xbch")', crates/compiler/gen_llvm/src/llvm/build.rs:5122:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ayazhafiz** [comment]
Thank you!
