### ISSUE TITLE
macos aarch64 segfault when using `CodeModel::Default`

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#5658]
```
 failures:

---- cli_run::parse_letter_counts stdout ----
thread 'cli_run::parse_letter_counts' panicked at '
___________
Roc command failed with status ExitStatus(unix_wait_status(11)):

   
___________
', crates/cli/tests/cli_run.rs:119:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
   2: cli_run::cli_run::check_output_with_stdin
   3: cli_run::cli_run::test_roc_app
   4: core::ops::function::FnOnce::call_once
error: test failed, to rerun pass `-p roc_cli --test cli_run`
   5: serial_test::serial_code_lock::local_serial_core
   6: core::ops::function::FnOnce::call_once
   7: core::ops::function::FnOnce::call_once
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- cli_run::with_env_vars stdout ----
thread 'cli_run::with_env_vars' panicked at '
___________
Roc command failed with status ExitStatus(unix_wait_status(11)):

   🔨 Rebuilding platform...

___________
', crates/cli/tests/cli_run.rs:119:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
   2: cli_run::cli_run::check_output_with_stdin
   3: cli_run::cli_run::test_roc_app
   4: core::ops::function::FnOnce::call_once
   5: serial_test::serial_code_lock::local_serial_core
   6: core::ops::function::FnOnce::call_once
   7: core::ops::function::FnOnce::call_once
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    cli_run::parse_letter_counts
    cli_run::with_env_vars

test result: FAILED. 50 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 99.74s
```

In compiler/build/src/target.rs we currently use this hacky workaround:
```
#[cfg(all(target_arch = "aarch64", target_os = "macos"))]
let code_model = CodeModel::Large;
```

But this should work with `CodeModel::Default`

**Comment by Anton-4** [comment]
`cli_run::with_env_vars` also fails on linux aarch64 on a raspberry pi 4 8GB
