### ISSUE TITLE
An internal compiler expectation was broken.

### ISSUE THREAD

**Issue by Enkidatron** [roc-lang/roc#5665]
While getting started with a toy CLI app, I encountered an error that is "definitely a compiler bug." (Kudos for the helpful error message!)

Here is a complete program that triggers the bug, which is about as simplified as I can make it while still getting the error: 
```
app "bug"
    packages { pf: "../examples/cli/cli-platform/main.roc" }
    imports [pf.Task.{ Task }]
    provides [main] to pf

main : Task {} []
main = 
    _ <- Task.succeed "This Task.await is important" |> Task.await 
    commands : List Cmd
    commands = []

    matches : Matches  
    matches = List.walk commands NoMatches addMatch
    
    when matches is 
        NoMatches -> 
            Task.succeed {}
        OneMatch (Cmd f) -> 
            f {} 
        ManyMatches _ _ _ -> 
            _ <- Task.succeed "This Task.await is also important" |> Task.await 
            _ <- Task.succeed commands |> Task.await
            Task.succeed {}

Cmd : 
    [ Cmd ({} -> Task {} [])
    ]
Matches : 
    [ NoMatches
    , OneMatch Cmd
    , ManyMatches Cmd Cmd (List Cmd)
    ]

addMatch : Matches, Cmd -> Matches   
addMatch = \matches, cmd -> 
    when matches is 
        NoMatches -> OneMatch cmd 
        OneMatch first -> ManyMatches first cmd []
        ManyMatches first second rest -> ManyMatches first second (List.concat rest [cmd])
```

This file is `src/bug.roc`, inside the 2023-07-14 nightly roc build directory, which is why the path to the platform is a bit weird. 

This results in the following error: 
```
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread '<unnamed>' panicked at 'I thought a non-nullable-unwrapped variant for a lambda set was impossible: how could such a lambda set be created without a base case?', crates/compiler/mono/src/layout.rs:1619:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Running with RUST_BACKTRACE=1 does not provide any new information, and RUST_BACKTRACE=full provides: 
```
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread '<unnamed>' panicked at 'I thought a non-nullable-unwrapped variant for a lambda set was impossible: how could such a lambda set be created without a base case?', crates/compiler/mono/src/layout.rs:1619:61
stack backtrace:
   0:     0x55d935a0070e - <unknown>
   1:     0x55d934beeefe - <unknown>
   2:     0x55d9359fa4a5 - <unknown>
   3:     0x55d935a004e5 - <unknown>
   4:     0x55d935a01eaf - <unknown>
   5:     0x55d935a01c24 - <unknown>
   6:     0x55d935a02533 - <unknown>
   7:     0x55d935a022b5 - <unknown>
   8:     0x55d935a00c3c - <unknown>
   9:     0x55d935a02022 - <unknown>
  10:     0x55d934a3ab83 - <unknown>
  11:     0x55d93556fa3c - <unknown>
  12:     0x55d9355202f2 - <unknown>
  13:     0x55d93550bc23 - <unknown>
  14:     0x55d93552c19b - <unknown>
  15:     0x55d93552bd45 - <unknown>
  16:     0x55d935546227 - <unknown>
  17:     0x55d93554a47c - <unknown>
  18:     0x55d935545739 - <unknown>
  19:     0x55d93552016e - <unknown>
  20:     0x55d935516f6a - <unknown>
  21:     0x55d93551663c - <unknown>
  22:     0x55d93545a8a2 - <unknown>
  23:     0x55d9353e2cc1 - <unknown>
  24:     0x55d9353dc8ce - <unknown>
  25:     0x55d9353e208d - <unknown>
  26:     0x55d935a07aa5 - <unknown>
  27:     0x7f684d1e0b43 - <unknown>
  28:     0x7f684d272a00 - <unknown>
  29:                0x0 - <unknown>
```

I am on Windows, using WSL2 with Ubuntu.

**Comment by Anton-4** [comment]
Thanks for this nice issue report @Enkidatron!
Note that if you're working on a CLI app, [basic-cli](https://github.com/roc-lang/basic-cli) has more features, compared to examples/cli/cli-platform.

**Comment by skyqrose** [comment]
Probably the same as https://github.com/roc-lang/roc/issues/5817 . Closing as a duplicate.
