### ISSUE TITLE
repl string interpolation panic

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#5708]
From zulip:
> I was going through the tutorial and accidentally misnamed the greeting variable to greetings, and so when I tried to do the string interpolation it failed and killed the repl.

```
» "\(greeting) there, \(audience)!"
"\xe8\x9d\t\x05\x01"
thread 'main' panicked at 'Roc hit an error', crates/repl_cli/src/cli_gen.rs:142:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by folkertdev** [comment]
this one is weird. You need two invalid variables for this to fail it seems

```
» "$(x) $(y)"
LookupNotInScope { loc_name: @69-70 Ident(IdentStr { string: "x" }), suggestion_options: {"U8", "F64", "Integer", "Box", "Nat", "Frac", "Decimal", "Dict", "Result", "FloatingPoint", "Eq", "KeyValWalker", "Decoding", "Unsigned8", "Natural", "Signed16", "Encoding", "InspectFormatter", "Int", "Num", "EncoderFormatting", "I32", "Hash", "Inspector", "Unsigned16", "Unsigned128", "Unsigned64", "Encoder", "replOutput", "I16", "I8", "Binary32", "DecoderFormatting", "I128", "Signed8", "Str", "Dec", "Binary64", "DecodeError", "I64", "U64", "F32", "DecodeResult", "ElemWalker", "Decoder", "Signed64", "Inspect", "U16", "Set", "Hasher", "Ok", "Unsigned32", "Signed128", "List", "Signed32", "Err", "U32", "Bool", "U128"}, underscored_suggestion_region: None }
thread 'main' panicked at 'Roc hit an error', crates/repl_cli/src/cli_gen.rs:125:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
