### ISSUE TITLE
expect prints wrong value for Result

### ISSUE THREAD

**Issue by adomurad** [roc-lang/roc#5727]
When using expect to check a `Result` type which is an `Err`, Roc prints the same "expected" value twice - instead of printing the "actual" value and the "expected" value:
```elm
expect
    actual = Err TestError
    expected = Ok { ownerName: "a" }

    actual == expected
```

Output:
```elm
Running tests…

────────────────────────────────────────────────────────────────────────────────
── EXPECT FAILED ───────────────────────────────────────────────── ./tests.roc ─

This expectation failed:

22│>  expect
23│>      actual = Err TestError
24│>      expected = Ok { ownerName: "a" }
25│>
26│>      actual == expected

When it failed, these variables had these values:

actual : [
    Err [TestError],
    Ok { ownerName : Str },
]
actual = Ok { ownerName: "a" }

expected : [
    Err [TestError],
    Ok { ownerName : Str },
]
expected = Ok { ownerName: "a" }



1 failed and 0 passed in 499 ms.
```

"actual" and "expected" are the same in the terminal output:
```elm
actual = Ok { ownerName: "a" }
expected = Ok { ownerName: "a" }
```

I would expect it to be:
```elm
actual = Err TestError
expected = Ok { ownerName: "a" }
```

**Comment by adomurad** [comment]
With latest roc build from the main branch (2bd998a21525128c93fcd45126ccd5ab557ecdf7) there is a runtime error (instead of wrong print):
```
thread 'main' panicked at 'misaligned pointer dereference: address must be a multiple of 0x8 but is 0x1178c503c', crates/repl_expect/src/app.rs:57:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'panic in a function that cannot unwind', library/core/src/panicking.rs:126:5
stack backtrace:
   0:        0x111d848d6 - std::backtrace_rs::backtrace::libunwind::trace::h0a908cd09b5a35f9
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x111d848d6 - std::backtrace_rs::backtrace::trace_unsynchronized::hc0e7d5d16c14a788
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x111d848d6 - std::sys_common::backtrace::_print_fmt::hcf9ca6805c7eb2fe
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x111d848d6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hae51cb91d407e2ef
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x111da9b3b - core::fmt::write::h746bc0969202388b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:1254:17
   5:        0x111d7f26c - std::io::Write::write_fmt::h4098c2c7437a0bd7
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/io/mod.rs:1698:15
   6:        0x111d846aa - std::sys_common::backtrace::_print::he6d3aef1f6c73e2d
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:47:5
   7:        0x111d846aa - std::sys_common::backtrace::print::h8360bf0158e89b36
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:34:9
   8:        0x111d860f0 - std::panicking::default_hook::{{closure}}::hedf04c568eb6e0bc
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:269:22
   9:        0x111d85ea0 - std::panicking::default_hook::h62889b2c29e2347d
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:288:9
  10:        0x111d8664a - std::panicking::rust_panic_with_hook::h22edd02828aff274
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:691:13
  11:        0x111d86523 - std::panicking::begin_panic_handler::{{closure}}::h6895f44a9b7e2caa
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:580:13
  12:        0x111d84d19 - std::sys_common::backtrace::__rust_end_short_backtrace::h013519e9b77978c5
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
  13:        0x111d862ad - rust_begin_unwind
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
  14:        0x111e26503 - core::panicking::panic_nounwind_fmt::h7eff05c2c44c99c9
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:96:14
  15:        0x111e265ab - core::panicking::panic_nounwind::h57629dda55159143
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:126:5
  16:        0x111e26715 - core::panicking::panic_cannot_unwind::h555ec587bc15578c
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:188:5
  17:        0x10dd1339e - <roc_repl_expect::app::ExpectMemory as roc_repl_eval::ReplAppMemory>::deref_str::h56914ad7300d194d
                               at /Users/10001784ergo.com/Work/ROC/roc/crates/repl_expect/src/app.rs:47:5
  18:        0x10dd26b56 - roc_repl_eval::eval::addr_to_ast::hd9f6deb19158b86f
                               at /Users/10001784ergo.com/Work/ROC/roc/crates/repl_eval/src/eval.rs:633:26
  19:        0x10dd283d4 - roc_repl_eval::eval::expr_of_tag::h6fb4192c41ba048a
                               at /Users/10001784ergo.com/Work/ROC/roc/crates/repl_eval/src/eval.rs:304:20
  20:        0x10dd2648b - roc_repl_eval::eval::addr_to_ast::hd9f6deb19158b86f
                               at /Users/10001784ergo.com/Work/ROC/roc/crates/repl_eval/src/eval.rs:718:13
  21:        0x10dd2e66c - roc_repl_eval::eval::jit_to_ast_help::{{closure}}::h143c4757e4314298
                               at /Users/10001784ergo.com/Work/ROC/roc/crates/repl_eval/src/eval.rs:502:21
  22:        0x10dd070a9 - <roc_repl_expect::app::ExpectReplApp as roc_repl_eval::ReplApp>::call_function_dynamic_size::h39652136fb98f191
                               at /Users/10001784ergo.com/Work/ROC/roc/crates/repl_expect/src/app.rs:144:9
  23:        0x10dd2d8dd - roc_repl_eval::eval::jit_to_ast_help::h6ed74be37327319f
                               at /Users/10001784ergo.com/Work/ROC/roc/crates/repl_eval/src/eval.rs:498:13
  24:        0x10dd218f7 - roc_repl_eval::eval::jit_to_ast::h2e39d82047427f4a
                               at /Users/10001784ergo.com/Work/ROC/roc/crates/repl_eval/src/eval.rs:70:13
  25:        0x10dd057b2 - roc_repl_expect::get_values::hf3da2fdbbd3beca3
                               at /Users/10001784ergo.com/Work/ROC/roc/crates/repl_expect/src/lib.rs:71:13
  26:        0x10dceffde - roc_repl_expect::run::render_expect_failure::h28b669e40fe854ee
                               at /Users/10001784ergo.com/Work/ROC/roc/crates/repl_expect/src/run.rs:574:44
  27:        0x10dcee9a1 - roc_repl_expect::run::run_expect_pure::h88a3928cb5510c9e
                               at /Users/10001784ergo.com/Work/ROC/roc/crates/repl_expect/src/run.rs:276:27
  28:        0x10dcf07b1 - roc_repl_expect::run::run_expects_with_memory::h3fffcd257a61f395
                               at /Users/10001784ergo.com/Work/ROC/roc/crates/repl_expect/src/run.rs:219:22
  29:        0x10dcef914 - roc_repl_expect::run::run_toplevel_expects::h8409058586480e4a
                               at /Users/10001784ergo.com/Work/ROC/roc/crates/repl_expect/src/run.rs:169:5
  30:        0x10dcf625e - roc_cli::test::hc37127c70b3a48f7
                               at /Users/10001784ergo.com/Work/ROC/roc/crates/cli/src/lib.rs:492:28
  31:        0x10db2b727 - roc::main::hc6ae04b433ac580c
                               at /Users/10001784ergo.com/Work/ROC/roc/crates/cli/src/main.rs:78:17
  32:        0x10db30dee - core::ops::function::FnOnce::call_once::h09048eab517ed8a9
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  33:        0x10db2e651 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4d18968fe67ea709
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:134:18
  34:        0x10db30984 - std::rt::lang_start::{{closure}}::h0392943000061727
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:166:18
  35:        0x111d77f22 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h4d31ab51fa4afcb3
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:287:13
  36:        0x111d77f22 - std::panicking::try::do_call::h29870f82be4076a9
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  37:        0x111d77f22 - std::panicking::try::h5d28bc317561a503
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  38:        0x111d77f22 - std::panic::catch_unwind::hcec89f8ee3292969
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  39:        0x111d77f22 - std::rt::lang_start_internal::{{closure}}::h8aa82e7014dd312d
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:48
  40:        0x111d77f22 - std::panicking::try::do_call::hd2313fc9b34e2403
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  41:        0x111d77f22 - std::panicking::try::hc5bb97f422b5bdd9
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  42:        0x111d77f22 - std::panic::catch_unwind::h8202c14898aaf8af
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  43:        0x111d77f22 - std::rt::lang_start_internal::h36134e47b0b0d769
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:20
  44:        0x10db30957 - std::rt::lang_start::h46ba6e92f0f1e174
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:165:17
  45:        0x10db2e638 - _main
  46:     0x7ff8012a741f - <unknown>
thread caused non-unwinding panic. aborting.
[1]    64862 abort      ./roc test ../../../roc-test/main.roc
```

**Comment by CrepeGoat** [comment]
I think I have another example for this same problem:

```coffee
expect
    result = solve 0
    exptResult = 1
    result == Ok exptResult

solve : U8 -> Result U32 []
solve = \x -> Ok 0
```

result:
```
$ roc test

Running tests…

────────────────────────────────────────────────────────────────────────────────
── EXPECT FAILED ──────────────────────────────────────────────────── main.roc ─

This expectation failed:

21│>  expect
22│>      result = solve 0
23│>      exptResult = 1
24│>      result == Ok exptResult

When it failed, these variables had these values:

result : Result U32 []
result = Ok 0

exptResult : Num *
exptResult = -6148914694099828735



1 failed and 0 passed in 458 ms.
```

the notable line being `exptResult = -6148914694099828735`
