### ISSUE TITLE
A Wasm instruction at file offset 0x27969 tried to access memory... on zig-11-llvm-16 branch

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#5860]
For command `nix develop -c cargo test-gen-llvm-wasm --locked --release`:
```
---- gen_primitives::deriv_pow stdout ----
thread 'gen_primitives::deriv_pow' panicked at 'Wasm test failed: ERROR: A Wasm instruction at file offset 0x2798a tried to access memory at 0x80000008 but the maximum address is 0x3ffff
-------------------
func[1294]  test_wrapper.command_export
  address  0247fc
  args     
  stack    []
-------------------
func[693]  test_wrapper
  address  022331
  args     
  locals   0: I32(223136), 1: I32(16), 2: I32(223120), 3: I32(223176), 4: I32(3), 5: I32(120), 6: I32(0), 7: I32(-2130706432), 8: I32(223224), 9: I32(16), 10: I32(223240), 11: I32(3), 12: I32(120), 13: I32(0), 14: I32(-2130706432), 15: I32(3), 16: I32(2), 17: I32(255), 18: I32(3), 19: I32(255), 20: I32(2), 21: I32(0), 22: I32(1), 23: I32(0), 24: I32(0), 25: I32(0), 26: I32(0), 27: I32(0), 28: I32(0), 29: I64(0), 30: I64(0), 31: I64(0), 32: I64(0), 33: I32(0), 34: I32(0), 35: I32(0), 36: I32(223272), 37: I32(1), 38: I32(223272), 39: I32(0), 40: I32(0), 41: I32(0), 42: I32(0), 43: I32(0), 44: I32(0), 45: I32(0), 46: I32(0), 47: I32(0), 48: I32(0), 49: I32(0), 50: I32(0), 51: I32(0), 52: I32(0), 53: I32(0), 54: I32(0), 55: I32(0), 56: I32(0), 57: I32(0), 58: I32(0), 59: I32(0), 60: I32(0), 61: I32(0), 62: I32(0), 63: I32(0), 64: I32(0), 65: I32(0), 66: I32(0), 67: I32(0), 68: I32(0), 69: I32(0), 70: I32(0), 71: I32(0), 72: I32(0), 73: I32(0), 74: I64(0), 75: I32(223272), 76: I64(0), 77: I32(0), 78: I32(0), 79: I32(0), 80: I32(0)
  stack    []
-------------------
func[689]  #UserApp_count_2a94b68b634c4fcf8ebd3afdef20854cc2d163b7945c72cedceea54c5591789e
  address  021acb
  args     0: I32(223272)
  locals   1: I32(223272), 2: I32(223272), 3: I32(1), 4: I32(-1), 5: I32(0), 6: I32(255), 7: I32(0), 8: I32(2), 9: I32(0), 10: I32(0), 11: I32(0), 12: I32(0), 13: I32(0), 14: I32(0), 15: I32(0), 16: I32(0), 17: I32(0), 18: I32(0), 19: I32(0), 20: I32(0), 21: I32(0), 22: I32(0), 23: I32(0), 24: I64(0), 25: I64(0), 26: I32(0), 27: I32(0), 28: I32(0), 29: I32(0), 30: I32(0), 31: I64(0), 32: I32(0), 33: I32(0), 34: I32(0), 35: I32(0), 36: I32(0), 37: I32(0), 38: I32(0), 39: I32(0), 40: I32(0), 41: I32(3), 42: I32(0), 43: I32(0), 44: I32(0), 45: I32(223272), 46: I32(223176), 47: I32(223224), 48: I32(-4), 49: I32(223268), 50: I32(-2147483648), 51: I32(-2147483648), 52: I32(-2147483648), 53: I32(-2147483648), 54: I32(1), 55: I32(1), 56: I32(1), 57: I32(0), 58: I32(0), 59: I32(0), 60: I32(0), 61: I32(0), 62: I32(0), 63: I64(0), 64: I64(0), 65: I64(0), 66: I32(0), 67: I64(0), 68: I32(0), 69: I32(0), 70: I32(0), 71: I32(0), 72: I32(0), 73: I32(0), 74: I32(0), 75: I64(0)
  stack    []
-------------------
func[687]  roc_builtins.utils.free_rc_ptr
  address  0218c3
  args     0: I32(223268)
  locals   1: I32(0), 2: I32(223268), 3: I32(0), 4: I32(0), 5: I32(1), 6: I32(0), 7: I32(4)
  stack    []
-------------------
func[640]  roc_dealloc
  address  01dea7
  args     0: I32(223268), 1: I32(4)
  locals   2: I32(223120), 3: I32(32), 4: I32(223088), 5: I32(0), 6: I32(0), 7: I32(0), 8: I32(0), 9: I32(0), 10: I32(0), 11: I32(1), 12: I32(0), 13: I32(0), 14: I32(0), 15: I32(0), 16: I32(0), 17: I32(0), 18: I32(0), 19: I32(0), 20: I32(0), 21: I32(0), 22: I32(0), 23: I32(0), 24: I32(0), 25: I32(0), 26: I32(0), 27: I32(0), 28: I32(0), 29: I32(0), 30: I32(0), 31: I32(0), 32: I32(0), 33: I32(0), 34: I32(0), 35: I32(0), 36: I32(0), 37: I32(0), 38: I32(0), 39: I32(0), 40: I32(0), 41: I32(0), 42: I32(0), 43: I32(0), 44: I32(0), 45: I32(0), 46: I32(0), 47: I32(0), 48: I32(0), 49: I32(0), 50: I32(0), 51: I32(0), 52: I32(0), 53: I32(0), 54: I32(0), 55: I32(0), 56: I32(0), 57: I32(0), 58: I32(0), 59: I32(0), 60: I32(0), 61: I32(0), 62: I32(0), 63: I32(0), 64: I32(0), 65: I32(0), 66: I32(0), 67: I32(0), 68: I32(0), 69: I32(0), 70: I32(0), 71: I32(0), 72: I32(0), 73: I32(0), 74: I32(0), 75: I32(0), 76: I32(0), 77: I32(0), 78: I32(0), 79: I32(0), 80: I32(0), 81: I32(0), 82: I32(0), 83: I32(0), 84: I32(0), 85: I32(0), 86: I32(0), 87: I32(0), 88: I32(0), 89: I32(0), 90: I32(0), 91: I32(0), 92: I32(0), 93: I32(0), 94: I32(0), 95: I32(0), 96: I32(0), 97: I32(0), 98: I32(0), 99: I32(0), 100: I32(0), 101: I32(0), 102: I32(0), 103: I32(0), 104: I32(0), 105: I32(0), 106: I32(0), 107: I32(0), 108: I32(0), 109: I32(0), 110: I32(0), 111: I32(0), 112: I32(0), 113: I32(0), 114: I32(0), 115: I32(0), 116: I32(0), 117: I32(0), 118: I32(0), 119: I32(0), 120: I32(0), 121: I32(0), 122: I32(0), 123: I32(0), 124: I32(0), 125: I32(0), 126: I32(0), 127: I32(0), 128: I32(0), 129: I32(0), 130: I32(0), 131: I32(0), 132: I32(0), 133: I32(0), 134: I32(0), 135: I32(0), 136: I32(0), 137: I32(0), 138: I32(0), 139: I32(0), 140: I32(0), 141: I32(0), 142: I32(0), 143: I32(0), 144: I32(0), 145: I32(0), 146: I32(0), 147: I32(0), 148: I32(0), 149: I32(0), 150: I32(0), 151: I32(0), 152: I32(0), 153: I32(0), 154: I32(0), 155: I32(0), 156: I32(0), 157: I32(0), 158: I32(0), 159: I32(0), 160: I32(0), 161: I32(0), 162: I32(0), 163: I32(0), 164: I32(0), 165: I32(0), 166: I32(0), 167: I32(0), 168: I32(0), 169: I32(0), 170: I32(0), 171: I32(0), 172: I32(0), 173: I32(0), 174: I32(0), 175: I32(0), 176: I32(0), 177: I32(0), 178: I32(0), 179: I32(0), 180: I32(0), 181: I32(0), 182: I32(0), 183: I32(0), 184: I32(0), 185: I32(0), 186: I32(0), 187: I32(0), 188: I32(0), 189: I32(0), 190: I32(0), 191: I32(0), 192: I32(0), 193: I32(0), 194: I32(0), 195: I32(0), 196: I32(0), 197: I32(0), 198: I32(0), 199: I32(0), 200: I32(0), 201: I32(0), 202: I32(0), 203: I32(0), 204: I32(0), 205: I32(0), 206: I32(0), 207: I32(0), 208: I32(0), 209: I32(0), 210: I32(0), 211: I32(0), 212: I32(0), 213: I32(0), 214: I32(0), 215: I32(0), 216: I32(0), 217: I32(0), 218: I32(0), 219: I32(0), 220: I32(0), 221: I32(0), 222: I32(0), 223: I32(0), 224: I32(0), 225: I32(0), 226: I32(0), 227: I32(0), 228: I32(0), 229: I32(0), 230: I32(0), 231: I32(0), 232: I32(0), 233: I32(0), 234: I32(0), 235: I32(0), 236: I32(0), 237: I32(0), 238: I32(0), 239: I32(0), 240: I32(0), 241: I32(0), 242: I32(0), 243: I32(0), 244: I32(0), 245: I32(223268), 246: I32(0), 247: I32(0)
  stack    []
-------------------
func[675]  free
  address  0212e8
  args     0: I32(223264)
  locals   1: I32(223264), 2: I32(0), 3: I32(0)
  stack    []
-------------------
', crates/compiler/test_gen/src/gen_primitives.rs:2304:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   2: core::ops::function::FnOnce::call_once
   3: core::ops::function::FnOnce::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
```
failures:
    gen_compare::compare_nullable_recursive_union_same_content
    gen_compare::compare_recursive_union_same_content
    gen_compare::eq_expr
    gen_compare::eq_linked_list
    gen_compare::eq_linked_list_false
    gen_primitives::binary_tree_double_pattern_match
    gen_primitives::deriv_pow
    gen_primitives::linked_list_double_pattern_match
    gen_primitives::linked_list_len_1
    gen_primitives::linked_list_len_3
    gen_primitives::linked_list_len_twice_1
    gen_primitives::linked_list_map
    gen_primitives::linked_list_sum_num_a
    gen_primitives::multiple_increment
    gen_primitives::nested_switch
    gen_primitives::nullable_eval_cfold
    gen_primitives::recursive_lambda_set_resolved_only_upon_specialization
    gen_primitives::reset_recursive_type_wraps_in_named_type
    gen_primitives::switch_fuse_rc_exhaustive
    gen_primitives::switch_fuse_rc_non_exhaustive
    gen_str::nested_recursive_literal
    gen_tags::issue_2365_monomorphize_tag_with_non_empty_ext_var_wrapped
    gen_tags::issue_2365_monomorphize_tag_with_non_empty_ext_var_wrapped_nested
    gen_tags::nullable_wrapped_eq_issue_5434

test result: FAILED. 1316 passed; 24 failed; 20 ignored; 0 measured; 0 filtered out; finished in 35.46s
```

Similar old issue in this merged PR: https://github.com/roc-lang/roc/pull/5312
[Discussion about a similar old issue on zulip](https://roc.zulipchat.com/#narrow/stream/231635-compiler-development-.28private.29/topic/Wasm.20Interpreter/near/314334266).

This failure has only been seen (and only been tested) on macos aarch64.

**Comment by folkertdev** [comment]
fixed by https://github.com/roc-lang/roc/pull/5851/commits/1b548cf75ac9099e3e4263a7a832b2121c7c9cb9. We did not propagate the alignment correctly, and also did not use the alignment to calculate the offset from a pointer to the data

**Comment by Anton-4** [comment]
Thanks @folkertdev :tada:
