### ISSUE TITLE
glue_cli_run::nullable_wrapped + nullable_unwrapped segmentation fault on linux

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#5924]
```
---- glue_cli_run::nullable_unwrapped stdout ----
thread 'glue_cli_run::nullable_unwrapped' panicked at 'bad status Out { cmd_str: "/home/small-ci-user/actions-runner/_work/roc/roc/target/release/roc /home/small-ci-user/actions-runner/_work/roc/roc/crates/glue/tests/fixtures/nullable-unwrapped/app.roc", stdout: "tag_union was: StrConsList::Cons(\"World!\", StrConsList::Cons(\"Hello \", StrConsList::Nil))\n`Cons \"small str\" Nil` is: StrConsList::Cons(\"small str\", StrConsList::Nil)\n`Nil` is: StrConsList::Nil\n", stderr: "🔨 Rebuilding platform...\n", status: ExitStatus(unix_wait_status(35584)) }', crates/glue/tests/test_glue_cli.rs:243:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   2: test_glue_cli::glue_cli_run::run_app
   3: core::ops::function::FnOnce::call_once
   4: core::ops::function::FnOnce::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- glue_cli_run::nullable_wrapped stdout ----
thread 'glue_cli_run::nullable_wrapped' panicked at 'bad status Out { cmd_str: "/home/small-ci-user/actions-runner/_work/roc/roc/target/release/roc /home/small-ci-user/actions-runner/_work/roc/roc/crates/glue/tests/fixtures/nullable-wrapped/app.roc", stdout: "tag_union was: StrFingerTree::More(\"foo\", StrFingerTree::More(\"bar\", StrFingerTree::Empty))\n`More \"small str\" (Single \"other str\")` is: StrFingerTree::More(\"small str\", StrFingerTree::Single(\"other str\"))\n`More \"small str\" Empty` is: StrFingerTree::More(\"small str\", StrFingerTree::Empty)\n`Single \"small str\"` is: StrFingerTree::Single(\"small str\")\n`Empty` is: StrFingerTree::Empty\n", stderr: "🔨 Rebuilding platform...\n", status: ExitStatus(unix_wait_status(35584)) }', crates/glue/tests/test_glue_cli.rs:243:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   2: test_glue_cli::glue_cli_run::run_app
   3: core::ops::function::FnOnce::call_once
   4: core::ops::function::FnOnce::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    glue_cli_run::nullable_unwrapped
    glue_cli_run::nullable_wrapped

test result: FAILED. 14 passed; 2 failed; 1 ignored; 0 measured; 0 filtered out; finished in 23.87s

error: test failed, to rerun pass `-p roc_glue --test test_glue_cli`
```
Valgrind output:
```
valgrind ./crates/glue/tests/fixtures/nullable-wrapped/app
==708913== Memcheck, a memory error detector
==708913== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==708913== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==708913== Command: ./crates/glue/tests/fixtures/nullable-wrapped/app
==708913== 
tag_union was: StrFingerTree::More("foo", StrFingerTree::More("bar", StrFingerTree::Empty))
`More "small str" (Single "other str")` is: StrFingerTree::More("small str", StrFingerTree::Single("other str"))
`More "small str" Empty` is: StrFingerTree::More("small str", StrFingerTree::Empty)
`Single "small str"` is: StrFingerTree::Single("small str")
`Empty` is: StrFingerTree::Empty
==708913== Can't extend stack to 0x485d138 during signal delivery for thread 1:
==708913==   no stack segment
==708913== 
==708913== Process terminating with default action of signal 11 (SIGSEGV)
==708913==  Access not within mapped region at address 0x485D138
==708913==    at 0x249024: ??? (in /home/small-ci-user/gitrepos/roc2/roc/crates/glue/tests/fixtures/nullable-wrapped/app)
==708913==    by 0x48D1494: __run_exit_handlers (exit.c:113)
==708913==    by 0x48D160F: exit (exit.c:143)
==708913==    by 0x1D7266: ??? (in /home/small-ci-user/gitrepos/roc2/roc/crates/glue/tests/fixtures/nullable-wrapped/app)
==708913==    by 0x1: ???
==708913==    by 0x1CC95E: ??? (in /home/small-ci-user/gitrepos/roc2/roc/crates/glue/tests/fixtures/nullable-wrapped/app)
==708913==  If you believe this happened as a result of a stack
==708913==  overflow in your program's main thread (unlikely but
==708913==  possible), you can try to increase the size of the
==708913==  main thread stack using the --main-stacksize= flag.
==708913==  The main thread stack size used in this run was 8388608.
==708913== 
==708913== HEAP SUMMARY:
==708913==     in use at exit: 600 bytes in 15 blocks
==708913==   total heap usage: 27 allocs, 12 frees, 3,833 bytes allocated
==708913== 
==708913== LEAK SUMMARY:
==708913==    definitely lost: 400 bytes in 10 blocks
==708913==    indirectly lost: 200 bytes in 5 blocks
==708913==      possibly lost: 0 bytes in 0 blocks
==708913==    still reachable: 0 bytes in 0 blocks
==708913==         suppressed: 0 bytes in 0 blocks
==708913== Rerun with --leak-check=full to see details of leaked memory
==708913== 
==708913== For lists of detected and suppressed errors, rerun with: -s
==708913== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)
```
This seems the important part of the valgrind output:
```
 Can't extend stack to 0x485d138 during signal delivery for thread 1:
   no stack segment
```
We discovered this error in https://github.com/roc-lang/roc/pull/5557 but it did not originate there. It could have been introduced earlier or have been there from the start.

**Comment by Anton-4** [comment]
Reverting https://github.com/roc-lang/roc/commit/d0e1da40ac3f4dc3a247e451199f81b70bf725a3 stops the `nullable_wrapped` and `nullable_unwrapped` from segfaulting but does make (only) `union_with_padding` segfault.

**Comment by Anton-4** [comment]
Some potentially useful information in the things linked [here](https://www.reddit.com/r/rust/comments/e9nilt/segfault_when_using_bytes_tokio_and_jemalloc_who/).

**Comment by Anton-4** [comment]
Given the fickleness I've seen of this error in basic-cli, I wonder if this is triggered by the compiled platform having a specific size.

**Comment by Anton-4** [comment]
I have assembled 4 good/bad versions of executables in the archive below.
option+closure are from the same commit, and nullable_wrapped+nullable_unwrapped are from the same commit.
The difference in source code for good vs bad for every case is one extra `eprintln!("")`, adding that "fixes" the issue.
If we find what all bad executables have in common we should be able to figure out the cause.

[glue_comparison.tar.gz](https://github.com/roc-lang/roc/files/13822586/glue_comparison.tar.gz)

Also linking some earlier [zulip discussion](https://roc.zulipchat.com/#narrow/stream/395097-compiler-development/topic/CI/near/410976235).

**Comment by Anton-4** [comment]
For record keeping; we know suspect this has the same root cause as #6121.

**Comment by bhansconnect** [comment]
I took a look at this again scanning the binaries reproduced locally. I was able to get the issue to go away, but only with another arbitrary fix (changed some alignment in the surgical linker). Nothing that I am confident is a proper fix.

I think I need to find a case where this is hit with the linux legacy linker. With the surgical linker it is hard to have confidence the linker is correct. As such, it is hard to verify what the underlying issue is. Also the surgical linker doesn't handle debug info so everything is harder to debug. Seeing this issue again on macos would also be fine, but linux debugging tools are better than macos.

**Comment by bhansconnect** [comment]
Just a note: I am starting to wonder if this is now a surgical linker only bug. I know way back when I saw the bug on macos. But every failure in recent months seems to be on linux with the surgical linker. So this may be something where eventually we have to really dig into the surgical linker to understand what might be going on here.

Still really hoping to see it with the legacy linker again. That probably will make it a lot more debuggable.
