### ISSUE TITLE
Compiler crash on invalid tagged union syntax

### ISSUE THREAD

**Issue by lsculv** [roc-lang/roc#6060]
## Description
The following (incorrect?) roc code causes a compiler crash:
```
app "main"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.5.0/Cufzl36_SnJ4QbOoEmiJ5dIpUxBvdB3NEySvuH82Wio.tar.br" }
    imports [pf.Stdout]
    provides [main] to pf

main = 
    Stdout.line "Compiler error!"

Node node = [One node, Many List node] # The offending line
```

I'm not actually sure if this is invalid syntax (although I suspect it is invalid). Either way this causes the compiler to crash and hang.

## Full Backtrace
```shell
$ RUST_BACKTRACE=full roc build 
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread '<unnamed>' panicked at 'destructures cannot participate in a recursive group; it's always a type error', crates/compiler/can/src/def.rs:1654:29
stack backtrace:
   0:     0x55fcb31ae081 - std::backtrace_rs::backtrace::libunwind::trace::h782cc21a5acaf6cb
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55fcb31ae081 - std::backtrace_rs::backtrace::trace_unsynchronized::hc579eb24ab204515
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55fcb31ae081 - std::sys_common::backtrace::_print_fmt::h7223525cfdbacda2
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55fcb31ae081 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbd7d55b7108d2ab8
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55fcb31dcd4f - core::fmt::rt::Argument::fmt::hb4f4a02b9bd9dd49
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/fmt/rt.rs:138:9
   5:     0x55fcb31dcd4f - core::fmt::write::h6d54cd7c9e155ec5
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/fmt/mod.rs:1094:21
   6:     0x55fcb31a96b1 - std::io::Write::write_fmt::h6a453a71c692f63b
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/io/mod.rs:1713:15
   7:     0x55fcb31ade95 - std::sys_common::backtrace::_print::h1cbaa8b42678f928
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55fcb31ade95 - std::sys_common::backtrace::print::h4ddf81241a51b337
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55fcb31af597 - std::panicking::default_hook::{{closure}}::hff91f1f484ade5cd
  10:     0x55fcb31af384 - std::panicking::default_hook::h21f14afd59f7aef9
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:288:9
  11:     0x55fcb31afa4c - std::panicking::rust_panic_with_hook::h45f66047b14c555c
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:705:13
  12:     0x55fcb31af901 - std::panicking::begin_panic_handler::{{closure}}::h49d1a88ef0908eb4
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:595:13
  13:     0x55fcb31ae4b6 - std::sys_common::backtrace::__rust_end_short_backtrace::hccebf9e57f8cc425
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:151:18
  14:     0x55fcb31af692 - rust_begin_unwind
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
  15:     0x55fcaebe3b83 - core::panicking::panic_fmt::h54ec9d0e3180a83d
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
  16:     0x55fcb2d3f063 - sort_can_defs_new
                               at /home/lucas/Programming/roc/crates/compiler/can/src/def.rs:1654:29
  17:     0x55fcb2d3f063 - canonicalize_module_defs
                               at /home/lucas/Programming/roc/crates/compiler/can/src/module.rs:436:42
  18:     0x55fcb17ee383 - canonicalize_and_constrain
                               at /home/lucas/Programming/roc/crates/compiler/load_internal/src/file.rs:5282:25
  19:     0x55fcb17f9ed7 - roc_load_internal::file::run_task::hd79a4f670f5ad7dd
                               at /home/lucas/Programming/roc/crates/compiler/load_internal/src/file.rs:6315:31
  20:     0x55fcb17c71ce - worker_task
                               at /home/lucas/Programming/roc/crates/compiler/load_internal/src/file.rs:2042:34
  21:     0x55fcb1800bba - roc_load_internal::file::load_multi_threaded::{{closure}}::{{closure}}::h13d30c42bc099db2
                               at /home/lucas/Programming/roc/crates/compiler/load_internal/src/file.rs:1782:25
  22:     0x55fcb1839f62 - crossbeam_utils::thread::ScopedThreadBuilder::spawn::{{closure}}::he17797fde00caec5
                               at /home/lucas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/crossbeam-utils-0.8.16/src/thread.rs:440:31
  23:     0x55fcb17a0d17 - core::ops::function::FnOnce::call_once{{vtable.shim}}::he45a094af9edcfeb
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
  24:     0x55fcb18472c3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h281fa5a86c37b2c9
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/alloc/src/boxed.rs:1985:9
  25:     0x55fcb187a937 - __rust_begin_short_backtrace<alloc::boxed::Box<(dyn core::ops::function::FnOnce<(), Output=()> + core::marker::Send), alloc::alloc::Global>, ()>
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:135:18
  26:     0x55fcb181aa37 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h4943310787f6fbf8
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/thread/mod.rs:529:17
  27:     0x55fcb187adc7 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::he0472834667fef0e
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panic/unwind_safe.rs:271:9
  28:     0x55fcb1848061 - do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<alloc::boxed::Box<(dyn core::ops::function::FnOnce<(), Output=()> + core::marker::Send), alloc::alloc::Global>, ()>>, ()>
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:500:40
  29:     0x55fcb184816b - __rust_try
  30:     0x55fcb1847f9a - try<(), core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<alloc::boxed::Box<(dyn core::ops::function::FnOnce<(), Output=()> + core::marker::Send), alloc::alloc::Global>, ()>>>
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:464:19
  31:     0x55fcb181a8a9 - catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<alloc::boxed::Box<(dyn core::ops::function::FnOnce<(), Output=()> + core::marker::Send), alloc::alloc::Global>, ()>>, ()>
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panic.rs:142:14
  32:     0x55fcb181a8a9 - {closure#1}<alloc::boxed::Box<(dyn core::ops::function::FnOnce<(), Output=()> + core::marker::Send), alloc::alloc::Global>, ()>
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/thread/mod.rs:528:30
  33:     0x55fcb17a0897 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h9b98cf6b12f01d0b
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
  34:     0x55fcb31b64e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he3e5dbdfabe0b668
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/alloc/src/boxed.rs:1985:9
  35:     0x55fcb31b64e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h246f7c7964633611
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/alloc/src/boxed.rs:1985:9
  36:     0x55fcb31b64e5 - std::sys::unix::thread::Thread::new::thread_start::hadf9e3501ff0df23
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys/unix/thread.rs:108:17
  37:     0x7f811a49fdd4 - start_thread
  38:     0x7f811a5219b0 - __clone3
  39:                0x0 - <unknown>
^C⏎            
```

**Comment by lsculv** [comment]
Shorter backtrace (easier on the eyes):
```
$ RUST_BACKTRACE=1 roc build
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread '<unnamed>' panicked at 'destructures cannot participate in a recursive group; it's always a type error', crates/compiler/can/src/def.rs:1654:29
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   2: sort_can_defs_new
             at ./crates/compiler/can/src/def.rs:1654:29
   3: canonicalize_module_defs
             at ./crates/compiler/can/src/module.rs:436:42
   4: canonicalize_and_constrain
             at ./crates/compiler/load_internal/src/file.rs:5282:25
   5: roc_load_internal::file::run_task
             at ./crates/compiler/load_internal/src/file.rs:6315:31
   6: worker_task
             at ./crates/compiler/load_internal/src/file.rs:2042:34
   7: roc_load_internal::file::load_multi_threaded::{{closure}}::{{closure}}
             at ./crates/compiler/load_internal/src/file.rs:1782:25
   8: crossbeam_utils::thread::ScopedThreadBuilder::spawn::{{closure}}
             at /home/lucas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/crossbeam-utils-0.8.16/src/thread.rs:440:31
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
  10: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/alloc/src/boxed.rs:1985:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
^C⏎ 
```
