### ISSUE TITLE
An internal compiler expectation was broken: region @17-6 not in list of dbgs

### ISSUE THREAD

**Issue by lindskogen** [roc-lang/roc#6097]
```
$ roc dev

An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread 'main' panicked at 'region @17-6 not in list of dbgs', /Users/m1ci/actions-runner2/_work/roc/roc/crates/repl_expect/src/run.rs:521:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```roc
app "hello"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.5.0/Cufzl36_SnJ4QbOoEmiJ5dIpUxBvdB3NEySvuH82Wio.tar.br" }
    imports [pf.Stdout]
    provides [main] to pf

main =
    dbg
        T (Str.split simple1 "\n\n")

    Stdout.line
        """
            Part 1: TODO
            Part 2: TODO
        """

simple1 =
    """
    1000
    2000
    3000

    4000

    5000
    6000

    7000
    8000
    9000

    10000
      
    """
```

Environment info:

```
roc nightly pre-release, built from commit 3d8884a96d4 on Fri Nov 24 09:18:30 UTC 2023
Apple M1 Max
macOS Sonoma 14.1.1
```

**Comment by lindskogen** [comment]
I managed to run the roc compiler in debug mode and found that the error is thrown here:

https://github.com/roc-lang/roc/blob/ef39bad7c61983f2329a11d2d23f7d038215c9d7/crates/repl_expect/src/run.rs#L521

**Comment by lindskogen** [comment]
I updated to `basic-cli 0.7.0` and recompile from source, and now I get another error:

```
ld: Undefined symbols:
  _roc_dbg, referenced from:
      _#UserApp_main_d394208415ac8fe0ce8aa0ddf6a845c7cc74d818698e3d25c85705ce311f5ec in roc_app1Bl6CO.o
main: is already signed
thread 'main' panicked at 'not yet implemented: gracefully handle `ld` (or `zig` in the case of wasm with --optimize) returning exit code Some(1)', crates/compiler/build/src/program.rs:1089:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
``` 

https://github.com/roc-lang/roc/blob/23c2b15115e9fd4e7224a17a388a020f3c74ffd3/crates/compiler/build/src/program.rs#L1089

**Comment by Anton-4** [comment]
I failed to reproduce this on an apple silicon mac running Sonoma.
I was running the code below with `roc hello.roc`:
```
app "hello"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.7.0/bkGby8jb0tmZYsy2hg1E_B2QrCgcSTxdUlHtETwm5m4.tar.br" }
    imports [pf.Stdout]
    provides [main] to pf

main =
    dbg
        T (Str.split simple1 "\n\n")

    Stdout.line
        """
            Part 1: TODO
            Part 2: TODO
        """

simple1 =
    """
    1000
    2000
    3000

    4000

    5000
    6000

    7000
    8000
    9000

    10000
      
    """

```

**Comment by Anton-4** [comment]
Can you give it a try with today's nightly @lindskogen?

**Comment by lindskogen** [comment]
Tried reproducing again today and the issue seems to have gone away!
