### ISSUE TITLE
test failures when running `cargo test` without `--release` flag

### ISSUE THREAD

**Issue by CrepeGoat** [roc-lang/roc#6100]
This is in reference to the local development test instructions at https://github.com/roc-lang/roc/blob/69b72866dbd7686ddd3b091516c683304328f292/CONTRIBUTING.md#running-tests

# setup
- open a macOS 13.4.1 (arm64) M1 macbook air
- clone the repo at https://github.com/roc-lang/roc/commit/69b72866dbd7686ddd3b091516c683304328f292
- run `nix develop`, as described in the test instructions

# the problem
Running `cargo test`, as described in the test instructions, produces a long error that ends with the suggestion
```
error: test failed, to rerun pass `-p roc_repl_expect --lib`
```

Running the reduced test suite `cargo test -p roc_repl_expect --lib` produces the below shorter error:
```sh
$ cargo test -p roc_repl_expect --lib
    Finished test [unoptimized + debuginfo] target(s) in 0.45s
     Running unittests src/lib.rs (target/debug/deps/roc_repl_expect-e018004a0c86f657)

running 26 tests
test test::equals_pass ... ok
test test::box_with_strings ... ok
test test::compare_long_strings ... ok
test test::adjacent_lists ... ok
test test::extra_offset_in_tag_union ... ok
test test::equals_fail ... ok
test test::arg_parser ... ok
test test::big_recursive_tag_copied_back ... ok
thread 'test::lookup_clone_result' panicked at 'misaligned pointer dereference: address must be a multiple of 0x8 but is 0x1701b5d94', crates/repl_expect/src/app.rs:57:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'test::lookup_clone_result' panicked at 'panic in a function that cannot unwind', library/core/src/panicking.rs:126:5
stack backtrace:
   0:        0x1031883c4 - std::backtrace_rs::backtrace::libunwind::trace::h35c35bd6a1eea1a3
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x1031883c4 - std::backtrace_rs::backtrace::trace_unsynchronized::h6e6a37fdc09ec2da
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x1031883c4 - std::sys_common::backtrace::_print_fmt::h6ae2889d87a644d1
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x1031883c4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb75be2413dd8ceb3
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x1031a9468 - core::fmt::rt::Argument::fmt::hfc9103857ff63de2
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/fmt/rt.rs:138:9
   5:        0x1031a9468 - core::fmt::write::h95d50546e769656f
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/fmt/mod.rs:1094:21
   6:        0x103184668 - std::io::Write::write_fmt::hce019ca594763835
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/io/mod.rs:1713:15
   7:        0x103188218 - std::sys_common::backtrace::_print::h15dce0f07dfee3db
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x103188218 - std::sys_common::backtrace::print::hae7307dcada41b2a
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x103189cd4 - std::panicking::default_hook::{{closure}}::h30c41986d637ef23
  10:        0x103189adc - std::panicking::default_hook::h81d03189ef2e7e78
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:288:9
  11:        0x1006e6e6c - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h609ad53f315a4b01
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/alloc/src/boxed.rs:1999:9
  12:        0x1006e6e6c - test::test_main::{{closure}}::hd329690e3ed79624
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/test/src/lib.rs:134:21
  13:        0x10318a270 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h6351ef30613d5f4e
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/alloc/src/boxed.rs:1999:9
  14:        0x10318a270 - std::panicking::rust_panic_with_hook::he8360f4d28da55fc
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:709:13
  15:        0x10318a014 - std::panicking::begin_panic_handler::{{closure}}::he9e07d605072520f
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:595:13
  16:        0x1031887a4 - std::sys_common::backtrace::__rust_end_short_backtrace::he03bf52f9c1eb73a
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:151:18
  17:        0x103189dc4 - rust_begin_unwind
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
  18:        0x1031ebdfc - core::panicking::panic_nounwind_fmt::h6a635b966d82551e
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:96:14
  19:        0x1031ebe78 - core::panicking::panic_nounwind::h241eff56ec55ba7a
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:126:5
  20:        0x1031ebf6c - core::panicking::panic_cannot_unwind::h911ff5cd61f62d63
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:188:5
  21:        0x100684bb8 - deref_str
                               at /Users/beckerawqatty/Repos/roc/crates/repl_expect/src/app.rs:47:5
  22:        0x100699a78 - addr_to_ast<roc_repl_expect::app::ExpectMemory>
                               at /Users/beckerawqatty/Repos/roc/crates/repl_eval/src/eval.rs:633:26
  23:        0x10069a964 - expr_of_tag<roc_repl_expect::app::ExpectMemory>
                               at /Users/beckerawqatty/Repos/roc/crates/repl_eval/src/eval.rs:304:20
  24:        0x10069958c - addr_to_ast<roc_repl_expect::app::ExpectMemory>
                               at /Users/beckerawqatty/Repos/roc/crates/repl_eval/src/eval.rs:718:13
  25:        0x10069e7f8 - {closure#5}<roc_repl_expect::app::ExpectReplApp>
                               at /Users/beckerawqatty/Repos/roc/crates/repl_eval/src/eval.rs:502:21
  26:        0x1006b48f0 - call_function_dynamic_size<roc_parse::ast::Expr, roc_repl_eval::eval::jit_to_ast_help::{closure_env#5}<roc_repl_expect::app::ExpectReplApp>>
                               at /Users/beckerawqatty/Repos/roc/crates/repl_expect/src/app.rs:144:9
  27:        0x10069dbb4 - jit_to_ast_help<roc_repl_expect::app::ExpectReplApp>
                               at /Users/beckerawqatty/Repos/roc/crates/repl_eval/src/eval.rs:498:13
  28:        0x1006962bc - jit_to_ast<roc_repl_expect::app::ExpectReplApp>
                               at /Users/beckerawqatty/Repos/roc/crates/repl_eval/src/eval.rs:70:13
  29:        0x1006b5444 - get_values
                               at /Users/beckerawqatty/Repos/roc/crates/repl_expect/src/lib.rs:71:13
  30:        0x1006a91a8 - render_expect_failure<alloc::vec::Vec<u8, alloc::alloc::Global>>
                               at /Users/beckerawqatty/Repos/roc/crates/repl_expect/src/run.rs:574:44
  31:        0x1006a8204 - run_expect_pure<alloc::vec::Vec<u8, alloc::alloc::Global>>
                               at /Users/beckerawqatty/Repos/roc/crates/repl_expect/src/run.rs:276:27
  32:        0x1006a7b14 - run_expects_with_memory<alloc::vec::Vec<u8, alloc::alloc::Global>>
                               at /Users/beckerawqatty/Repos/roc/crates/repl_expect/src/run.rs:219:22
  33:        0x1006a36c4 - run_expect_test
                               at /Users/beckerawqatty/Repos/roc/crates/repl_expect/src/lib.rs:176:34
  34:        0x1006a3e50 - lookup_clone_result
                               at /Users/beckerawqatty/Repos/roc/crates/repl_expect/src/lib.rs:407:9
  35:        0x1006b2ea4 - {closure#0}
                               at /Users/beckerawqatty/Repos/roc/crates/repl_expect/src/lib.rs:406:30
  36:        0x100689e88 - call_once<roc_repl_expect::test::lookup_clone_result::{closure_env#0}, ()>
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
  37:        0x1006eaff8 - core::ops::function::FnOnce::call_once::hdd7136f7e727049e
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
  38:        0x1006eaff8 - test::__rust_begin_short_backtrace::h982e7e4d425b370b
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/test/src/lib.rs:655:18
  39:        0x1006e9f30 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h798ebb6488e44ba8
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/alloc/src/boxed.rs:1985:9
  40:        0x1006e9f30 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hb61202be0a9afa59
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panic/unwind_safe.rs:271:9
  41:        0x1006e9f30 - std::panicking::try::do_call::h1238a7c9dd4da172
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:500:40
  42:        0x1006e9f30 - std::panicking::try::ha104f4cfbf9c9abf
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:464:19
  43:        0x1006e9f30 - std::panic::catch_unwind::hde39742198b6d1ec
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panic.rs:142:14
  44:        0x1006e9f30 - test::run_test_in_process::h8bd83a75e938bafc
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/test/src/lib.rs:678:27
  45:        0x1006e9f30 - test::run_test::run_test_inner::{{closure}}::hbd5f4261bd98af5a
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/test/src/lib.rs:572:39
  46:        0x1006bc000 - test::run_test::run_test_inner::{{closure}}::h10075b66460e4e3a
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/test/src/lib.rs:599:37
  47:        0x1006bc000 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4bb6d55a5573af99
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:135:18
  48:        0x1006c0ff4 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h3d33d70cf258ac61
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/thread/mod.rs:529:17
  49:        0x1006c0ff4 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h2a8008ad0e2c20b2
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panic/unwind_safe.rs:271:9
  50:        0x1006c0ff4 - std::panicking::try::do_call::h80cb45ea59a030e7
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:500:40
  51:        0x1006c0ff4 - std::panicking::try::h637156efe7c2c07f
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:464:19
  52:        0x1006c0ff4 - std::panic::catch_unwind::h3b38cfa4bc7fc552
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panic.rs:142:14
  53:        0x1006c0ff4 - std::thread::Builder::spawn_unchecked_::{{closure}}::h6765e063920f6a43
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/thread/mod.rs:528:30
  54:        0x1006c0ff4 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h6d9b734aff50ee99
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
  55:        0x10318f6c0 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6e76824cbc2fe276
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/alloc/src/boxed.rs:1985:9
  56:        0x10318f6c0 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hff5d24f551839383
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/alloc/src/boxed.rs:1985:9
  57:        0x10318f6c0 - std::sys::unix::thread::Thread::new::thread_start::h06dea01d0985d944
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys/unix/thread.rs:108:17
  58:        0x1a3737fa8 - __pthread_joiner_wake
thread caused non-unwinding panic. aborting.
error: test failed, to rerun pass `-p roc_repl_expect --lib`

Caused by:
  process didn't exit successfully: `/Users/beckerawqatty/Repos/roc/target/debug/deps/roc_repl_expect-e018004a0c86f657` (signal: 6, SIGABRT: process abort signal)
```

# a workaround
Running `cargo test --release`, in contrast, produces no test failures.

**Comment by LoipesMas** [comment]
This doesn't only happen in tests, here's a simple repro code:
```elixir
interface Issues
    exposes []
    imports []

# thread '<unnamed>' panicked at 'assertion failed: unspecialized.is_empty()', crates/compiler/mono/src/ir.rs:6144:9
# note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
# + spins
#expect
#    Dict.empty {} == Dict.empty {}

#thread 'main' panicked at 'misaligned pointer dereference: address must be a multiple of 0x8 but is 0x7ffff7e3008c', crates/repl_expect/src/app.rs:57:45
#note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
#thread 'main' panicked at 'panic in a function that cannot unwind', library/core/src/panicking.rs:126:5
# + core dump
expect 
    d1 = Dict.empty {}
        |> Dict.insert "a" 0 # either key or value has to be a string to reproduce

    # other Dict can be empty or not
    d2 = Dict.empty {}
        |> Dict.insert "b" 2

    d1 == d2
  ```
  If you run `cargo r -- test Issues.roc` you will get panics, but not with `cargo r --release -- test Issues.roc`
