### ISSUE TITLE
Implement `Num.sqrt`, `sqrtChecked`, `pow` for `Dec`

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#6208]
Trying to use these functions currently results in:
```
thread 'main' panicked at 'internal error: entered unreachable code: Unrecognized dec binary operation: NumPow', crates/compiler/gen_llvm/src/llvm/lowlevel.rs:2386:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

*Recommend workaround*: use `F64` or `F32` instead

**Comment by lindskogen** [comment]
I could give it a shot!

**Comment by Anton-4** [comment]
Awesome @lindskogen, I think the functions need to be added in [this file](https://github.com/roc-lang/roc/blob/main/crates/compiler/builtins/bitcode/src/dec.zig).

**Comment by lindskogen** [comment]
@Anton-4 I [posted on zulip](https://roc.zulipchat.com/#narrow/stream/316715-contributing/topic/ambient.20functions.20don't.20unify/near/406601072) that I'm currently stuck, but this is what I got so far: https://github.com/roc-lang/roc/compare/main...lindskogen:roc:implement-sqrt-pow-for-dec


I'm stuck on this error: `ambient functions don't unify`

**Comment by Anton-4** [comment]
I'll try to look at this tomorrow @lindskogen

**Comment by Anton-4** [comment]
I've simplified the error a bit (run with `roc test`):
```
interface Echo
    exposes []
    imports []

expect
    sqr = Inspect.toStr (Num.sqrt 4)
    sqr == "2.0"
```
Interestingly, the following versions do work:
```
    sqr = Inspect.toStr (Num.sqrt 4.0)
```
```
    sqr = Inspect.toStr (Num.sqrt 4dec)
```

**Comment by Anton-4** [comment]
I ran with `ROC_TRACE_COMPACTION=1 ./target/debug/roc test examples/cli/Echo.roc`.
1.
```
interface Echo
    exposes []
    imports []

expect
    sqr = Inspect.toStr (Num.sqrt 4dec)
    sqr == "2.0"

```
<details>
  <summary>Output for 1. </summary>
  
```
===lambda set compaction===
  concrete type: Opaque(`Num.Num`, [2786], <2786>Opaque(`Num.FloatingPoint`, [2782], <2782>RangedNumber( NumAtLeastEitherSign(I8))))
  step 1:
    uls_a = {  }
  step 2:
    uls_a' = {  }
  step 3:
===lambda set compaction===
  concrete type: Apply(`Str.Str`, [])
  step 1:
    uls_a = { LambdaSet([] + (<2794>Apply(`Str.Str`, []):`Bool.isEq`:1), ^<2791>) }
  step 2:
    uls_a' = { LambdaSet([] + (<2794>Apply(`Str.Str`, []):`Bool.isEq`:1), ^<2791>) }
  step 3:
    - iteration: LambdaSet([], ^<2791>)
         Func([<80>Apply(`Str.Str`, []),<81>Apply(`Str.Str`, []),], <2793=84>LambdaSet([], ^<2791>), <85>Opaque(`Bool.Bool`, [], <2795>['False' , 'True' , ]<Any(89)>))
      ~  Func([<2806>Flex(a),<2806>Flex(a),], <2805=2805>LambdaSet([`Bool.IdentId(11)` , ], ^<2803>), <2804>Opaque(`Bool.Bool`, [], <2807>['False' , 'True' , ]<Any(2808)>))
      =  Func([<2806>Apply(`Str.Str`, []),<2806>Apply(`Str.Str`, []),], <2793=2805>LambdaSet([`Bool.IdentId(11)` , ], ^<2791>), <2804>Opaque(`Bool.Bool`, [], <2795>['False' , 'True' , ]<Any(89)>))

===lambda set compaction===
  concrete type: Opaque(`Num.Num`, [3372], <3372>Opaque(`Num.FloatingPoint`, [3373], <3373>RangedNumber( NumAtLeastEitherSign(I8))))
  step 1:
    uls_a = {  }
  step 2:
    uls_a' = {  }
  step 3:
===lambda set compaction===
  concrete type: Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>)
  step 1:
    uls_a = { LambdaSet([] + (<2178>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>):`Inspect.init`:1), ^<2177>) }
  step 2:
    uls_a' = { LambdaSet([] + (<2178>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>):`Inspect.init`:1), ^<2177>) }
  step 3:
    - iteration: LambdaSet([], ^<2177>)
         Func([<269>EmptyRecord,], <2179=272>LambdaSet([], ^<2177>), <273>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>))
      ~  Func([<3376>EmptyRecord,], <3375=3375>LambdaSet([`Inspect.IdentId(36)` , ], ^<3374>), <2210>Opaque(`Inspect.IdentId(35)`, [], <311>{ 'data' : Apply(`Str.Str`, []), }<1>))
      =  Func([<3376>EmptyRecord,], <2179=3375>LambdaSet([`Inspect.IdentId(36)` , ], ^<2177>), <2210>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>))

===lambda set compaction===
  concrete type: Opaque(`Num.Num`, [3372], <3372>Opaque(`Num.FloatingPoint`, [3373], <3373>RangedNumber( NumAtLeastEitherSign(I8))))
  step 1:
    uls_a = { LambdaSet([] + (<2171>Opaque(`Num.Num`, [3372], <3372>Opaque(`Num.FloatingPoint`, [3373], <3373>RangedNumber( NumAtLeastEitherSign(I8)))):`Inspect.toInspector`:1), ^<2168>),LambdaSet([] + (<2171>Opaque(`Num.Num`, [3372], <3372>Opaque(`Num.FloatingPoint`, [3373], <3373>RangedNumber( NumAtLeastEitherSign(I8)))):`Inspect.toInspector`:2), ^<2174>) }
  step 2:
    uls_a' = { LambdaSet([] + (<2171>Opaque(`Num.Num`, [3372], <3372>Opaque(`Num.FloatingPoint`, [3373], <3373>RangedNumber( NumAtLeastEitherSign(I8)))):`Inspect.toInspector`:2), ^<2174>),LambdaSet([] + (<2171>Opaque(`Num.Num`, [3372], <3372>Opaque(`Num.FloatingPoint`, [3373], <3373>RangedNumber( NumAtLeastEitherSign(I8)))):`Inspect.toInspector`:1), ^<2168>) }
  step 3:
    - iteration: LambdaSet([], ^<2174>)
         Func([<274>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>),], <2173=277>LambdaSet([], ^<2174>), <278>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>))
      ~  Func([<3381>FlexAble(f, [`Inspect.InspectFormatter`]),], <3382=3382>LambdaSet([] + (<3381>FlexAble(f, [`Inspect.InspectFormatter`]):`Inspect.i64`:2), ^<3380>), <3381>FlexAble(f, [`Inspect.InspectFormatter`]))
      =  Func([<3381>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>),], <2173=3382>LambdaSet([] + (<3381>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>):`Inspect.i64`:2), ^<2174>), <3381>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>))

    - iteration: LambdaSet([], ^<2168>)
         Func([<263>Opaque(`Num.Num`, [3372], <3372>Opaque(`Num.FloatingPoint`, [3373], <3373>RangedNumber( NumAtLeastEitherSign(I8)))),], <2170=266>LambdaSet([], ^<2168>), <267>Opaque(`Inspect.Inspector`, [2172, 2173], <2174>Func([<3381>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>),], <2173=3382>LambdaSet([] + (<3381>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>):`Inspect.i64`:2), ^<2174>), <3381>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>))))
      ~  Func([<3397>Alias(`Num.I64`, [], <3398>Opaque(`Num.Num`, [3399], <3399>Opaque(`Num.Integer`, [3400], <3400>Opaque(`Num.Signed64`, [], <3401>EmptyTagUnion)))),], <3396=3396>LambdaSet([] + (<3402>FlexAble(f, [`Inspect.InspectFormatter`]):`Inspect.i64`:1), ^<3394>), <3395>Opaque(`Inspect.Inspector`, [3402, 3403], <3404>Func([<3402>FlexAble(f, [`Inspect.InspectFormatter`]),], <3403=3403>LambdaSet([] + (<3402>FlexAble(f, [`Inspect.InspectFormatter`]):`Inspect.i64`:2), ^<3404>), <3402>FlexAble(f, [`Inspect.InspectFormatter`]))))
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread '<unnamed>' panicked at 'ambient functions don't unify', /home/username/gitrepos/lindskogen/roc/crates/compiler/unify/src/unify.rs:201:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
</details> 
2.

Can you recommend next steps @ayazhafiz? Broad strokes is fine.
```
interface Echo
    exposes []
    imports []

expect
    sqr = Inspect.toStr (Num.sqrt 4dec)
    sqr == "2.0"

```
<details>
  <summary>Output for 2.</summary>
  
```
===lambda set compaction===
  concrete type: Opaque(`Num.Num`, [2787], <2787>Opaque(`Num.FloatingPoint`, [2783], <2783>Opaque(`Num.Decimal`, [], <3>EmptyTagUnion)))
  step 1:
    uls_a = {  }
  step 2:
    uls_a' = {  }
  step 3:
===lambda set compaction===
  concrete type: Apply(`Str.Str`, [])
  step 1:
    uls_a = { LambdaSet([] + (<2796>Apply(`Str.Str`, []):`Bool.isEq`:1), ^<2793>) }
  step 2:
    uls_a' = { LambdaSet([] + (<2796>Apply(`Str.Str`, []):`Bool.isEq`:1), ^<2793>) }
  step 3:
    - iteration: LambdaSet([], ^<2793>)
         Func([<81>Apply(`Str.Str`, []),<82>Apply(`Str.Str`, []),], <2795=85>LambdaSet([], ^<2793>), <86>Opaque(`Bool.Bool`, [], <2797>['False' , 'True' , ]<Any(90)>))
      ~  Func([<2808>Flex(a),<2808>Flex(a),], <2807=2807>LambdaSet([`Bool.IdentId(11)` , ], ^<2805>), <2806>Opaque(`Bool.Bool`, [], <2809>['False' , 'True' , ]<Any(2810)>))
      =  Func([<2808>Apply(`Str.Str`, []),<2808>Apply(`Str.Str`, []),], <2795=2807>LambdaSet([`Bool.IdentId(11)` , ], ^<2793>), <2806>Opaque(`Bool.Bool`, [], <2797>['False' , 'True' , ]<Any(90)>))

===lambda set compaction===
  concrete type: Opaque(`Num.Num`, [3372], <3372>Opaque(`Num.FloatingPoint`, [3373], <3373>Opaque(`Num.Decimal`, [], <3374>EmptyTagUnion)))
  step 1:
    uls_a = {  }
  step 2:
    uls_a' = {  }
  step 3:
===lambda set compaction===
  concrete type: Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>)
  step 1:
    uls_a = { LambdaSet([] + (<2178>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>):`Inspect.init`:1), ^<2177>) }
  step 2:
    uls_a' = { LambdaSet([] + (<2178>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>):`Inspect.init`:1), ^<2177>) }
  step 3:
    - iteration: LambdaSet([], ^<2177>)
         Func([<269>EmptyRecord,], <2179=272>LambdaSet([], ^<2177>), <273>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>))
      ~  Func([<3377>EmptyRecord,], <3376=3376>LambdaSet([`Inspect.IdentId(36)` , ], ^<3375>), <2210>Opaque(`Inspect.IdentId(35)`, [], <311>{ 'data' : Apply(`Str.Str`, []), }<1>))
      =  Func([<3377>EmptyRecord,], <2179=3376>LambdaSet([`Inspect.IdentId(36)` , ], ^<2177>), <2210>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>))

===lambda set compaction===
  concrete type: Opaque(`Num.Num`, [3372], <3372>Opaque(`Num.FloatingPoint`, [3373], <3373>Opaque(`Num.Decimal`, [], <3374>EmptyTagUnion)))
  step 1:
    uls_a = { LambdaSet([] + (<2171>Opaque(`Num.Num`, [3372], <3372>Opaque(`Num.FloatingPoint`, [3373], <3373>Opaque(`Num.Decimal`, [], <3374>EmptyTagUnion))):`Inspect.toInspector`:1), ^<2168>),LambdaSet([] + (<2171>Opaque(`Num.Num`, [3372], <3372>Opaque(`Num.FloatingPoint`, [3373], <3373>Opaque(`Num.Decimal`, [], <3374>EmptyTagUnion))):`Inspect.toInspector`:2), ^<2174>) }
  step 2:
    uls_a' = { LambdaSet([] + (<2171>Opaque(`Num.Num`, [3372], <3372>Opaque(`Num.FloatingPoint`, [3373], <3373>Opaque(`Num.Decimal`, [], <3374>EmptyTagUnion))):`Inspect.toInspector`:2), ^<2174>),LambdaSet([] + (<2171>Opaque(`Num.Num`, [3372], <3372>Opaque(`Num.FloatingPoint`, [3373], <3373>Opaque(`Num.Decimal`, [], <3374>EmptyTagUnion))):`Inspect.toInspector`:1), ^<2168>) }
  step 3:
    - iteration: LambdaSet([], ^<2174>)
         Func([<274>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>),], <2173=277>LambdaSet([], ^<2174>), <278>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>))
      ~  Func([<3382>FlexAble(f, [`Inspect.InspectFormatter`]),], <3383=3383>LambdaSet([] + (<3382>FlexAble(f, [`Inspect.InspectFormatter`]):`Inspect.dec`:2), ^<3381>), <3382>FlexAble(f, [`Inspect.InspectFormatter`]))
      =  Func([<3382>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>),], <2173=3383>LambdaSet([] + (<3382>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>):`Inspect.dec`:2), ^<2174>), <3382>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>))

    - iteration: LambdaSet([], ^<2168>)
         Func([<263>Opaque(`Num.Num`, [3372], <3372>Opaque(`Num.FloatingPoint`, [3373], <3373>Opaque(`Num.Decimal`, [], <3374>EmptyTagUnion))),], <2170=266>LambdaSet([], ^<2168>), <267>Opaque(`Inspect.Inspector`, [2172, 2173], <2174>Func([<3382>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>),], <2173=3383>LambdaSet([] + (<3382>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>):`Inspect.dec`:2), ^<2174>), <3382>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>))))
      ~  Func([<3398>Alias(`Num.Dec`, [], <3399>Opaque(`Num.Num`, [3400], <3400>Opaque(`Num.FloatingPoint`, [3401], <3401>Opaque(`Num.Decimal`, [], <3402>EmptyTagUnion)))),], <3397=3397>LambdaSet([] + (<3403>FlexAble(f, [`Inspect.InspectFormatter`]):`Inspect.dec`:1), ^<3395>), <3396>Opaque(`Inspect.Inspector`, [3403, 3404], <3405>Func([<3403>FlexAble(f, [`Inspect.InspectFormatter`]),], <3404=3404>LambdaSet([] + (<3403>FlexAble(f, [`Inspect.InspectFormatter`]):`Inspect.dec`:2), ^<3405>), <3403>FlexAble(f, [`Inspect.InspectFormatter`]))))
      =  Func([<3398>Alias(`Num.Dec`, [], <3399>Opaque(`Num.Num`, [3372], <3372>Opaque(`Num.FloatingPoint`, [3373], <3373>Opaque(`Num.Decimal`, [], <3374>EmptyTagUnion)))),], <2170=3397>LambdaSet([] + (<3403>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>):`Inspect.dec`:1), ^<2168>), <3396>Opaque(`Inspect.Inspector`, [2172, 2173], <2174>Func([<3403>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>),], <2173=3404>LambdaSet([] + (<3382>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>):`Inspect.dec`:2), ^<2174>), <3403>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>))))

===lambda set compaction===
  concrete type: Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>)
  step 1:
    uls_a = { LambdaSet([] + (<3382>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>):`Inspect.dec`:2), ^<2174>) }
  step 2:
    uls_a' = { LambdaSet([] + (<3382>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>):`Inspect.dec`:2), ^<2174>) }
  step 3:
    - iteration: LambdaSet([], ^<2174>)
         Func([<3403>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>),], <2173=3404>LambdaSet([], ^<2174>), <3403>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>))
      ~  Func([<3342>Opaque(`Inspect.IdentId(35)`, [], <1796>{ 'data' : Apply(`Str.Str`, []), }<1>),], <3407=3407>LambdaSet([`Inspect.IdentId(297)` <1779>Alias(`Num.Dec`, [], <2039>Opaque(`Num.Num`, [2040], <2040>Opaque(`Num.FloatingPoint`, [2041], <2041>Opaque(`Num.Decimal`, [], <2042>EmptyTagUnion)))) , ], ^<3406>), <3342>Opaque(`Inspect.IdentId(35)`, [], <1796>{ 'data' : Apply(`Str.Str`, []), }<1>))
      =  Func([<3342>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>),], <2173=3407>LambdaSet([`Inspect.IdentId(297)` <1779>Alias(`Num.Dec`, [], <2039>Opaque(`Num.Num`, [2040], <2040>Opaque(`Num.FloatingPoint`, [2041], <2041>Opaque(`Num.Decimal`, [], <2042>EmptyTagUnion)))) , ], ^<2174>), <3342>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>))

===lambda set compaction===
  concrete type: Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>)
  step 1:
    uls_a = { LambdaSet([] + (<3403>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>):`Inspect.dec`:1), ^<2168>),LambdaSet([`Inspect.IdentId(297)` <1779>Alias(`Num.Dec`, [], <2039>Opaque(`Num.Num`, [2040], <2040>Opaque(`Num.FloatingPoint`, [2041], <2041>Opaque(`Num.Decimal`, [], <2042>EmptyTagUnion)))) , ], ^<2174>) }
  step 2:
    uls_a' = { LambdaSet([] + (<3403>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>):`Inspect.dec`:1), ^<2168>) }
  step 3:
    - iteration: LambdaSet([], ^<2168>)
         Func([<3398>Alias(`Num.Dec`, [], <3399>Opaque(`Num.Num`, [3372], <3372>Opaque(`Num.FloatingPoint`, [3373], <3373>Opaque(`Num.Decimal`, [], <3374>EmptyTagUnion)))),], <2170=3397>LambdaSet([], ^<2168>), <3396>Opaque(`Inspect.Inspector`, [2172, 2173], <2174>Func([<3342>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>),], <2173=3407>LambdaSet([`Inspect.IdentId(297)` <1779>Alias(`Num.Dec`, [], <2039>Opaque(`Num.Num`, [2040], <2040>Opaque(`Num.FloatingPoint`, [2041], <2041>Opaque(`Num.Decimal`, [], <2042>EmptyTagUnion)))) , ], ^<2174>), <3342>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>))))
      ~  Func([<1779>Alias(`Num.Dec`, [], <2039>Opaque(`Num.Num`, [2040], <2040>Opaque(`Num.FloatingPoint`, [2041], <2041>Opaque(`Num.Decimal`, [], <2042>EmptyTagUnion)))),], <3410=3410>LambdaSet([`Inspect.IdentId(60)` , ], ^<3408>), <3409>Opaque(`Inspect.Inspector`, [3411, 3412], <3413>Func([<3411>Opaque(`Inspect.IdentId(35)`, [], <2235>{ 'data' : Apply(`Str.Str`, []), }<1>),], <3412=3412>LambdaSet([`Inspect.IdentId(297)` <1779>Alias(`Num.Dec`, [], <2039>Opaque(`Num.Num`, [2040], <2040>Opaque(`Num.FloatingPoint`, [2041], <2041>Opaque(`Num.Decimal`, [], <2042>EmptyTagUnion)))) , ], ^<3413>), <3411>Opaque(`Inspect.IdentId(35)`, [], <2235>{ 'data' : Apply(`Str.Str`, []), }<1>))))
      =  Func([<1779>Alias(`Num.Dec`, [], <3399>Opaque(`Num.Num`, [3372], <3372>Opaque(`Num.FloatingPoint`, [3373], <3373>Opaque(`Num.Decimal`, [], <3374>EmptyTagUnion)))),], <2170=3410>LambdaSet([`Inspect.IdentId(60)` , ], ^<2168>), <3409>Opaque(`Inspect.Inspector`, [2172, 2173], <2174>Func([<3411>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>),], <2173=3412>LambdaSet([`Inspect.IdentId(297)` <1779>Alias(`Num.Dec`, [], <3399>Opaque(`Num.Num`, [3372], <3372>Opaque(`Num.FloatingPoint`, [3373], <3373>Opaque(`Num.Decimal`, [], <3374>EmptyTagUnion)))) , ], ^<2174>), <3411>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>))))

===lambda set compaction===
  concrete type: Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>)
  step 1:
    uls_a = {  }
  step 2:
    uls_a' = {  }
  step 3:
```
</details>

**Comment by Anton-4** [comment]
This may be useful too, for:
```
sqr = Num.toStr (Num.sqrt 4)
```
```
❯ ROC_TRACE_COMPACTION=1 ./target/debug/roc test examples/cli/Echo.roc 
===lambda set compaction===
  concrete type: Apply(`Str.Str`, [])
  step 1:
    uls_a = { LambdaSet([] + (<2796>Apply(`Str.Str`, []):`Bool.isEq`:1), ^<2793>) }
  step 2:
    uls_a' = { LambdaSet([] + (<2796>Apply(`Str.Str`, []):`Bool.isEq`:1), ^<2793>) }
  step 3:
    - iteration: LambdaSet([], ^<2793>)
         Func([<80>Apply(`Str.Str`, []),<81>Apply(`Str.Str`, []),], <2795=84>LambdaSet([], ^<2793>), <85>Opaque(`Bool.Bool`, [], <2797>['False' , 'True' , ]<Any(89)>))
      ~  Func([<2808>Flex(a),<2808>Flex(a),], <2807=2807>LambdaSet([`Bool.IdentId(11)` , ], ^<2805>), <2806>Opaque(`Bool.Bool`, [], <2809>['False' , 'True' , ]<Any(2810)>))
      =  Func([<2808>Apply(`Str.Str`, []),<2808>Apply(`Str.Str`, []),], <2795=2807>LambdaSet([`Bool.IdentId(11)` , ], ^<2793>), <2806>Opaque(`Bool.Bool`, [], <2797>['False' , 'True' , ]<Any(89)>))


0 failed and 1 passed in 276 ms.

```

**Comment by ayazhafiz** [comment]
```
         Func([<263>Opaque(`Num.Num`, [3372], <3372>Opaque(`Num.FloatingPoint`, [3373], <3373>RangedNumber( NumAtLeastEitherSign(I8)))),], <2170=266>LambdaSet([], ^<2168>), <267>Opaque(`Inspect.Inspector`, [2172, 2173], <2174>Func([<3381>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>),], <2173=3382>LambdaSet([] + (<3381>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>):`Inspect.i64`:2), ^<2174>), <3381>Opaque(`Inspect.IdentId(35)`, [], <1824>{ 'data' : Apply(`Str.Str`, []), }<1>))))
      ~  Func([<3397>Alias(`Num.I64`, [], <3398>Opaque(`Num.Num`, [3399], <3399>Opaque(`Num.Integer`, [3400], <3400>Opaque(`Num.Signed64`, [], <3401>EmptyTagUnion)))),], <3396=3396>LambdaSet([] + (<3402>FlexAble(f, [`Inspect.InspectFormatter`]):`Inspect.i64`:1), ^<3394>), <3395>Opaque(`Inspect.Inspector`, [3402, 3403], <3404>Func([<3402>FlexAble(f, [`Inspect.InspectFormatter`]),], <3403=3403>LambdaSet([] + (<3402>FlexAble(f, [`Inspect.InspectFormatter`]):`Inspect.i64`:2), ^<3404>), <3402>FlexAble(f, [`Inspect.InspectFormatter`]))))

```

The issue looks like it's here. So an I64 is being compared to a `Num (FloatingPoint (RangedNumber >= I8))`, and clearly an I64 cannot unify with a floating point. The signature with the I64 type looks to be the specialized type of toInspector. So the next step is probably to figure out why that's happening there.

**Comment by Anton-4** [comment]
Excellent, thanks Ayaz :heart:

**Comment by skyqrose** [comment]
`pow` was implemented in https://github.com/roc-lang/roc/issues/6069 (issue) and https://github.com/roc-lang/roc/pull/6463 (PR).

`sqrt` has another more specific issue https://github.com/roc-lang/roc/issues/5831 so I'm closing this issue in favor of that one.
