### ISSUE TITLE
Crash on dbg 

### ISSUE THREAD

**Issue by salarii** [roc-lang/roc#6326]
app "test"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.7.0/bkGby8jb0tmZYsy2hg1E_B2QrCgcSTxdUlHtETwm5m4.tar.br" }
    
    imports [

        pf.Task.{ Task, await, loop },
        pf.Cmd,
        pf.Cmd.{Cmd},
        Utils,
        State,
        State.{StateType}
        ]
    provides [main] to pf

    
isDirectoryPath : Str -> Task Bool  *
isDirectoryPath = \ str ->
    command =
        Cmd.new "test"
        |> Cmd.args ["-d",  str]
        
    result <- Cmd.status  command |> Task.attempt
    when result is  
        Ok out ->
            Task.ok Bool.true
        Err _ ->
            Task.ok Bool.false

main =

    res <-isDirectoryPath "oo" |> Task.attempt
    dbg  res 
    Task.ok  {}

**Comment by Anton-4** [comment]
Full backtrace for extra info:
```
❯ RUST_BACKTRACE=1 ./target/release/roc examples/helloWorld.roc 
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates/compiler/mono/src/ir.rs:6156:56
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:117:5
   3: roc_mono::ir::with_hole
   4: roc_mono::ir::assign_to_symbol
   5: roc_mono::ir::assign_to_symbols
   6: roc_mono::ir::with_hole
   7: roc_mono::ir::assign_to_symbol
   8: roc_mono::ir::assign_to_symbols
   9: roc_mono::ir::call_by_name
  10: roc_mono::ir::with_hole
  11: roc_mono::ir::from_can_when
  12: roc_mono::ir::with_hole
  13: roc_mono::ir::assign_to_symbol
  14: roc_mono::ir::assign_to_symbols
  15: roc_mono::ir::call_by_name
  16: roc_mono::ir::with_hole
  17: roc_mono::ir::from_can
  18: roc_mono::ir::specialize_variable
  19: roc_mono::ir::Procs::insert_anonymous
  20: roc_mono::ir::with_hole
  21: roc_mono::ir::assign_to_symbol
  22: roc_mono::ir::assign_to_symbols
  23: roc_mono::ir::call_by_name
  24: roc_mono::ir::with_hole
  25: roc_mono::ir::from_can
  26: roc_mono::ir::specialize_variable
  27: roc_mono::ir::specialize_external_help
  28: roc_mono::ir::specialize_all
  29: roc_load_internal::file::run_task
  30: core::ops::function::FnOnce::call_once{{vtable.shim}}
```
