### ISSUE TITLE
Confusing error when mistakenly using commas in function application

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#652]
If I do `Num.add 1 1` in the repl, it works as expected.

However, if I mistakenly use a comma - like `Num.add 1, 1` - instead of getting a parse error, I get this:

```
Mismatch in compiler/unify/src/unify.rs Line 1057 Column 29
Trying to unify two flat types that are incompatible: Func([849, 851], 848, 844) ~ Func([10], 12, 13)

thread '<unnamed>' panicked at 'not yet implemented: TODO gracefully handle the situation where we expose a function to the host which doesn't have a valid layout (e.g. maybe the function wasn't monomorphic): UnresolvedTypeVar(13)', compiler/load/src/file.rs:2800:41
```

This should instead be a parse error!

**Comment by JanCVanB** [comment]
This is now a parse error!
```
[jan@framey roc]$ cargo run repl
    Finished dev [unoptimized + debuginfo] target(s) in 0.61s
     Running `target/debug/roc repl`

  The rockin’ roc repl
────────────────────────

Enter an expression, or :help, or :q to quit.

» Num.add 1 1

2 : Num *

» Num.add 1, 1
thread 'main' panicked at 'not yet implemented: unhandled parse error: Pattern(IndentEnd(@78), @76)', crates/reporting/src/error/parse.rs:532:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[jan@framey roc]$ 
```
