### ISSUE TITLE
"connection to server is erroring. Header must provide a Content-Length property” errors in VS Code

### ISSUE THREAD

**Issue by snej** [roc-lang/roc#6744]
- Installed Roc nightly on my MacBook Pro
- Installed the VS Code extension
- Opened a VS code window, pasted in the first “Building An Application” tutorial example, and saved it as “hello.roc"
- Several error notifications popped up:

`Client roc-lang: connection to server is erroring. Header must provide a Content-Length property. {"downloading \u001b[36mhttps":"//github.com/roc-lang/basic-cli/releases/download/0.10.0/vNe6s9hWzoTZtFmNkvEICPErI9ptji_ySjicO6CkucY.tar.br\u001b[0m\n into /Users/snej/.cache/roc/packages\n\nContent-Length: 38"} Shutting down server.`

`Client roc-lang: connection to server is erroring. Header must provide a Content-Length property. {"{\"jsonrpc\"":"\"2.0\",\"result\":null,\"id\":1}Content-Length: 38"} Shutting down server.`

`Client roc-lang: connection to server is erroring. Header must provide a Content-Length property. {"{\"jsonrpc\"":"\"2.0\",\"result\":null,\"id\":2}Content-Length: 157"} Shutting down server.`

The text in the editor does have colors, though, so I assume the language server is running now.

**Comment by snej** [comment]
Roc version is "roc nightly pre-release, built from commit dd9a6ff2e4a on Sat May 11 09:12:29 UTC 2024”

VS Code is Version: 1.85.0

**Comment by Anton-4** [comment]
Hi @snej,
Did you set `Roc-lang › Language-server: Exe` in the settings of the extension?
For me it is set to `/Users/admin/Downloads/temp2/roc_nightly-macos_apple_silicon-2024-05-13-e5ea6dc4617/roc_language_server`?
We mention it but it's easy to look over, I'll look into improving this.

**Comment by Anton-4** [comment]
Issues for improvements:
https://github.com/ivan-demchenko/roc-vscode-unofficial/issues/29
https://github.com/ivan-demchenko/roc-vscode-unofficial/issues/30

**Comment by Anton-4** [comment]
> The text in the editor does have colors, though, so I assume the language server is running now.

That will work without the language server. If you introduce an error in to the code, e.g by changing `Stdout.line` to `Stdout.lin` and the error is underlined in red, the language server is working.

**Comment by snej** [comment]
Yes, I entered the path to the language server.

If you look closely at the error, it looks as though the language server is echoing some compiler status output (about downloading a package) to the HTTP response stream before the response headers are complete, and only afterwards sends the Content-Length header. Perhaps that output is being redirected to the wrong FD?

`Client roc-lang: connection to server is erroring. Header must provide a Content-Length property. {"downloading \u001b[36mhttps":"//github.com/roc-lang/basic-cli/releases/download/0.10.0/vNe6s9hWzoTZtFmNkvEICPErI9ptji_ySjicO6CkucY.tar.br\u001b[0m\n into /Users/snej/.cache/roc/packages\n\nContent-Length: 38"} Shutting down server.`

**Comment by Anton-4** [comment]
Hmm, what seems wrong to me is that `{"downloading \u001b[36mhttps":"//github.com/roc-lang/basic-cli/releases/download/0.10.0/vNe6s9hWzoTZtFmNkvEICPErI9ptji_ySjicO6CkucY.tar.br\u001b[0m\n into /Users/snej/.cache/roc/packages\n\nContent-Length: 38"}` is not the json we want. `Content-Length` is not a separate json field, it's just concatenated with the other value string.

Can you try updating to the latest vscode (1.89)? That version works on my mac.

**Comment by ion1** [comment]
I am experiencing this with VSCode 1.102.3 on Windows 11.

The output:

```
LS executable path: Some(/home/ion/.local/bin/roc_language_server)
LS debug executable path: None
You are ready to Roc!Roc language server started
[Info  - 3:06:24 PM] Roc language server initialized.
[0.6 / 13.3 MB][Error - 3:06:26 PM] Client roc-lang: connection to server is erroring.
Header must provide a Content-Length property.
{"downloading \u001b[36mhttps":"//github.com/roc-lang/basic-cli/releases/download/0.19.0/Hj-J_zxz7V9YurCSTFcFdu6cQJie4guzsPMUi5kBYUk.tar.br\u001b[0m\n    into /home/ion/.cache/roc/packages\n\nContent-Length: 38"}
Shutting down server.
[1.4 / [Error - 3:06:26 PM] Client roc-lang: connection to server is erroring.
Header must provide a Content-Length property.
{"{\"jsonrpc\"":"\"2.0\",\"result\":null,\"id\":1}Content-Length: 38"}
Shutting down server.
[13.3 / 13.3 MB]
[Error - 3:06:28 PM] Client roc-lang: connection to server is erroring.
Header must provide a Content-Length property.
{"{\"jsonrpc\"":"\"2.0\",\"result\":null,\"id\":2}Content-Length: 450"}
Shutting down server.
[Error - 3:06:28 PM] Stopping server timed out
[Error - 3:06:28 PM] Stopping server failed
Error: Stopping the server timed out
    at /home/ion/.vscode-server/extensions/ivandemchenko.roc-lang-unofficial-1.2.0/dist/extension.js:1:95430
[Error - 3:06:28 PM] Stopping server failed
Error: Stopping the server timed out
    at /home/ion/.vscode-server/extensions/ivandemchenko.roc-lang-unofficial-1.2.0/dist/extension.js:1:95430
[Error - 3:06:28 PM] Stopping server failed
Error: Stopping the server timed out
    at /home/ion/.vscode-server/extensions/ivandemchenko.roc-lang-unofficial-1.2.0/dist/extension.js:1:95430
```

**Comment by lue-bird** [comment]
_not related to roc but for future readers with the same issue in other lsps that arrive here from search (feel free to delete as off-topic)_

This error implies that the server has a stray print to stdout or a child process that writes to an inherited stdout (which is typically the default). As LSPs usually communicate through stdio, these messages get misinterpreted. For what exactly has been sent, open the logs folder and check the latest modified log with the name of your extension which should have a message before the error.
