### ISSUE TITLE
`Num.neg` not supported for `Dec`, or for any `Num` except I64/U64 when in repl

### ISSUE THREAD

**Issue by Lubsch** [roc-lang/roc#6959]
When trying to build the following test program:
```
app [main] {
    cli: platform "https://github.com/roc-lang/basic-cli/releases/download/0.12.0/Lb8EgiejTUzbggO2HVVuPJFkwvvsfW6LojkLR20kTVE.tar.br",
}
import cli.Stdout

a : Dec
a = 10

main =
    Num.neg a
    |> Num.toStr
    |> Stdout.line
```
I get the output:
```
thread 'main' panicked at crates/compiler/gen_llvm/src/llvm/lowlevel.rs:2230:13:
internal error: entered unreachable code: Unrecognized dec unary operation: NumNeg
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

When investigating the source, it's clear that `Num.neg` is simply not implemented for `Dec`.
This isn't mentionend in the documentation or anywhere else I've looked.

Additionally, using `Num.neg` on any `Num` that's not `I64` or `U64` is not supported from the repl. For example:
```
» a : I32
… a = 10

10 : I32
» -a
thread 'main' panicked at crates/compiler/gen_dev/src/generic64/mod.rs:1794:18:
not yet implemented: NumNeg: layout, Builtin(Int(I32))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
You can of course work around this by subtracting from 0, but I think this should at least be documented.

**Comment by Anton-4** [comment]
Thanks for reporting this @Lubsch. I've created a PR with improved documentation. For anyone interested in implementing this, I suspect the claude 3.5 sonnet API can handle the implementation if you provide it with the rest of the file, if you get something working, bhansconnect can review it for correctness.

**Comment by Lubsch** [comment]
See also https://github.com/roc-lang/roc/issues/3513

**Comment by shua** [comment]
I can take this.

Question: for f32/f64, gcc/llvm will treat them like u32/u64 and xor the top bit (sign bit for f32/f64), [godbolt C example](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:___c,selection:(endColumn:2,endLineNumber:7,positionColumn:2,positionLineNumber:7,selectionStartColumn:2,selectionStartLineNumber:7,startColumn:2,startLineNumber:7),source:'/*+Type+your+code+here,+or+load+an+example.+*/%0Adouble+neg_f64(double+f)+%7B%0A++++return+-f%3B%0A%7D%0Afloat+neg_f32(float+f)+%7B%0A++++return+-f%3B%0A%7D'),l:'5',n:'0',o:'C+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:cg142,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:___c,libs:!(),options:'-O0',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+gcc+14.2+(Editor+%231)',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4). I tried doing this, but get an error about trying to load a float symbol in a general purpose register. Should I instead encode float negation as `0.0 - f`, or is there some way to load float symbols into general purpose registers that I don't know, and then I can implement the sign bit flip `f ^ 0x8000_0000`?

**Comment by Anton-4** [comment]
@bhansconnect

**Comment by shua** [comment]
I am looking now, and I was mistaken saying I need to load floats to general-purpose registers. llvm/gcc load them into floating point registers, but they then use `xorpd` or `xorps` which are bitwise logical xor of floating point values. Not generally useful, so we don't have any generator for that asm in the gen-llvm backend. I can add that if it makes sense?
