### ISSUE TITLE
language server `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#7153]
RestApi.roc:
```roc
module [get, post]

import json.Json

User : {
    name : Str,
    owes : Dict Str F64,
    owedBy : Dict Str F64,
    balance : F64,
}

Database : { users : List User }

get : Database, { url : Str, payload ? Str } -> Result Str _
get = \database, { url, payload ? "" } ->
    crash "Please implement the 'get' function"

post : Database, { url : Str, payload ? Str } -> Result Str _
post = \database, { url, payload ? "" } ->
    crash "Please implement the 'post' function"
```
main.roc:
```roc
# These tests are auto-generated with test data from:
# https://github.com/exercism/problem-specifications/tree/main/exercises/rest-api/canonical-data.json
# File last updated on 2024-09-09
app [main] {
    pf: platform "https://github.com/roc-lang/basic-cli/releases/download/0.15.0/SlwdbJ-3GR7uBWQo6zlmYWNYOxnvo8r6YABXD-45UOw.tar.br",
    json: "https://github.com/lukewilliamboswell/roc-json/releases/download/0.10.2/FH4N0Sw-JSFXJfG3j54VEDPtXOoN-6I9v_IA8S18IGk.tar.br",
}

main =
    Task.ok {}

import RestApi exposing [get, post]

standardizeResult = \result ->
    result
    |> Result.try \string ->
        string
        |> Str.replaceEach ".0," ","
        |> Str.replaceEach ".0}" "}"
        |> Str.toUtf8
        |> List.dropIf \c -> [' ', '\t', '\n'] |> List.contains c
        |> Str.fromUtf8

##
## user management
##

# no users
expect
    database = {
        users: [
        ],
    }
    result =
        database
        |> get {
            url: "/users",
        }
        |> standardizeResult
    expected = Ok "{\"users\":[]}"
    result == expected

# add user
expect
    database = {
        users: [
        ],
    }
    result =
        database
        |> post {
            url: "/add",
            payload: "{\"user\": \"Adam\"}",
        }
        |> standardizeResult
    expected = Ok "{\"balance\":0,\"name\":\"Adam\",\"owed_by\":{},\"owes\":{}}"
    result == expected

# get single user
expect
    database = {
        users: [
            {
                name: "Adam",
                owes: Dict.fromList [],
                owedBy: Dict.fromList [],
                balance: 0.0,
            },
            {
                name: "Bob",
                owes: Dict.fromList [],
                owedBy: Dict.fromList [],
                balance: 0.0,
            },
        ],
    }
    result =
        database
        |> get {
            url: "/users",
            payload: "{\"users\": [\"Bob\"]}",
        }
        |> standardizeResult
    expected = Ok "{\"users\":[{\"balance\":0,\"name\":\"Bob\",\"owed_by\":{},\"owes\":{}}]}"
    result == expected

##
## iou
##

# both users have 0 balance
expect
    database = {
        users: [
            {
                name: "Adam",
                owes: Dict.fromList [],
                owedBy: Dict.fromList [],
                balance: 0.0,
            },
            {
                name: "Bob",
                owes: Dict.fromList [],
                owedBy: Dict.fromList [],
                balance: 0.0,
            },
        ],
    }
    result =
        database
        |> post {
            url: "/iou",
            payload: "{\"amount\": 3.0, \"borrower\": \"Bob\", \"lender\": \"Adam\"}",
        }
        |> standardizeResult
    expected = Ok "{\"users\":[{\"balance\":3,\"name\":\"Adam\",\"owed_by\":{\"Bob\":3},\"owes\":{}},{\"balance\":-3,\"name\":\"Bob\",\"owed_by\":{},\"owes\":{\"Adam\":3}}]}"
    result == expected

# borrower has negative balance
expect
    database = {
        users: [
            {
                name: "Adam",
                owes: Dict.fromList [],
                owedBy: Dict.fromList [],
                balance: 0.0,
            },
            {
                name: "Bob",
                owes: Dict.fromList [
                    ("Chuck", 3.0),
                ],
                owedBy: Dict.fromList [],
                balance: -3.0,
            },
            {
                name: "Chuck",
                owes: Dict.fromList [],
                owedBy: Dict.fromList [
                    ("Bob", 3.0),
                ],
                balance: 3.0,
            },
        ],
    }
    result =
        database
        |> post {
            url: "/iou",
            payload: "{\"amount\": 3.0, \"borrower\": \"Bob\", \"lender\": \"Adam\"}",
        }
        |> standardizeResult
    expected = Ok "{\"users\":[{\"balance\":3,\"name\":\"Adam\",\"owed_by\":{\"Bob\":3},\"owes\":{}},{\"balance\":-6,\"name\":\"Bob\",\"owed_by\":{},\"owes\":{\"Adam\":3,\"Chuck\":3}}]}"
    result == expected

# lender has negative balance
expect
    database = {
        users: [
            {
                name: "Adam",
                owes: Dict.fromList [],
                owedBy: Dict.fromList [],
                balance: 0.0,
            },
            {
                name: "Bob",
                owes: Dict.fromList [
                    ("Chuck", 3.0),
                ],
                owedBy: Dict.fromList [],
                balance: -3.0,
            },
            {
                name: "Chuck",
                owes: Dict.fromList [],
                owedBy: Dict.fromList [
                    ("Bob", 3.0),
                ],
                balance: 3.0,
            },
        ],
    }
    result =
        database
        |> post {
            url: "/iou",
            payload: "{\"amount\": 3.0, \"borrower\": \"Adam\", \"lender\": \"Bob\"}",
        }
        |> standardizeResult
    expected = Ok "{\"users\":[{\"balance\":-3,\"name\":\"Adam\",\"owed_by\":{},\"owes\":{\"Bob\":3}},{\"balance\":0,\"name\":\"Bob\",\"owed_by\":{\"Adam\":3},\"owes\":{\"Chuck\":3}}]}"
    result == expected

# lender owes borrower
expect
    database = {
        users: [
            {
                name: "Adam",
                owes: Dict.fromList [
                    ("Bob", 3.0),
                ],
                owedBy: Dict.fromList [],
                balance: -3.0,
            },
            {
                name: "Bob",
                owes: Dict.fromList [],
                owedBy: Dict.fromList [
                    ("Adam", 3.0),
                ],
                balance: 3.0,
            },
        ],
    }
    result =
        database
        |> post {
            url: "/iou",
            payload: "{\"amount\": 2.0, \"borrower\": \"Bob\", \"lender\": \"Adam\"}",
        }
        |> standardizeResult
    expected = Ok "{\"users\":[{\"balance\":-1,\"name\":\"Adam\",\"owed_by\":{},\"owes\":{\"Bob\":1}},{\"balance\":1,\"name\":\"Bob\",\"owed_by\":{\"Adam\":1},\"owes\":{}}]}"
    result == expected

# lender owes borrower less than new loan
expect
    database = {
        users: [
            {
                name: "Adam",
                owes: Dict.fromList [
                    ("Bob", 3.0),
                ],
                owedBy: Dict.fromList [],
                balance: -3.0,
            },
            {
                name: "Bob",
                owes: Dict.fromList [],
                owedBy: Dict.fromList [
                    ("Adam", 3.0),
                ],
                balance: 3.0,
            },
        ],
    }
    result =
        database
        |> post {
            url: "/iou",
            payload: "{\"amount\": 4.0, \"borrower\": \"Bob\", \"lender\": \"Adam\"}",
        }
        |> standardizeResult
    expected = Ok "{\"users\":[{\"balance\":1,\"name\":\"Adam\",\"owed_by\":{\"Bob\":1},\"owes\":{}},{\"balance\":-1,\"name\":\"Bob\",\"owed_by\":{},\"owes\":{\"Adam\":1}}]}"
    result == expected

# lender owes borrower same as new loan
expect
    database = {
        users: [
            {
                name: "Adam",
                owes: Dict.fromList [
                    ("Bob", 3.0),
                ],
                owedBy: Dict.fromList [],
                balance: -3.0,
            },
            {
                name: "Bob",
                owes: Dict.fromList [],
                owedBy: Dict.fromList [
                    ("Adam", 3.0),
                ],
                balance: 3.0,
            },
        ],
    }
    result =
        database
        |> post {
            url: "/iou",
            payload: "{\"amount\": 3.0, \"borrower\": \"Bob\", \"lender\": \"Adam\"}",
        }
        |> standardizeResult
    expected = Ok "{\"users\":[{\"balance\":0,\"name\":\"Adam\",\"owed_by\":{},\"owes\":{}},{\"balance\":0,\"name\":\"Bob\",\"owed_by\":{},\"owes\":{}}]}"
    result == expected
```

The roc compiler and lsp on my path is from roc_nightly-linux_x86_64-2024-10-07-6cb2501

md5sum `which roc`
7d299380f5270497917f388af74292d3  /home/xxxx/bin/roc

md5sum `which roc_language_server`
32a158fc8ee775c874f535a41ed3e21e  /home/xxxx/bin/roc_language_server

I'm using Ubuntu 22.0.4:
```
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.5 LTS"
```
When I open RestApi.rocin Zed (0.155.2) I get the following in LSP Logs:
```
Roc language server initialized.
stderr: thread 'tokio-runtime-worker' panicked at crates/language_server/src/analysis.rs:301:71:
stderr: called `Option::unwrap()` on a `None` value
stderr: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
stderr: thread 'tokio-runtime-worker' panicked at crates/language_server/src/analysis.rs:301:71:
stderr: called `Option::unwrap()` on a `None` value
```

Full context: https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/load.3A.20UNRECOGNIZED.20PACKAGE.20.20opening.20Excerism.20file.20in.20Zed/near/475367369

**Comment by konnik** [comment]
Just tried on my MacBook and I can confirm that the same happens on apple silicon too.

**Comment by Anton-4** [comment]
Source of error is [here](https://github.com/roc-lang/roc/blob/b5e3c3e4411e49bf9b2b640d66a498e8cbe1690e/crates/language_server/src/analysis.rs#L30), it does not look too difficult to solve.

**Comment by drewolson** [comment]
I see the same error by opening [this file](https://github.com/drewolson/aoc-roc/blob/main/Aoc/Year2024/Day01.roc) within the larger project.

**Comment by chuckwondo** [comment]
I get the same problem for the Exercism exercise noted in the opening comment, but this is the source of the error for me: https://github.com/roc-lang/roc/blob/d7825428df72e3685be7291284c5eeeb1300a7f6/crates/compiler/mono/src/ir.rs#L6166

This error occurs for me when attempting to call either `Dict.fromList []` or `Dict.empty {}`:

```plain
thread '<unnamed>' panicked at crates/compiler/mono/src/ir.rs:6166:56:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by quecot** [comment]
I've found the same bug trying to solve the [Collatz Conjecture exercise in the Exercism track](https://exercism.org/tracks/roc/exercises/collatz-conjecture/edit).

My solution is as follows:

```roc
app [main] { pf: platform "https://github.com/roc-lang/basic-cli/releases/download/0.17.0/lZFLstMUCUvd5bjnnpYromZJXkQUrdhbva4xdBInicE.tar.br" }

import pf.Stdout

expect steps_rec 12 0 == 9

main =
    Stdout.line! "steps 12 -> $(Inspect.toStr (steps 12))"

steps_rec : U64, U64 -> U64
steps_rec = \number, stepsTaken ->
    if number == 1 then
        stepsTaken
    else if number % 2 == 0 then
        steps_rec (Num.floor (Num.toFrac number / 2)) (stepsTaken + 1)
    else
        steps_rec (3 * number + 1) (stepsTaken + 1)

steps : U64 -> Result U64 _
steps = \number ->
    Ok (steps_rec number 0)
```

Output (errors and gets stuck):

```sh
$ roc dev CollatzConjecture.roc
thread '<unnamed>' panicked at crates/compiler/mono/src/ir.rs:6246:56:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
^C
```

What I've also found is that if I change the `steps` function to return `Err` instead of `Ok`, it works as expected (albeit it's not what I want):

```roc
steps : U64 -> Result U64 _
steps = \number ->
    Err (steps_rec number 0)
```

Output:

```sh
$ roc dev CollatzConjecture.roc
steps 12 -> (Err 9)
```

**Comment by gamebox** [comment]
A quick unwrap_or_default() here would be sufficient

**Comment by gamebox** [comment]
I'd like to suggest that we address the other unwraps in /crates/language_server/src/analysis.rs as well at the same time as I think it wouldn't be crazy to figure out better behavior in all of these cases.

And then we can start addressing the panics, unwraps, and todos in parse, can, and and the type checking crates - basically anything upstream of the LS
